
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: John O
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKkx0NWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKlcoc.  .;kNWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK0x.   .;,   ,kNW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO'... .cOk;     ;0    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.  .cOk:..cxc   d    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX:  ;Ok:..cOk:. .oX    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc.  ',..cOk:.   '0W    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl.       :x:.  .ccoXW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl.            .. ,0MWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWWKl.          .ldxKXOKWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dc;''',;:cdOXWWWWWWWKl.          .oKWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWXx,.            .:xXWWKl.          .oKWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWW0;    ,ldxxoc:,.    .cc.          .oKWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWK;   ,kNWWWWWWWWKx:.             .oKWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWNc   '0WWWWWWWWWWWWK;           .oKWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWXl.  .kWWWWWWWWWWWKl.          .lKWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWNKOd,   .xWWWWWWWWWKko.            .oXWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWX0xdlc;,..     ;OWWWWWWWWKo.           .:.   ;0WWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWXkl;..        ..,lONWWWWWWWKo.           .oKW0;   'OWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWNkc.     .';cloxk0XWWWWWNko:;,.           .oKWWWWX:   ,KWWWWWWWWWWWWWWWWWWW    //
//    WWWNx,    .:dOKNWWWWWWWWWWWNk,               .oKWWWWWWW0'   oWWWWWWWWWWWWWWWWWWW    //
//    WW0;    ;xKWWWWWWWWWWWWWWWWx.              .oKWWWWWWWWWN:   :NMWWWWWWWWWWWWWWWWW    //
//    WO'   ,kNWWWWWWWWWWWWWWWWWX;              ;KWWWWWWWWWWWK,   lNWWWWWWWWWWWWWWWWWW    //
//    K,   :XWWWWWWWWWWWWWWWWWWWNc              dWWWWWWWWWWNO,   '0WWWWWWWWWWWWWWWWWWW    //
//    d.  '0WWWWWWWWWWWWWWWWWWWWW0,           .cXWWWWWNKkdc,    ,OWWWWWWWWWWWWWWWWWWWW    //
//    l   ;XMWWWWWWWNkccONWWWWWWWWXo,.     .;xKNWWWNkc,.     .,dXWWWWWWWWWWWWWWWWWWWWW    //
//    d   ,KWWWWWWWNo.   ;ONWWWWWWWWN0xdodkKNWWWWNk,    ..;cdONWWWWWWWWWWWWWWWWWWWWWWW    //
//    0'   oWWWWWWWW0c.    ;ONWWWWWWWWWWWWWWWWWWWd.   ,d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    Wd.  .xWWWWWWWWW0c.    ;ONWWWWWWWWWWWWWWWWO.   lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WNl   .xNWWWWWWWWW0c.    :ONWWWWWWWWWWWWMWl   ,KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWNo.  .cKWWWWWWWWWW0c.   .:ONWWWWWWWWWWMK,   lWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWNx.   'xNWWWWWWWWWW0c.   .OWWWWWWWWWWWd.  .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWW0:    ;kNWWWWWWWWWW0c';kNWWWWWWWWWKx,   cNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWNk,    ;kNWWWWWWWWWWNNWWWWWWWWWWXc.   .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWXx,    ;xXWWWWWWWWWWWWWWWWWWWXc    .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWXx,    'o0NWWWWWWWWWWWWWWNk,    .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWNk:.   .,okXWWWWWWWWWXx;    .;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWW0o,.    .,coddddl;.    ,xKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWN0o:.             .ckNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWXOxoc;,,,;:ldOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//                                                                                        //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract JOHN is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
