
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: No small talk was exchanged
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    "Lu's brother still won't give up. He'll send someone to keep an eye on us, or I'll beat them up."                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    Nie Zhongyou said, "No, brother Lu is not a bad man. We all belong to the army and do what we are ordered to do. There is no need to embarrass each other."                                                                                                                     //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    "Are we making it difficult for him? He made it difficult for us."                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    Nie Zhongyou and Li Xia did not respond.                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    Seeing that the game was not hot, Lin Zi said with a playful smile, "My brother is really biased. I used to give Nie Ping such good orders and play games in the Zhucui Building every day. Send me next time it happens. I haven't anything near the wood, except birds..."    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    "Shut up." Nie Zhongyou.                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    The forest turned a look, the original is Han Qiaoer carrying the breakfast out, the plate with steamed stuffed bun, steamed bread, pot stickers.                                                                                                                               //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    The little girl delicately laid the plate on the stone table, beckoned them to eat, and brought out a small cloth bag.                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    The sack contained several eggs. Han Qiaoer took them out and glanced at Linzi, hesitating, as if afraid that the bore might make fun of her again, but in the end she stood at the stone table and peeled them carefully.                                                      //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//    "Brother Li, this is for you."                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract NSTWE is ERC721Creator {
    constructor() ERC721Creator("No small talk was exchanged", "NSTWE") {}
}
