package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
)

// Networks is the resolver for the networks field. It is deliberately loaded from the configuration
// as networks change very infrequently, and you'd need to download new release regardless. No need to store them
// into the database...
// There is no need for any type of caching for this endpoint.
func (r *queryResolver) Networks(ctx context.Context, networkID *int, name *string, symbol *string, suspended *bool, maintenance *bool) ([]*Network, error) {
	return r.resolveNetworks(ctx, networkID, name, symbol, suspended, maintenance)
}

// Contracts is the resolver for the contracts field.
func (r *queryResolver) Contracts(ctx context.Context, networkIds []int, blockNumbers []int, blockHashes []string, transactionHashes []string, addresses []string, limit *int, first *int, after *string) (*ContractConnection, error) {
	return r.resolveContracts(ctx, networkIds, blockNumbers, blockHashes, transactionHashes, addresses, limit, first, after)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
