pragma solidity ^0.4.18;
pragma solidity ^0.4.0;

contract SimpleStorage {
    uint storedData;

    function set(uint x) public {
        storedData = x;
    }

    function get() public view returns (uint) {
        return storedData;
    }
}

//SPDX-License-Identifier: UNLICENSED
//rs34514405
//ATCGTGCCACTACACTCTCCAGCCTAGGTGACAGAGCGAGACTCTGTCAAAAAAGAAAAAAAAT
//TAGCACGGTGATGTGAGAGTCGGATCCACTGTCTCGCTCTGAGACAGTTTTTTCTTTTTTTTA
//rs7970368
//GCGGCCGCCTGTAGTCCCAGCTGCTCGGGAGGCTGAGGCAGGAGAATGGCGTTAACCCGGGAGG
//CGCCGGCGGACATCAGGGTCGACGAGCCCTCCGACTCCGTCCTCTTACCGCAATTGGGCCCTCC
//rs151057105
//GACTGATCTCAAACTCCTGACCTTATGATCCGCCTGCCTTGGCCTCCCAAAGTACTGGGATTAC
//CTGACTAGAGTTTGAGGACTGGAATACTAGGCGGACGGAACCGGAGGGTTTCATGACCCTAATG
//rs41288837
//CAAATCCCCCACCCCCTCGGCTGGCTCGTCCCACAGTAAGGAACCCACAGCCTCTCTTCCCCCT
//GTTTAGGGGGTGGGGGAGCCGACCGAGCAGGGTGTCATTCCTTGGGTGTCGGAGAGAAGGGGGA
//rs3217870
//TATAAATCCTAACTGTTGGTCAAGTTGATACCTCATTTCTATAATGGGCACACGCCGTGTTTCC
//ATATTTAGGATTGACAACCAGTTCAACTATGGAGTAAAGATATTACCCGTGTGCGGCACAAAGG
//rs28675824
//AACCACTGCACTCCAGCCTGGTGACAGAGCGAGACTCCTCAAAAAAAAAAAAAGAAAGAAAGAA
//TTGGTGACGTGAGGTCGGACCACTGTCTCGCTCTGAGGAGTTTTTTTTTTTTTCTTTCTTTCTT
//rs73390208
//ACCTCCTGCCTCTCCAGCCCTTCTGTCTGCCCCTCTCATCCCTCACACCCCCGCTCCCCTTAG
//TGGAGGACGGAGAGGTCGGGAAGACAGACGGGGAGAGTAGGGAGTGTGGGGGCGAGGGGAATC
//rs112204843
//CCAGGCCCCAGAATGGTAGATCTACTGACAGCTTTCACTATGTGTCTGGAAAAGCCACAGACAC
//GGTCCGGGGTCTTACCATCTAGATGACTGTCGAAAGTGATACACAGACCTTTTCGGTGTCTGTG
//rs2237468
//AGGAGCGCCAGGTCCACATCATGGTAGTTGCTTGCTCTCAGACCTGGGGTCTCTGGACACCAGC
//TCCTCGCGGTCCAGGTGTAGTACCATCAACGAACGAGAGTCTGGACCCCAGAGACCTGTGGTCG
//rs11154343
//CCAGCAGCTATCTCTCAGTCTAAAGAATGCCGTGCAGCTTGATGACACATTGATTGCTTTCCTT
//GGTCGTCGATAGAGAGTCAGATTTCTTACGGCACGTCGAACTACTGTGTAACTAACGAAAGGAA
//rs478839
//CCAGCAGCTATCTCTCAGTCTAAAGAATGCCGTGCAGCTTGATGACACATTGATTGCTTTCCTT
//GGTCGTCGATAGAGAGTCAGATTTCTTACGGCACGTCGAACTACTGTGTAACTAACGAAAGGAA