
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Forced to arrest shrimp farmers
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Wang Jue asked the other four to wait in the room for a while, then he got up and went back to the room where the team members were.                                                                                                                                      //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Looking at the crowd, Wang Jue turned to Chu Xuan. "Have you arranged the groups?"                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Chu Xuan faint response: "I and Zheng Zha, Zhang Jie, Zhan LAN, Li Xiaoyi, Bawang, zero and other new people a group, to the nearby temples and shrines to find a way to lift the curse."                                                                                 //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    "Then you might as well say I'm a group of people."                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Chu Xuan light answer way: "that pour not, still have two new appointee strong request must follow you."                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Finish to point to a side of zhao Yingkong and Qi Teng a.                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Wang Jue looked at the two people, secretly thinking, Zhao Yingkong skill is a good help, Qi Teng also some professional knowledge is ok, and their trip should not take too many people.                                                                                 //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Wang Chueh nodded and said, "Ok, yunning, let's go first."                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    Chu Xuan pushed the glasses on the bridge of his nose and slowly said: "I think you misunderstood me. I mean, they are only one group with you, and we also need a person who can deal with female ghosts. So, Yun Ning is one group with us."                            //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//    "I tm... Well, for the greater good, it's a reasonable allocation." Wang Jao went to Yunning silently and took out the Tang Hengdao from his pocket. It was always part of his body and was filled with qi, because this time it was too conspicuous in a modern city.    //
//                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract FTAS is ERC721Creator {
    constructor() ERC721Creator("Forced to arrest shrimp farmers", "FTAS") {}
}
