
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Different rubik's cube space
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//    Jing Shu's head also 'bang', and then unconscious.                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//    Yes, to activate this carryon space, no blood needs to be shed, no spells need to be cast, only to restore the disrupted Rubik's cube within a specified time, and it will take root in your spiritual world and recognize you as the master. Jing Shu spent nine years in her previous life to activate the Rubik's Cube space by chance.    //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//    Who's big enough to think a toy Rubik's cube is a space? Other people's space is either a ring, or a bracelet necklace, and then strange power head directly has a space.                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//    Besides, jing Shu's rubik's Cube space activation conditions are also so harsh, if not reborn to the impossible to know such a thing.                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                  //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DRCS is ERC721Creator {
    constructor() ERC721Creator("Different rubik's cube space", "DRCS") {}
}
