// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dutch Art Community
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMWWMMMMMMMMMMWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNXNWWWWNNNX0OOKXWMMMMMMMMMMWNWNNWWWMMMMMMWNXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXOOOOO000OOkddddxOKNWMMMMMMMMMWWNNWWWMMMMMMMNNNXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWNX0Okdoooodddooodk0XWWWWMMMMMMMWWWWNWWWWWWMMWNNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWMMMMMMWWNKOkxdooddoddoodkOKNWWWWMWWWWMMWWWNXXXNWWMMWNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWWWWWWWWWWWNK0OxdddddddddddddkOKXWWWWNKKKXNWMWNXXKXXNWWWWWNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWWWNNNNNNNKOxxxxxxxxxxxxxxxxxxO0XNWWNXK000KNWWNXXKKXXNWWWWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWWNNNXNNXK0OxxxxxxxxxxxxxxxxxxxO0XNWWNKOkkO0KXNNNXKKKXXNWWNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWNXKKXNXKKOkkkkkkkkkkkkkkkkkkkkkkO0XKK0OkkkkkO0KXNXKKKKKXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWWWNXXNWX0kOOkkOOkkOOOOOOOOkkOOOkOO00OOOOOOOOOO0KXNNXKKKXXNNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNXK0OOOOOOOOOOOOOOOOOOOOOOOOOOO000OOOOOOOOO00KKXKKKK0KXNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXNNXK000000000000000000000000000000000000000000000KKKKKXXXXNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWNWWXKKKXKXXkddxxxxddddxkO00000xooooodO0xooooodOkdoooooooooooooox0KXXKkxollooxOKWMMMMXOkkkkkKWXOkkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNXXXNWWWNXXKKKKKKKO;           ..;d0Kk'     .dO,     .oo.              .dKkc'.        .;xNMMo      cNx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWWWNNNNXXXXXNNXXXKKKKX0,      .'.     .oXO'     .dO'     .od...          ..'xk.     .:,      cNMo      :Nx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMWWWWWNXXXNNNNNXXXXXXXXXX0,      oK:      :X0'     .x0'     .dKOkOl.      .dOkOKc      :XO.     .OWo      :Nx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMWWWWWWWWWNNNNNNNXXXNNNNNK;      oXc      :X0'     .x0,     .dNXXNx.      'ONXNXc      cXO.     .kWl      'xc      ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWWWWWWWWWWNNNNNNNNNNNNK;      oNl      :X0'     .xK,     .dNNNNx.      'ONNNX:      cNKl;;,;,c0Nl               ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWWWWWWWWWWWNNNNNNNWK;      oNl      :N0'     .xK,     .dWNNWx.      '0WNWNc      cNWWWNWWWWWNl               ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWWWWWWWWWWWWWWWWWWX;      oWl      :N0'     .xK,     .xWWWWk.      '0WWWNc      cNXxllllldKWl      'o;      ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWWWWWWWWWWWX;      dWl      :NK,     .xK,     .xWWWWk.      '0WWWWl      cW0'     .kWo      :Nx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWWWWWWMWMX;      oK;      cNX;     .xK,     .kMWWMk.      '0MWMWd      cNO.     '0Wo      :Nx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;      ..      .dWWd.     .,      :XMMMMk.      ,0MMMMK;     .;'     .oNMo      :Nx.     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.............;xNMMWOc'.       .;xXMMMMMO'......;KMMMMMKo,.       .'cONMMd......lNk......cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00000KKKKKKXNWMMMMMMMNKOkxxxk0XWMMMMMMMWKKK0000XWMMMMMMMWKOkxxxkOKNMMMMMNK00000XMNK0KKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0kOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXXNWWMMMMMMMMMMWNXXXNKkkk0KXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOOkkkkkkkO0XWMMMMMWNK0OkkOXKkkkkkkkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkO0KXNNXX0Okk0XWMMN0Okk0KXNNKkkOKNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkOXWMMMMMMWXOkk0NWNKkkOKWMMMWKkkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkONMMMMWMMMWKkkOXNX0kk0NWWMMWKkkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMWKkkk0NWWWWWWWWKkkOXNX0kk0NWWWWWXOkk0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWNKOkkO0KKKXWWWKkkOXNK0kk0NWWWWWWX0kkk00KXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNX00Okkk0XWNKkkOXNK0kk0NWWWWWNWNXK0OOkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNWWWNWWNNXXXXNNNXXXXNNNXXXXNNNNNNNNNNNNNXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNWWNNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNWWNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl::::lkNMMMMMMMMMMWWMWWMMWNNXNWWXXNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkc::d00kkkKXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   ,;   lNNOdllod0WNkoodxoldkxcco0Kxlodolclxdllclk0dllokxlloOxlllolccd0d...:d'  .cxollO0ollkKKKKKKKKKKKKKKKKXWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   dx.  ;0l  .,. .o0,  .;.  .:.  ,x,  .,.  .,,.  'd,  .l,  .o:   ..   ll   'c.   ,l.  :o.  lKKKKKKKKKKKKKKKXNWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   dXkxx0O'  ,x'  ;k;  ,k;  ,k;  'd,  .d;  .ox,  .l,  .l,  .l:   c:   :l   ,x,  .o0:  ';. .dK00000000000000KKNWMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMX;   d0c;;dk'  ,d'  ,k;  ,k,  ,x,  ,k;  .d;  'dO;  .l,  .c,  .l;   ::   :c   ,x,  .l0d.  .  'k000000000000000000XWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   cl   cO,  'l.  :O;  ,k,  ,k;  ,O:  .l,  .dO;  .l,  .;.  .l;   :;   :c   ,d,   :Ok;     :OOOOOOOOOOOO0XXK0OOOXWMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,....,lKWk;.''''c0Xl'.lOl''l0l.'cOl..:kl..;k0l..;xo...'...'oc...cc...cl...;xl...'ld;    .oOkkkkkkkkOOkOO000OOkOKWMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXWMMMMWNXXXNMMMNNNNWNNNNWNNNNWNNNNWNXKKKXXXKKXX0xdxxxxxkxxxxxxxxxxxxxxxkkxxxxxl,',,;lxkkkkkkkkkkkkkkkkkkkkkk0XWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKXNNXNNX0kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxkxxxxxxxxxxxxxxxxxxkKWMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMWWXKKXXKXNKOxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0Oxxxxxxxxxxxxxxxxk0KXWMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWWX0KXXKXX0xddddddddddddddddddddddddddddddddddkXKkkxddddddddddddddxOXWMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKXNXXNKkdooodoooddoodooooooddddoooooddddod0NNNKxdoddodkOOOOkkKNWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNXKNWWNN0xoooooooxxoooooooooooddooooooooood0NMMNKkdoooxOOkxdxXMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXXNMMMMNkollllldkxolllllllllk0dllllllllllodOKNWWNK0kdllllldXMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWWWWWMMMN0olddlclxxollllllllkN0olllllllllllllodk0XWWNKxollxNMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkd00dcokkocccodlcxNWKxlccccccccccclolclxXWMWOokXMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKNXxo0X0dlclOkcoKMMW0dcccccccccccokdc:dXMMNNWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWNOx0NXOxlxX0dOWMMMWKdc:::::::::xXkclKMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMX0KWNNKOKWNNWMMMMMNkc;;;:;::;dXXdxNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMWNWWMMMMMMMMMMNd;;;:oo:l0WWXNMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxldkKXOkXMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DAC is ERC1155Creator {
    constructor() ERC1155Creator("Dutch Art Community", "DAC") {}
}
