
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Plan before you act
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Wang Jue opened his eyes and found yun Ning pan sitting beside him, the sun through the glass soft reflection on the beauty of the face, everything appears so quiet and warm.                                                                                                                      //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Wang Chueh stretched. "What time is it?" he asked lazily.                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Yunning got up slowly. "It's already nine o 'clock in the morning."                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    "Why didn't you wake me?" "Wang Jue asked.                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    In the face of Wang Jue's question, Yun Ning du mouth, slightly grievance said.                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    "See you tired......"                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    What else can Wang Jue say? These three words have shattered his disguise and tenacity completely. For a time he was speechless.                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Two people so four eyes relative, for a long time, yun Ning some shy lower head way: "are you hungry, I get some food for you."                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Wang Jue looked at Yun Ning flattered, "er...... Don't bother. I'll just eat some dry, compressed food."                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    "Then I'll get you a glass of water." Yunning didn't wait for Wang Jue to respond and walked out of the bedroom.                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    "I wonder what's wrong with her today? She's suddenly such a good wife and mother. I didn't set her up with such a character."                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    But hear a sneer at this time, "how, contend for pet bai, show oneself bai." Ming Yanwei sat up in bed, smiling contemptuously.                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    "Really funny, she actually thought I would rob a man with her, ha ha." Say that finish oneself stretch a lazy waist; The belt is gradually wide, luo Unlined half untie, reveal oneself extremely proud person's figure.                                                                           //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Wang Jue looked at that exciting scene, coupled with the physical reaction in the morning, couldn't help but think wildly.                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Wang Jue rubbed his face and threw his thoughts out of his mind. He said to himself, "An ape who keeps his mind fixed needs to realize emptiness. Wang Jue, you are an old driver, you have to stand the test, Jiang Gong Lei is not mature, look at the tragic situation of zhang Lingyu......"    //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
//    Ming Yanwei straightened up her clothes and looked at Wang Jue, who w                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PBYA is ERC721Creator {
    constructor() ERC721Creator("Plan before you act", "PBYA") {}
}
