
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Some truth in
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//    Embroider river is very delicate, green wave ripples, without what gust strength wave, water surface is broad to give a person wen wan feeling however.                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//    Chen Pingan four people in the south of the ship has two layer, how is the blue Confucian scholar and merchants traveler, Li Bao bottle is not timid around strangers, like carrying a small case to group together, ears listening to their talk, the general scholars see a reiki girl, also carry a small travel flicker of bamboo books, it is quiet and demure, stood not far not close, The grown-ups, with good-natured smiles, did not take the little girl to heart, and went on talking.                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//    Li Huai carefully controlled the REINS, riding a white donkey in the bow of a small area around the circle, as patrol border general, arrogant. Strange to say, really just want to let white donkeys Li Huai riding, this let Li Huai happy is broken, as to what the snow temple gods of wei and jin dynasty, the future is to want to held the donkey, then let Li Huai remember with that person for the payment, just keep the lion big openings, the really important things, instead of the whole to Li Huai as fallen on deaf ears.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//    Lin Shouyi came to Chen Ping an's side, back against the wall of the boat and sat, hesitated for a moment, asked: "You don't want to know, why liang said I am qi shi? And how did he become a practicing qi scholar?"                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//    Chen Ping an stopped his chopping action and smiled: "Of course I want to know, but I don't have any interest in asking, afraid of your thinking."                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STI is ERC721Creator {
    constructor() ERC721Creator("Some truth in", "STI") {}
}
