// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: KOKOU YOUGI GRAFFITI
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMTYUM@TTTTY"TTTM"UMMMMY"TW@"TTT#"TYMMMMMMM@"MMTW@TYMM"TM@TMYTTM@"MYTMMMMMMYT#"WM9TTM#"W@"MMTYWMMY"TWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM<(#~JMM>(M@~dMMN~(MMMMM~(MF~dMM#~J]~MMMMMM$~?JN@~Jr~H~(1(M{_#~JF~d>_M"""HM>(#~J]~M~(#~Jr~H~(NNMMM~(MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM<(&~JMM>(M@~(&MN~(MMMMM~(MF~+&M#~(/dMMMMMM$~J?M@~Jr~H~_,(W: K_JF~d_ H.   g` $.J]~M_(D J%_M~(J<dMM~(MMMMMMM"""""""""WMMMMMMMM""""77?!?TMM"=?TMMMMMMMMM    //
//    MMMMD!    ``!???77""""YMMMMMMMMMMMMMMMMMMMMMMMMM"WM<(#~JMM>(M@~dMMN~(MMMMM`(M]`dMM#~J]~MMMMMM$~MJ/8~Jr_M .h,?>.K ,] d_ MMMMMMM_.HM]~M .b.-} p .F_dMM~(MMMMM^     ....   `       ........    ..  HMMMMMMM    //
//    MMM#  .J(............. .""""""""""""""7?!`        HJJNJJMMgJMNJJJJNJ...Jg(...h..JJNJJmJMMMH"MmJMMJJhJJdH.(MhJM&J.#Ma..NMMMMMMMJ.K(Ha..MMhJJMMN...dM&JJJMMMM. .MMMMMMM.....(J&.  JMMMMMM].(MMMM,  HMMMMMM    //
//    MMM#  dMMMMMMMMMMMMMM\..        ..........(+gNMMM, .MMMMMMMMMMMMMMH%  MMMMMMM#                ..  MMMb  ,MMMMMMMN,dMMMMMMMMMMMMMMNNp.JMMMMMMMN....    HMMMM; .MMMMMMMMMMMMMMM;  (MMMMMM],MMMMMM,  MMMMMM    //
//    MMMF  dMMMMMMMMMMMMMM:MMMMMMMMMMMMMMMMMMMMMMMMMMMb  ~`                MMMMMMMM.(+gggNNMMMMMMMMM#  dMMMN,  TMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMM#  dMMH"' .MMMMMMMMMMMMMMM\  .MMMMMMb ,MMMMMM,  MMMMM    //
//    MMMF  MMMMMMMMMMMMMMM_MMMMMMMMMMMMMMMMMMMMMMMMMMMM. ...J+gggNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  (MMMMMp  (MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMF          MMMMMMML.....J+gg .MMMMMM#  ,MMMMM#  .MMMM    //
//    MMMN,        .MMMMMMF.MMMMMMMMMMMMMMMMMMMMMMMMMH""' .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. .MMMMMMN,  WMMMM#4MMMMMM\   _?7UMMMMMMM"""MMMMMMM\  MMMMMMMMMMMMMMMMMMMMMMMMM  MMMMMMM   ,Y"` .  -MMMM    //
//    MMMMMMMMB"  .MMMMMMF .MMMMMMF7MMMMMM#~`,MMMMMM#  .. .MMMMMMMMMMMMMMMMMMMMMMMMMH"""""""7?!`        -MMMMMMMMe  ?M"  dMMMMMMNggJ.....TMMMMa......       dMMMMMMMMMMMMMMMMMMMMMMMM. dMMMMMMggMMMMMMM) .MMMM    //
//    MMMMMMM]  ..MMMMMMF  .MMMMMM] MMMMMMF  .MMMMMM#  g]  M"""""""77!~` ..........J&ggNNMMMMMMM  .gggNMMMt              MMMMMMMMMMMMMMM\ MMMMMMMMMMMMMMF   JMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb  MMMM    //
//    MMMMMMM\ .MMMMMMMD   .MMMMMM] MMMMMMF  .MMMMMM#  dN,       (MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM- .MMMMMM#  (NNggJ..... .MMMMMMMMMMMMMMM`.MMMMMMMMMMMMMM%   (MMMMM@ .MMMMMN..(dMMMMMMMMMMMMMMMMMMMMMMMM#  dMMM    //
//    MMMMMMM: .MMMMMMF    JMMMMMM\ MMMMMM]  (MMMMMM@  dMMMMMMM. .MMMMMMMMMMMMMMMMMMMMH"WMMMMMMM[ .MMMMMMF  dMMMMMMMMMM!(MMMMMMYTMMMMMM#  _?7""""MMMMMMM`   .MMMMMNNMMMMMMMMMMMF"""WMMMMMMMMMMM""""7!`    JMMM    //
//    MMM^     .MMMMMMa.Jg dMMMMMM!.MMMMMM\  (MMMMMM@  dMMMMMMM; .MMMMMMM]          .....MMMMMMM]  MMMMMM%  MMMMMMMMMM# MMMMMMM .MMMMMMF     .agMMMMMMM=  . .MMMMMMMMMMMMMMMMMMFdMMMMF!`MMMMMMM- .MNg...  MMMM    //
//    MM#  dMMMMMMMMMMMMMM MMMMMMM .MMMMMM}  (MMMMMM@  dMMMMMMM]  MMMMMMMNNNMMMMMMMMMMMMMMMMMMMMb  MMMMMM;  7"TUMMMMMMF.MMMMMMF (MMMMMM\.g+(.dMMMMMMM"   .' .MMMMMM""MMMMMM+....MMMMMF  JMMMMMM] MMMMMM$  MMMM    //
//    MM#  dMMMMMMMMMMMMMM.MMMMMM# .MMMMMM:  (MMMMMM@  dMMMMMMM]  MMMMMMMMMMMMMMMMMMMMMMMMMMMMH"9       4Ng..  JMMMMMM]MMMMMMM> dMMMMMM`dMMMMMMMMMMMMMNR     MMMMMM_ MMMMMMMMMMMMMMMM]  .MMMMMMN(MMMMM@  -MMMM    //
//    MM#  JMMMMMMMMMMMMM#.MMMMMMF .MMMMMM`  (MMMMMM#  dMMMH"""^  MMMMH"""""""7?!`  .........J+gggNNMM{ .MMMF  MMMMMMMdMMMMMMF .MMMMMM# MMMMMMMMMMMMMMM#  ;  MMMMMM} ?MMMMMMMMMMMMMY=    MMMMMMMMMMMMM` .MMMMM    //
//    MM#  ?"""HMMMMMM    (MMMMMM] .MMMMMM   .MMMMMMN  JMMF  ........J&ggNNMMMMMMMMMMMMMMMMMMMMMMMMMMM]  MMM% .MMMMMMMMMMMMMM^ .MMMMMMF """"HMMMMMMMMMM]  ]  MMMMMM) . .........(J MNag, (MMMMMMMMMMM^  TMMMMM    //
//    MMMx     dMMMMMN    MMMMMMM! (MMMMM#..JgMMMMMMM. .MM@  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMF  MMM! .MMMMMMMMMMMMMN..MMMMMMM!     dMMMMMM# _?` .F  MMMMMMMMMb.MMMM)dMMMN.MMMM% .MMMMMMMMMMNa,.   4MM    //
//    MMMMMMF  MMMMMM#   .MMMMMM#  JMMMMM#(MMMMMMMMMM| .MM#  JMMMMMMMMMMMMMMMMMMMMMMMH"""""""7?qMMMMMM@  dMD  (MMMMMM@MMMMMFMMMMMMMMM# .MNggMMMMMMMF  ...MF  MMMMMMMMMMJMMMM]dMMMMMMMMF   dMMMMMMMMtMMMMM|  MM    //
//    MMMMMMF  MMMMMM#   dMMMMMMF  dMMMMM#.MMMMMMMMMMb  dMM  (MMMMMM#7?!`  .........J+gggNMMN  .MMMMMM#     ..MMMMMMMM,(HMF MMMMMMMMM% .MMMMMMMMMMM{ .MMMM% .MMMMMMMMMMMMMMM](MMMMMMMM!   .MMMMMMM\ MMMMM[ .MM    //
//    MMM#""3  MMMMMMF  .MMMMMMM`  dMMMMM@.MMMMMMMMMMM. .MM_ .MMMMMMN  .MMMMMMMMMMMMMMMMMMMMM  .MMMMMMM  .gMMMMMMMMMMMMN&,. ""WMMMMMt  .MMMMMMMMMM#  (MMMM  .MMMMMM?MMMMMMMMF.MMMM{_Tn, .MMMMMMMMMb.MMMMM{ .MM    //
//    MM]  .  .MMMMMMF .MMMMMMMN..+MMMMMMMMMMMMMMMMMMMb  vM) .MMMMMMM. .MMMMMMMMMMMMMMMMMMMMM-  MMMMMMM_ .MMMMMMMMMMMMMMMMMMMNg+.....    _?"T""HH"`  ""MMF  dMMMMMM XMMMMMMMN.MMMMMMMMNMMMMMMMMMMMMMMMMMM  .MM    //
//    MM[ .MMMMMMMMMM].MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMp  W]  MMMMMMM;  MMMMMM       ..dMMMMM[ .MMMMMMM)  .MMMMM@^ .YMMMMMMMMMMMMMMMMMMMMMNNggJ......   ,  .MMMMMMF .i..MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMF  dMM    //
//    MM] .MMMMMMMMMM\ TMMMMMM4MMMMMMMMMMMMMMMMMMMMMMMMM! .F  MMMMMMM]  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\   ,#"`  ...  ."WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM: .e  ?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM@` ?MMMMMMMM#  .MMM    //
//    MM]  MMMMMMMMM#   .HMMM3.MMMMH"""!`   MMMMMXMMMMD  .MN  dMMMMMM]  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM! ..   .(MMMMNa..    _7""WMMMMMMMMMMMMMMMMMMMM#  (Mh. ,MMMFdMMMMMMMMMMMM""=`  WMMM"  ..  TMMMMMD  .MMMM    //
//    MMb    `??777!  .,  ?M^        ....,  MMMMM!TMM^  .MMN  JMMMMMMb  JMMMMMF7?!`       dMMMMMMMMMMY^  dMMMMMMMMMMMMMMMNgJ...         ??7"T""HMMMMMF  MMMN,  W# (MMMM"""!     ...,  ?`  .dMMm.       .(MMMMM    //
//    MMMNgJ.........MMMh.   .gNNMMMMMMMMN         ?  .MMMMM  .MMMMMM#  ,"77!!` ....(+gg. .!~``        .MMMMMMMMMMMMMMMMMMMMMMMMMMNNggJ......          .MMMMMe          ....gNMMMMMMN,..(MMMMMMMMNNgggMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNgMMMMMMMMMMMMMMMgJgNMMm...JMMMMMM; ."""""7!  .......JMMMMMMMMNJ.......JggMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNggMMMMMMMMN-.++&gMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,  .......gMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                                                              //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract KKYGG is ERC721Creator {
    constructor() ERC721Creator("KOKOU YOUGI GRAFFITI", "KKYGG") {}
}
