// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Inside
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    cool,     ...    ';:::cooooooodxkkkxxxxxxxdoodxkkkkkkkkkkkkkkkkxdoooooooooolc::::;:c::::::::::::::::::;;;,,,,,,,,,,,,,,,,;;;:::;::;;:::::::::::::cdxxxxdlooooooooooooooollllllooooooooooooooodxdolcc::::::::::::;;,,,,,,,,,,,,,;;;:::::;;;,;:loooooooooolc::::::::;.    .dOO00OOOx:,,:::::,,cxOOOOOOOOOOO000    //
//    loc'     .;:.    .;::clooooodxxkkkkxxxxxddoodxkkkkkkkkkkkkkkkkxdoooooooooolc::::::::::::::::::::::::;;;,,,,,,,,,,,,,,,;;;;::::::::::::::::::::::::coxxxdooooooooooolc:;;;;;;;;;;:clodddooooooooooooollcc:::::::::;;;,,,,,,,,,,,,,;;:::::;;;;,;:cloooooooolc:::::::;.    .oOOOOOOOOdc:::::::cdOOOOOOOOOOOO000    //
//    o:.     .:ol'    .,:cloooodxxkkkkkxxxddooodxkkkkkkkkkkkkkkxxddoooooooooolc:::::::::::::;;;;;:::::;;;,,,,,,,,,,,,,,;;;;:::::::::::::::::::::::::cccccloddoooodddddddolccllllllllllodxxxxdoooooooooooooooolllc:::::::::;;,,,,,,,,,,,,,;;::::::;;,,;:clooooooolc:::::;.    .cOOOOOOOOko::::::cokOOO0OOO0OOOOOOO    //
//    ;.    .,lool,    .,:loddddxkkkkkkkxdooooodxkkkkkkkkkkkkkxddooooooooooolc::;:::::::::;;;,,,,,;;;;;,,,,,,,,,,,,,,;;;:::::::::::::::::::ccccllloooooooooooooodxkkkkkkkkkkkkkkkkxxxxxddoooooooooooooooooooooooooolc::::::::;;,,,,,,,,,,,,,;;;:::::;;,,,;:clooooolc:::::'     ;kOOOOOOOOkoc:::cokOOOOOOOOOOOOOOOO    //
//         .;loooo;.    ,lodxxxkkkkkkkkxdooooodxkkkkkkkkkkkkkxdooooooooooolc::::;;;;;;::;;,,,,,,,,,,,,,,,,,,,,,,,;;;;:::::::::::::::cccllloooooooooooooooooooodxxxkkkkkkkkkkkkOkkkxxxdddddddodoooooooooooooooooooooooollc::::::;;;,,,,,,,,,,,,,;::;:::;;,,,,,:coooool::::'     ,xOOOOOO00OkxoodxOOOOOOOOOOOOOOOOOO    //
//        'cooooooc.    ,odxxkkkkkkkxkkxdoooodxkkkkkkkkkkkkkkkdooooooooolc::::;;,,,;;;;;,,,,,,,,,,,,,,,,,,,,,,,;;:::::::::::::::cclloooooooooooooooooooooooooodxkxxxxxxxxxxxxxxxxxddddddxxxxxddooooooooooooooooooooooooooolc:::::::;;,,,,,,,,,,,,;;::::;;,,,,,;:loooolc::,.    .oOOOOOOOOOOOOOOOOOOOOOOOO0OO0OOOOO    //
//      .,loooooool.    'oxxkkkkkkxdddddoooooxkkkkkkkkkkkkkkxdoooooooolc::::;;;,,,,,,;,,,,,,,,,,,,,,,,,,,,,,;;;;:::::::::::::clllooooooooooooooooooooooooooooooddddooodooooooooooooooooooooooooooooooooooooooooooooooooooooollc:::::;;;,,,,,,,,,,,,;;:::;,,,,,,,:loooool:;.     :kOOOO00OOOOOOOOOOOOOOOOO0OOOOOOOO    //
//     .;looooooool'    .oxxkkkkkxdooooooooddxkkkkkkkkkkkkkxdooooooolc:::::;;,,,,,,,,,,,,,,;:c;,,,,,,,,,,,;;:::::::::::::ccllooooooooooooooooooooooooooooooooooooooooooooooooooddodddddddddddddooooooooooooooooooooooooooooooooolc::::::;;;,,,,,,,,,;;;;;;,,,,,,,;looooolc,     'dOOOOOOOOOO00OOOOOO0OOOOOOOOOOOOO    //
//     .:oooooooool'    .oxkkkkkxdooooooodxddxkkkkkkkkkkkxdooooooolc:::::::;,,,,,,,,,,,,,;colc;,,,,,,,,;;;;:::::::::::ccloooooooooooooooooooooooooooooooooooooooddddddddxxxxxxxxkkxkkkkkkxxxxxxddddooooooooooooooooooooooooooooooollc::::::;;;,,,,,,,,,,,,,,,,,,,,;looooool'    .oOOOOOOOOOOOOOOOOOOOO00OOOOOOOOOk    //
//      ,looooooool'    .lkkkkkxdoooooodxxkddxkkkkkkkkkkxdoooooooc:::::::::;,,,,,,,,,,;clol:;,,,,,,,,;;;:::;::::::::cloooooddddoooooooooooooooooooooodddddxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxdddoooooooooooooooooooooooooooooollc::::::;;;,,,,,,,,,,,,,,,,,,;coooooo;     cO0OOOOOOOOOOOOOOOOO0OOOkdl:;,''.    //
//      .looooooool'    .lkkkkkdooooddxxkkxddxkkkkkkkkxdooooooooc:::::::;;;,,,,,,,,,;looc;,,,,,,,,,;;::::::::::::cloooodddxxxxxdoooooooodddoodddxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxddooooooooooooooooooooooooooooooollc:::::;;,,,,,,,,,,,,,,,,,;coool:'     ;k0OOOOOOOOOOOO0OOOO0OOd;.           //
//      .cooooooool'    .lkkkkxooodxxkkkxxdoodkkkkkkkxdoooooooolc::c:;;;;,,,,,,,,,:looc;,,,,,,,,,;;;:::::::::::cloooddxxxxxxxxxdoooodddxxkkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxdoooddddddddooooooooooooooooooolc:;:::;;;,,,,,,,,,,;,,,,,;cooo:.     ,kOOOOOOOOOOOOO0OOO0OOOc.            //
//      .,clooooool.    .lxxxxdoooxkkkkxxxdddxkkkkkkxdoooooooooollc:,,,,,,,,,,,;codoc;,,,,,,,,,;;:::::::::::cllooodxxxxxxxxxxxxdoddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkkxdoodxxxxxxxxddooodddooooooooooool:;;;:::;;,,,,,,,,,,,,,,,;col:.     ,xOOOOOOOOOOOOOOOOOOOOd;. ..',;;:    //
//         ..';clol.    .lkxxdooodxkkkxxxxxkkkkkkkkdoooooooooooooc;,,,,,,,,,,;coxdc;,,,,,,,,,;;;::::::::::cllooddxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxdddoddxxxxxxxxxxxxxdooooooooooooc;;;::::;,,,,,,,,,,,,,,,;c:,.     'xOOOOOOOOOOOOOOOOOOOo.   .clllll    //
//             ..;:.    .lxxxdoooxkkkxdodxkkkkkkkxdooooooooooool:;,,,,,,,,,;coxdl;,,,,,,,,,;;;::::::::::clooodxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxddooddxxxxxxxxxdoooooooooooooc:;:::::;;,,,,,,,,,,,,,,;,,'.    .dOOOOOOOOOOOOOOOOOOOc.   .:lllll    //
//      ..              .lxxxdoooxkxdoodxkkkkkkkxdooooooooooooc;,,,,,,,,,,;lxxl;,,,,,,,,,;;:::::::::::clooddxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxddodddxxxxxxxddoooooooooooolc:::::::;;,,,,,,,,,,,,;;;'.    .lOOOOOOOOOOOOOOOOOOOl.   .;lllll    //
//     .;cc;'.          .cxxxdoooxxdoodxkkkkkkkxdoooooooooool:;,,,,,,,,,:ldxo:,,,,,,,,,,;:::::;;::::cloodxxxxxxxxxxxxxddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxkkkkkkkkkkkkkkkkkkkkkkxxdooddxxxxxxxdooooooooooooolc::::::;;,,,,,,,,,,,,,;,.    .lOOOOOOOOOOOOOOOOOOOo.    ,lllll    //
//      ;ooool;'.        :dxdooodxdoodkkkkkkkkxdoooooooooooc:;;;,,,,,,;cdxdl;,,,,,,,,,;:::::;;;clccloddxxxxxxxxxxxxxddodxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxdddddxxxkkkkkkkkkkkkkkkkkkkkxddddddoooddddddddxxxxkkkkkkkkkkkkkkxddoodxxxxxxdooooooooooooool:::::::;,,,,,,,,,,,,;;,'...'oOOOOOOOOOOOOOOOOOOOd.    'cllll    //
//      ,looooooc'       ,ddooooddodxkkkkkkkkxdoooooooooooc;;;;,,,,,,;lxxo:,,,,,,,,,,;:::;;,,;cooooddxxxxxxxxxxxxxddodxxkkkkkkkkkkkkkkkkkkkkkkkkkxxxddddooodxxkkkkkkkkkkkkkkkkkkkkkkkdoooooooooooooooooooodddxxkkkkkkkkkkkkkxxdoooddxxxdooooooooooooool:::::::;;,,,,,,,,,,,;;;,,,,:xO0OOOOOOOOOOOOOOOOx,    .cllll    //
//      'loooooo:.       'looooooodxkkkkkkkkxdooooooooool:;;;;,,,,,,cdxxl;,,,,,,,,,,;:::;,;:clooodxxxxxxxxxxxxxxddddxxkkkkkkkkkkkkkkkkkkkkkkkxxdddooooooooxkkkkkkkkkkkkkkkkkkkkkkkkxdooooooooooooooooooooooooodddxxxkkkkkkkkkkxddooooddxxdddooooooooooolc:::::::;;,,,,,,,,,,;;,'..,ckOOOOOOOOOOOOOOOO0k;    .:llll    //
//      'looooo:.        .:oooooodxkkkkkkkkxdooooooooool:;;;;,,,,,;lxxdc,,,,,,,,,,,,,;;;;:loooddxxxxxxkkxxxxxxxdddxkkkkkkkkkkkkkkkkkkkkkkxxddooooooooooooodxkkkkkkkkkkkkkkkxxxxxxxxdoooooooooooooooooooooooooooooooddxxkkkkkkkkkxdoooooddxxxxddooooooooolc:::::::;;,,,,,,,,,,,.   .,lkOOOOOOOOOOOOOOOOk:    .:llll    //
//      'loooo:.          ,loooodxkkkkkkkkxdooooooooooc:::;,,,,,,cdkxo:,,,,,,,,,;;;;;;;;:looddxxxxxxxxxxxxxxddddxxkkkkkkkkkkkkkkkkkkkkxdddooooooooooooooooodxxkkkkkkxxxxdddoooooddooooooooooooooooooooooooooooooooooooodxkkkkkkkkkxdooooodxxxxxdooooooooolc::::::::;,,,,,,,,,.     .:dOOOOOOOOOOOOOOOOk:    .;llll    //
//      'looo:.     .     'looodxkkkkkkkkxdooooooooooc;;;;,,,,,:odddc;,,,,,,,,;;;::::::::codxxxxxxxxxxxxxxxdodxkkkxxxxxkkkkkkkkkkkxxddooooooooooooooooooooooodxxxxxddoooooooooooooooooolllllllooooooooooooooooooooooooooodxxkkkkkkkkxdooodxxxxxxddoooooooolc:::::::;,,,,,,,,,.     .;oOOOOOO00OOOOOOOOOl.    ,llll    //
//      ,ooo:.     ',.    .cooodxkkkkkkkxdoooooooooo:,,;,,,,,;cdkdc;,,,,,,,,,;::::::::::coxxxxxxxxxxxxxxxdoodxkkkkxxxxxkkkkkkkkxxddoooooooooooooooooooooooooooooooooooooooooooooollccc::::::::::cccclllooooooooooooooooooooddxkkkkkkkxxdoodxxxxxxxdoooooooolc:::;::;;,,,,,,,,.     .,oOOOOOOOOOOOOOOOOOo.    'clll    //
//      ,oo:.     'c:.    .cooodkkkkkkkkdoooooooool:;,,,,,,,;lxkxc;,,,,,,,,;;::::::::::ldxxxxxxxxxxxxxddooodxkkkkkxxxxkkkkkkkxddoooooooooooooooooooooooooooooooooooooooooooooooolc::::::::::::::::::::::ccllooooooooooooooooodxkkkkkkkkxdoodxxxxxxxddddooooolc:::::::;;,,,,,,.     .,oOOOOOOOOOOOOOOOOOo.    'clll    //
//      .c:.     .co:.    .:oooxkkkkkkxdoooooooool:,,,,,,,,:dkkxc;,,,,,,,,;;:::::::::coxxxxxxxxxxxxxxxdoodxkkkkkkkkkkkkkkkxddooooooooooooooooollllloooooooooooooooooollllcllcccc:;;:::::::::::::::::::::::::ccloooooooooooooooodxkkkkkkkxdoodxxxxxxxxxxdooooolc:::::::;;,,,,,'.    .,dOOOOOOOOOOOOOOOOOd.    .clll    //
//      ...     'cooc.    .cooodkkkkkkdoooooooool:,,,,,,,,cxkkxc;,,,,,,,,;::::::::::coxxxxxxxxxxxxxkkkxdxxkkkkkkkkkkkkkxxdoooooooooooooooollcccclooooooooollllcc::cc:::::;:::;;;;;;::::::::::;:::;:::::::::::::ccloooooooooooooodkkkkkkkkkxdodxxxxxxxxxxdooooooc:::::::;;,,,,'.     ;kOOOOOOOOOOOOOOOOOd.    .::;,    //
//             'loooo:.. .;loooxkkkkkxdooooooool:,,,,,,,;lxkkxc,,,,,,,,,;:::::::::::cdxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkxdoooooooooooooooolc:::::cccloooolcc::::::::::;;::::::::::::;::;;:::::::::::;::::::::::::::::cclooooooooooodxkkkkkkkkkkdodxxxxxxxxxxdooooolc:::::::;;,,,,.     :O0OOOOOOOOOOOO00OOd'     .       //
//            ,loooooolccloooooxkkkkxdooooooool:,,,,,,,,lxkkdc,,,,,,,,,;::::::::::clodxxxxxxxxxkkkkkkkkkkkkkkkkkkkkxddoooooooooooooolc:;,;;::::::cloolc:::::::::::;;;;;:::::;;;;;;;,,,,;;;;;;;:::::::::::::::::::::::clooooooooodxkkkkkkkkkkkdodxxxxxxxxxxdooooolc::::::::;,,,.     ;kOOO0OOOOOOOOOOOOOx'             //
//           ,looooooooolodddddxkkkxdooooooool:,,,,,,,;lollc;,,,,,,,,;;:::::::::clodxkkxxxxxxxxkkkkkkkkkkkkkkkkkxxdoooooooooooooolc:;;;;;;::::cllolc:;,;;:::::::;;,,,,,;;;;,,,,,,,,,,,,,,,,,,,,;;;;;::::::::::::::::::::cloooooodxkkkkkkkkkkkkxoodddddxxkxxdooooolc::::::::;,,'.    .lkxoloxOO00OOOOOOOk;       .'    //
//          'looooooooc,..,oxxkkkkkxooooooooo:;,,,,,,,lo:,,,,,,,,,,,;;:;::::::cloodxkxdddxxxxkkkkkkkkkkkkkkkkkxdoooooooooooooolc:;;;;::::::cllolc:;,,,,,;;::;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;::::::::::::::::clooooodxxkkkkkkkkkkkkxooooodxxxxxxdooooolc:::::;::;;,.     .,.   .;dO0OOOOOOOOd,. ..:okO    //
//          'loooooool,    ,dkkkkkxdooooooooc;;,,,,,,co:,,,,,,,,,,,;;:::::::clodxxkkxdoodxkkkkkkkkkxkkkkkkkkxddoooooooooooolc:;;;:::::::cllolc:;,,,,,,,,,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:::::::::::::::looooooodxkkkkkkkkkkkkxdoooodxxxxxxdoooool:::::::::;;,.            .:dOOOOOOOOOkdodkOOOO    //
//          .:oooooool,    .okkkkkdooooooool;;;,,,,,coc,,,,,,,,,,,;:::::::cloddxkkxdoodxkkkkkkkkkkkkkkkkkkxxdoooooooooooolc::;:::::::cllool:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;:::::::::::::loooooooodxxkkkkkkkkkkkxdoooodxxxxxxdoooool:::::::::;;'              .,okOOOOO0OOO0OOOOO    //
//           ;oooooooo,    .lkkkkxdoooooool:;;,,,,,:ool;,,,,,,,,,;:::::::loodxxkkxddddxkkkkkkkkkkkkkkkkkkxdooooooooooollc:;::::::::cloolc;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;::::::::::cooooooooooodxkkkkkkkkkkkxdooodxxxxxxxdoooool::::::::::,.     .cdl.     .;xOOOOOOOOOOOOOO    //
//    .      ;dooooooo:.    :xkkkxooooooooc:;;,,,,;lodl,,,,,,,,,;::::::cloddxxkkxdxkkkkkkkkkkkkkkkkkkkkxdooooooooolccc:;::::::::cloolc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;::::::::loooooooooooodxkkkkkkkkkkkxxdoodxxxxxxdooooolc:::::::::;.    .oKKKOl.    .oOOOOOOOOOOOOOO    //
//    ;      'odooooooc.    'dkkxdoooooool:;;,,,,;clol;,,,,,,,,;;:::::cooddxxkkxodxkkkkkkkkkkkkkkkkkkxdoooooooollc::::::::::::clolc:;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;:;:;:cloooooooooooodxxkkkkkkkkkkkxxddxxxxxxxdooooolc::::::::;.    .xKKKKd.    ,xOOOOOOOOOOOOOO    //
//    c.      'cooooool,    .lkkxooooooolc:;,,,,,:c:;;,,,,,,,,;;::::clooddxxkxdddxkkkkkkkkkkkkkkkkkxxdooooooolc::::::::::::clllc:;,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,;;;::::cloooooooooooodxkkkkkkkkkkkkxxxxxxxxxxdoooool::::;;;:;.    .dKKX0c    .lOOOOOOOOOOOOOOO    //
//    o.        ':loooo:.    ;xxdoooooll:::;,,,,:c;,,,,,,,,,,,;::::cloodddxkkxddxkkkkkkkkkkkkkkkkkxdooooooool:::::::::::ccclc:;,,,,,,,,,,,,,,,,,,,,,,;;;::::::::::::::::::::::::::::::::::::;:;;;;;;;;;;;;;;;;;;,,,,,,;;:::::clooooooooooodxkkkkkkkkkkkkkkxxxxxxxxdoooooc:::::::;.     c0KK0:    .dOOOOOOOOOO0OOOO    //
//    x,          .;looc.    .oxdooolc:::::;,,,;c:,,,,,,,,,,,;::::clooddddkkxddxkkkkkkkkkkkkkkkkxxdooooooolc:::::::::::cc;;;,,,,,,,,,,,,,,,,,,,,,,;;:::::::::::::::::::::::::::::::::::::::::::::::::::::;;:::::;;,,,,,,;::::::cloooooooooodxkkkkkkkkkkkkkkxxxxxxxxdooool:;:::::;,.   .oKKkc.    .dOOOOOOOOOOOOOOO    //
//    kc            .;ll,    .cdooool:::::;;,,;cc,,,,,,,,,,,;;::::looddddkkxddxkkkkkkkkkkkkkkkkxdooooooool::::::::;;:cl:,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;,,,,,,;::::;:cclllooooooodxxkkkkkkkkkkkkxxxxxxxxxdooolc::::::::;'.'ckx:.     .lkOOOO00OOO00OOOO    //
//    Oo.    .'.      .''     ;oooooolc:::;;;;cl;,,,,,,,,,,;;::;:cooddddxkxdxkkkkkkkkkkkkkkkkxddooooooolc:;:::::::;,;:;,,,,,,,,,,,,,,,,,,,,,;;;;;;,;::::::ccccccclllooooolllllcccc:::::::::::::::::::::::::::::;:;;;;;,,,;;::;;::::::cclooooooxkkkkkkkkkkkkkxxxxxxxxdoool::::::::::::;c:.     .;dOOOOOOOOOOOOOOOOO    //
//    Ok;    .od:.            'looooooc:;;::::c:,,,,,,,,,,,;;;;;cooodddxkxxxkkkkkkkkkkkkkkkkxdoooooooolc::::::::;;,,,,,,,,,,,,,,,,,,,,,,,;;;::::ccclooolooooooooooooooooooooooooooolllc:::::::::::::::::::::;::::;;;;;;,,,;;;:;::::::::cloooooddxxkkkkkkkkkkxxxxxxxxxdoolc::::::::::;,.     .:dOOOOOOOOOOOOOOOOOOO    //
//    OOxc,';lxkkdc'.         .cooooooc,,;::::;,,,,,,,,,,,;::;;cooodddxkxxxkkkkkkkkkxxkkxxxdoooooooooc:::::::::;;,,,,,,,,,,,,,,,,,,,,,,;;:::clllooooooooooodddoooooooooooooooooooooooooollcc:::::::::::::;;::::::::;;;;;;,,;;:;;;:::::::cloooooodxxxkkkkkkkkxxxxxxxxxdoool:::::::::;.      .lkOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOkOOkkkkkxo:..      .;oooool:,,;:::;,,,,,,,,,,,;:::;:looddddxkxxkkkkkkkkxxxkxxdddoooooooolc::::::;:;;,,,,,,,,,,,,,,,,,,,,,,;;:::cloooooooooodddxxxkkxdoooooooooooooooooooooooooooollc:::::::::::::::::::::;;,;;;,,;;::::::::::::looooodxxxkkkkkkxxxxxxxxxxxxdoool::::::::,.    'cdOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOkkkkkkkkx:       ,looooc;,;:::;;,,,,,,,,,,;;::;:looodddxkkkkkkkkkxxxxxkxdddooooooooolc::::::::;;,,,,,,,,,,,,,,,,,,,,,;;:::clooooooooodddxkkkkkkkkxxxxxxxxxxdddddooooooooooooooooollc::::cc:::::::::::::;;;;;;,,,;;:::::::::::cooooodxxxkkkkkxxxkxxxxxxxxdoooolc:::::;'.   .lOOOOOOOOOOO0OOOOOOOOOOOO    //
//    OOOOkxxkkkkkkkkxc.       .coool:,,;:::;;,,,,,,,,,,;::;;cooooddxkkkkkkkkxxxxxxkxdooooooooooolc::::::::;,,,,,,,,,,,,,,,,,,,,,,;;::clooooooooddxxkkkkkkkkkkkkkkkkkkkkkkkkkkxxdoodddoooooooooooolc:clolc:::::::;:::::;;;;;,,,;;;::::::::::clooodxxxxkkkkxxxkkxxxxxxxdoooool:;;:;;,..  .lOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOo,..,okkkkkd;.        .:oooc;,;;:::;,,,,,,,,,,;::;;:looooodkkkkkkkkxxxxxxkxdoooooooooool:::::::::;,,,,,,,,,,,,,,,;,,,,;;;;::cloooooooddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdodxxxdddooooooooooooooool:::::::::::::;;;;;,,,,;;::::::::::clooodxxkkkkkkkkkkkxxxxxxdoooooo:,,,,,,,''',ckOOOOOOOOOOOOOOOOOOO0OOO    //
//    OOk;    ;xkkxo'           ,ool;,;;::::;,,,,,,,,,;;::;:looooodxkkkkkkkxxxxxxxxdoooooooooool:::::::::;,,,,,,,,,,,,,,;;;,,;;:::::looooooodxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxdoddxxxxxdoooooooooooooool:::::;::::::;;;;,,,,,,;;::::::::::looodxkkkkkkkkkkkxxxxxdoooooooc;,,,,,,,''';dOOO00OOOOOOOOOOOOOOOOOO    //
//    OOk;    'dko;.     ',.    'ol:,,;::::;;,,,,,,,,,;:::;cooooooxkkkkkkkxxxxxxkxooooooooooool::::::::;;,,,,,,,,,,,,,,;;,;;::::::cloooooddxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxdooddxxkxxddooooooooooooolc::::::::::::;,,,,,,,,;;::::::::;:clooxkkkkkkkkkkkkxdddooooooool;,,,,,'..  .cOOO00O0OOOOOOOOOOOOOOOO    //
//    olc'    .;;.     .;do.    .::,,;;::::;,,,,,,,,,;:::;:looooodkkkkkkkxxxkkkkxdooooooooooolc:::::::;;,,,,,,,,,,,,,,;,,;cc:::::coooooodxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxdoooddxxxxdooooooooooooolc:::::::::::;,,,,,,,,,;;:::::::::clodkkkkkkkkkkkk                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract INS is ERC721Creator {
    constructor() ERC721Creator("Inside", "INS") {}
}
