logger:
  env: development
  level: debug

storage:
  enabled: true
  contractsPath: /mnt/{disc}/downloader/
  databasePath: /mnt/{disc}/downloader/db

nodes:
  - group: "ethereum"
    type: "mainnet"
    networkId: 1
    endpoint: "ws://localhost:8545"
    concurrentClients: 10

nats:
  addr: "localhost:4222"

db:
  flattenWorkers: 10

cache:
  addr: "localhost:6739"
  password: ""
  db: 0
  maxRetries: 3
  minRetryBackoff: 8ms
  maxRetryBackoff: 512ms

etherscan:
  provider: "etherscan"
  endpoint: "https://api.etherscan.io/api"
  keys:
    - "XXXXX"

syncer:
  subscribers:
    - type: head
      enabled: true
    - type: archive
      enabled: true
      startBlockNumber: 0
      endBlockNumber: 19312364
