logger:
  env: development
  level: debug

networks:
  - name: "ethereum"
    networkId: 1
    canonicalName: "Ethereum"
    symbol: "ETH"
    website: "https://ethereum.org/"
    suspended: false
    maintenance: false
  - name: "binance"
    networkId: 56
    canonicalName: "Binance Smart Chain"
    symbol: "BNB"
    website: "https://www.bnbchain.org/en/bnb-smart-chain"
    suspended: true
    maintenance: false

storage:
  enabled: true
  contractsPath: /mnt/{disc}/inspector/
  databasePath: /mnt/{disc}/inspector/db

nodes:
  - group: "ethereum"
    type: "mainnet"
    networkId: 1
    endpoint: "ws://localhost:8545"
    concurrentClients: 10

rpc:
  enabled: true
  addr: "localhost:6877"

nats:
  enabled: true
  addr: "localhost:4222"

ipfs:
  enabled: false
  addr: ""

db:
  dialect: "sqlite3"
  datasource: sqlite/inspector.db
  migrationDir: migrations/sqlite3

cache:
  addr: "localhost:6379"
  password: ""
  db: 0
  maxRetries: 3
  minRetryBackoff: 8ms
  maxRetryBackoff: 512ms

etherscan:
  provider: "etherscan"
  endpoint: "https://api.etherscan.io/api"
  keys:
    - "XXXXX"

syncer:
  subscribers:
    - type: unpacker
      enabled: true
      subjectName: "contracts:unpack"
    - type: head
      enabled: true
      resumption: false
      network: "ethereum"
    - type: archive
      enabled: true
      resumption: true
      network: "ethereum"
      endBlockNumber: 19312364

unpacker:
  otsEnabled: false

graphql:
  addr: 0.0.0.0:8084
  transports:
    - http
    - ws
  cache:
    adapter: redis
    queryCacheDuration: 24h
  cors:
    debug: true
    maxAge: 120
    allowCredentials: true
    allowedOrigins:
      - "*"
    allowedMethods:
      - HEAD
      - GET
      - POST
      - PUT

pprof:
  enabled: true
  addr: "localhost:7599"