
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: God, please let me die again
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    Tang dynasty, zhenguan twelve winter.                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    Hundreds of thousands of go games, such as the twelfth street vegetable beds.                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    Remote recognition slightly into the fire, a star five doors west.                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    The moon and stars without light, the north wind is rustling, the snow like goose feather falls rustling down the ridge of the streets and lanes, stepping on the thick snow, a line of torches from each lane just opened by the lane door out, gathered rosefinch Street, vast and mighty to Chengtianmen, ready for the court.    //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    As early as the hour will come, but liang Guogong, Shang Shu left servant shot Fang Xuanling's mansion is noisy, disorderly.                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
//    Fang Xuanling, who will soon be 60 years old, stood in court clothes with her hands in her hands, looking up at the snow-covered roof with a sad face.                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract GPLM is ERC721Creator {
    constructor() ERC721Creator("God, please let me die again", "GPLM") {}
}
