
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Insects awaken
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//    February 2, dragon head.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//    Town in the dusk, secluded place named bottle mud lane, a thin boy alone, as he according to custom, one holding a candle, a handheld peach sticks, shining on the place such as beams, walls, wooden bed, with peach branches tapping, hoping to drive snake, centipede, mouth murmured, is traditionally handed down the town's adage: February 2, candle beam, peach hit the wall, human snake insects nowhere to hide.                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//    The boy's surname is Chen, his name is Ping an, his parents died young. The town is very famous for its porcelain. Since the founding of the Dynasty, it has assumed the responsibility of "serving the imperial decree and supervising the burning and offering of mausoleum sacrificial vessels". There are imperial officials stationed here all year round to supervise the official kiln affairs. Helpless, have long served as porcelain potter, can only do some chores at first life, with a bad temper halfway teacher, hard boil a few years, just wondering to porcelain doorways, impermanence, as a result, the town suddenly lost kilns made do this amulet, dozens of surrounding the town if the wolong kiln, are all government ordered to shut off overnight.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LAN is ERC721Creator {
    constructor() ERC721Creator("Insects awaken", "LAN") {}
}
