
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Strange Lives ❤️
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    xxxdddooodooodddddxddddooooooooooolooooodddodoooooooolllloooooddddxxxxkkkkkxxdxxxxddddddxddddodddodddooddddddoooooooddooodddddddddddddddoddddddddddddoooooooooooodl.  :xxxkkkO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXKKKKKKKKKKKKXXXKKXXXXXKKXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKXXXXXXXXXXXXXXXXXX    //
//    xddddoooooooddddxddddooooooooloooloooooooooooooooooooolllllloddddxxxxkkkkxxxxxxdddddddxddddooddddddooddddddooodoooooooodddddddddddddddooddddddddddddooooooooooooodl.  :xxkkkOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXKKKKKKKKKKKKKKKKKXXKKKXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXXKKKXXXXKXXXXXXXXXXXXXXXX    //
//    dddoodooooddddddddddodooooooooollooooooooooooooooollollllllooodddxxkkkkkxxxxxxddddddxddxdoodddoddooddddddooodoooooooooddddddddddddddddodddooodddooooooooooooooooodl.  :xkkkkO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXKKKKKKKKKKKKKKKKXXKKKKXXXXXXXXXXXXXXXKKXXXXKXXXXXXXKXXXKKXXXXXXXXXXXXXXXXXXXXXXX    //
//    dooddooodddddddddooooooooollolllooloolloolloooollooollllloooodddxxxkkkxxxxddxdddddddddddodddddddoddddddooodooooooooooddddodddddddddoodddooooodooooooolloooooooooodc.  :kkkkO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKXXXKXXXXXKKKKKKKKKKKKKKKXXKKKXXXXXXXXXXXXXXXKXXXXKKKKXXXXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXX    //
//    oooooooddddddddoooooloooolllllllllllllllllloolloooollolooooodddxxxkkxxxdddddddddddddddodddddooooddddddooddooooooooodddddddddddddddooddooooooooooooooooooooooooooodc.  :kkkOO000KKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKXXXKKKKKKKKKKKKKKKKKXKKKXXXKXXXXXXXXXKKKKXXKKKKXXXXKKXXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    ooooododddoooooooooooooollllllllllllllllllllllooollooooooooddxxxxxxddddddddddddddddddodddddoodddddddooodooooooodooddddddddddddxdooddoooooooooooooollooooooooooooddc. .ckkkO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKXKKKKKKKKKKKKKKKKKXXKKKXXXXXXXXXXXXKKKKXXXKKKKKXXXKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXX    //
//    oooooooooooooooooooooollloolllllllllllllllllllolllooooooooddddxxdddddddddoddddddoddooddddooddddddddodddooooooddodddodddddddddddoooooooooooolooooollooooooooooooddd:  .lkkkO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXKKKKKKKKKKKKXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXX    //
//    oodooooooooooooooooollloolllllllllllllllllllllllloooooooddddddddddooddoododdddoodoooddddodddddddddddddddoooddooddddddodddddxdoodooooloooolloooollloooooooooododddd,  .okkO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKXXXXXKKXXXXXXXKKKKKKKKKKKKKKKKKXXXXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    odooooooooooooooooolloolllllllllllllllllllllllllloooooodddddddddooooooooodddooodooddoddoddddddddddxddddoodddoddddddoodddddxdoodoooolooolllooollllooooooooooddddddo.  'xkO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKXXXXXXXXXKKKKKKKKKXKKKKKKXXXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    ooooooooooooooooolllolllllllllllllllllllllllllloooodddxxxxdddddoodooooodddooddooodoodoodddddddddxxdxdddddddddddddoodddddxdoodooooolooolloooollllloooooooooddodddd:.  ckOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKXXKKKXXXXXXKXXXKKKKKKKKKKKKKKXKKKXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXKXXXK    //
//    ooooooooooooooolllllllllllllllllllllllllllllllodddxxxkxxxxdxdl,''',;;:clooddooooooddodddddddddxxxxxdddxxddddddddooddddddddoooooolooolllooollllllooooooooodddddddd'  .dOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKXXKKKKKKKKKKXKKKKKXKKKXXXXXXXXXXXXXXXXXKXXXXXKKXKKKKXXKKK    //
//    ooooooolooooollllllllllllllllllllllllllllllloodxxkkOOkkkkkxddc,,,..     ..,;cloooooodddddxddxxxxxxddxxxddxddxxdodddddddddoooooolooolllooollllllllooooooodddddddxc.  :kOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKXKKKKKKKKKKKKKKXXXKXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKXXX    //
//    oooooooooooolllllllllllllllllllllllllllllllodxxkOO000OOOOkxkkxxxxdol:;,'.    .,coooddoddxddxxdxxdddxxddxddxxdddxddddddddoooooloooolloooollllllllooooooddddddddxd,  .oOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKXXKXKKKXKXXKKKXXXXKXXXXXXXXXXXXXXXXXXXKKKXKKKKKKXXXXX    //
//    ooooooooooooolllllllllllllllllllllllllllloodxkkO00KKKKKK0O0OOOkxxxxxddddoc;'.   .:oooddddxxdddddddddddddxxxddxxdxxdddddoooooloooolloolollllllllooooodddddddddxxl.  ;kO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKXXKKXXKKKXXKKKKXXXXXXXXXXXXXXXXXXXXXXXXKKXXXKKKKXXXXXXX    //
//    oolooooooooolollollllllllllllllllllllllloodxkOO0KKKxlldxddddoooodxkkkxxxdoool;.   .:oooddddddddddddddddxxdddxxdxxdddddoooooloooolloooolllolllloooooddddddddddxx;  .oOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKXXKKXXKKKKKXKKKXXKKXKXXXXXXXXXXXXXXXXXKKXXXKXXKKXXXXXXXX    //
//    looooooooooooooolllllllllllllllllllllllllodxkO0KXO:.            ..':lxkxxddoool;.   .,coddddoodddddodddddddxdxxddxddddooollooololooollllolllooooooddddddddddxxo.  ,k000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKKKKKKKKKKKKXKKKKKXXXXXXXXXXXXXXXXXKKXXKKKKKKXXXXKXXKXX    //
//    ooooooooooooooollllllllooollllllllllllllodxxkO0XO;  ;xxdoollllc;'.   .,:oddoooool:.    'coooodddoooodddoodddddddxddddooolooollooooollllllllooooooddddddddddxxd,  .oO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKXKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXKKKXXXXXKKKXXXKKXXXXXXX    //
//    oooooooooooooolloolllloolllollollllllllooddxk0KKc  .OWWWWWWWWWNNXOo;.    ':looooollc,.   ,loddooooodoooodddddddxdodoooolooolooooolllllllllooooooodddddddddxxx:   :O000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKXXXXXKKKXXXKXXXKKKKKKXXXKXXXXKXXXXK    //
//    ooooooooooooollollllooolooooooollolllllloodkO0Kx.  cNWWWWWWWWWWNNNNKOd;.   .'coooooooc'   .:oooooooooodddddoddddddoooolooolooooolloollllloooodoodddddddddxxxc.  ;k000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKXXXXXKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKKXKKXXXKKXXXXXXKKXXXXXXXXXXX    //
//    oooooooooooooloollloooooooooooooolllllllodxkO00c  .xWWWWWWWWWWWWNNNXXK0kc'    .coooooooc.   'loooooooodddoodddodoooollooloooooolloolllllooooooddddddddxxxxxl.  'x000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKXXXKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKXXXXXXXXXXXXKXXXXXXX    //
//    ooooooooooooooollloolooooooooooollllllloodxxk0O,  .OWWWWMMWWWWWWNNNNXKK00Oo'   .;oooooodl'   .cooooooodooodddoooooollooloooooolooollllloooooodddddddxxdxxxl.  'dO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKXXXXXXXXXXXXXXXXXXXXXX    //
//    oooodoooooooolloooooooooooooooooollllllooddxk0d.  ;XWWWMWWWWWWWWWWNXXXXKK0Okc.   .lddddool;   .:oooooooodddoooooooloooloooooolooolllloooooooddddddddxxxxxo.  .dO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKXXXXXXKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKXXXXXXXXXXXXXXXXXX    //
//    oodddoooooolloooooooooddoddooooolllllllloddxkOl   cNWWWWWWWWWWWWWNNNNXXKK0KK0d'   .cxxdoodo;.  .;ooooooddooooooooloollooooooooooooloooooddddddddddddxxxxo.  .dOO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKXXKXXKKXXKKKKKKKKKKKXKKKKKKKXKKKKKKKKKKKKKKKKKKXKXXXXKXXXXXXXXXXXXXXXXXXXX    //
//    ddddooooolllooloooooododddooooollllllllloodxkk;   oWWWWWWWWWWWWWWNWNNNXXXXXKK0k;    ;odxddoo:.   ;oooodoooooooollooloooodooodooooooooooddddddddddddxxxxo.  .d0O0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKXXXXXXKXXXKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKXXXXXXXXXXXXXXXXXXXX    //
//    xdoooooolloooloooooddddddodooolllllllllloodxOk,  .kWWWWWWWWWWWWWWWNNNXXNNXXXK0K0l.   .lxdooooc.   ;ooooooooooollooloooodooodoooooooodddddddddddddxxxxl;.  'dOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKXXXXKKKKXXKKKKKKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKXXXXXXXXXXXXXXX    //
//    ddddodoloooolooooddddxdoddooooolllllllllodxx0d.  .OWWWWWWWWWWWWWWNNNNNNNNNXXXXXKKd.   .:ddodooc.  .:oooooooooloooloooodooodooooooooddddddxddddddxxxx:.   ,xOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKXXXXXKKXXKKKKKKKKKKKKKKKKKKXXKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKXXKKXXXXXXXXXXXXXXX    //
//    dddddooodooooooodddddddddddoooolllllllloodxO0o.  '0WWWWMWWWWWWWWWNWNNNNNNNNNXXXXXKk'   .cxddooo;   'ooooooolloooloooodooddooooooodddddddxddddddxxxx;   .:kOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKXXXXXXXXXXKKKXXKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKXXKXXXXXXXXXXXXXXXX    //
//    ddddooddddooooddddxddddddddddooolllllllodxkO0l   ,KWWWMWWWWWWWWWWWWWWNNNNNNNNNNXXKXx.   'ddddooc.  .:ooooolloooooooddooddooooooodddddddxddddxxxxxd;  .'ckO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXKKKXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXKKKKKKKXXKKXXXXXXXXXXXXXXXX    //
//    dddddxdddddddddxxxdddddxxddxdooollllllodxkOO0l   ,KWWMWWWWWMWWWWWWWWNNWNNNNNNNNXXXX0:    :xddool'   :doooloddoooooddooddoooooooddddxxxxddxdxxxxxd,  .lkOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKXXXXXXXXXXXXKKKKKKKKKKKKKKKXKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKKKKXKKKKXXKKKXXXXXXXXXXXXX    //
//    ddddxxdddxxxxxxxxxxxdxxddxxddooollloooodxkkOKl   '0WWWMWWWMWWWWWWWWNWWNNNWWNNNNNNXKKd.   ,dddooo,   :oooloddoodooddooddoooooodddddxxxxxdxxxxxxxd,  .oOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKXXXXXXXXXXXXXKXXXKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXKKKKKXXKKXXXKKXXXXXXXXXXXXXXX    //
//    ddxxddddxxxxxkkxxxxxxxxxxxxddooollooloodxxO0Ko.  .kWWWWWWMWWWWWWWWWWWNNWWWNNNNNWNXXXk'   .lxdddd,  .:oooodooododddooddooooooddddxxxxxxxxxxxxxxo.  'dOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKXXKXXXXXXXXKXXXXXXXXXXXXXXXKKXKKKXKKKKKKKKKKKKKKKKKKXKKKKXXXXXXKKKKXXKKKXXKKXXXKXXXXXXXXXXXXX    //
//    dxxddddxxxxxkxxkkxxxxxxxxxddooooloolloodxxkO0k.   lNWWWWWWWWWWWWWWWWNWWWWWNNWWWNNNXXK;    ckxxdo,  .looodooooodddooddooooodddddxddxxdxxxxxxxxl.  ;xOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXXXKKKKKKKKKKKKKKKKKKKXXKKKXXXXKKKXXXXKKKKKKKKKKKXXXKXXXXXXXXXXX    //
//    xxddddxxxxkkxxkkxxxxxxxxxddoooooolllloooddxkOO;   ,KWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXc    ;kxddd;  ,ooodooooddddoddooooooddddddddxxddxxxxxxx:. .lkOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKXKKKKKKKKKKKKKKXXKKKXXKKXKKKXXXKKKKKXKKKKKXXXKKXXXXXXXXXXXX    //
//    dddddxxxxkkkkkkkxxxxxxxxdddoooooolloolooodxxk0l   .dWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXo    ,kxxxx; .loddoooodddooodooooooddodxddxxxddxxxxxxo'  'dOOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXK0OkkxxxkO0KXXXXXXXKXXXXXXXXXXXXXXXXXXXXKXKKKKKKKKKKKKKKKKKKKXXXXXKKKKKXXKKKXKKKKKKXXXKKXXXXXXXKXXXXXX    //
//    ddddxxxxkkkkkkkkxxxxxxxdddooooooollollloodddkOx'   ,0WWWWWWWWWWWWWWWWWWWWWWNK0XNWNNNNo    ;kkkxxo:ldddoooodddooooooooooddodxdddxxdxxxxxxdc. .:kOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXX0kdl:;'..........',:codxO0KXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKXXXXXXKKKXXKKKKXKKKXKKXXXKKXXXXXXKKKXXXXXXX    //
//    dddxxxkkkkkkkkkkxkxxxxddddoodoooololllooooddxkOl.   lNWWWWWWWWWWWWWWWWWWWXd,..'oXNNNXc    :OOkxxddddoooooddddooooooooooodddddxxdxxxxxxxo'  'oOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKOdl;'...,:cloddxxxdol:;'..  ..':lk0XXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKXXXXXKKKXXXKKKKXXXKKKXXXKKXXXXXXKKKXXXXXKKXX    //
//    ddddxxkkkkkkkkkkkxxkxdxxdddddooooollloooooodxxkk;   .xNWWWWWWWWWWWWWWWWWWo     .kWNNK;   .l0Okxxxddooooodddooooooooooooddddddxxxxxxxxxc. .:xOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXX0ko:'...;ldOKXXXXXXXXXXXXXXXK0Oxdlc,.  .;lkKXXXXXXXXXXKKKKKKKKKKKKKKKKXXXXXXKKKKKXXKKKKKKKKKKXXKKXXXXXXKKXXXXXKKKXXXX    //
//    dddxxxkkkkkkkkkkkxkxxxxxxxddddooollloolooodddxkOd.   .dXWWWWWWWWWWWWWWWWWd.   .lXWNWk.   'kKOkxxxddoooddddoooooooooododddddxxxxxxxxxd;  .oOOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKko;...,cdkKXXXXXXXXXXXXXXXXXXXXXXXXNNNX0dc,.  'cd0XXXXKKKKKKKKKKKKKKKKKKXXXXKXKKKXXXKKKKKKKKKKXXKKXXKXXXKKXXXXXKKKKKXXXX    //
//    ddxxxkkkkkkkkkkkkxxxxxxxxxxxddooollllloooddddkkkOd.    ;kNWWWWWWWWWWWWWWWXxc:lONWWWNc    c0Okkxxdddooddddoooooooooodddddddxxxxxxxxxo'  'dOOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXK0xc'.':lx0XXXXXNXKOxdolc:;;;,,'''''',,;cloxO0XX0d:'  .l0XXXXKKKKKKKKKKXKKKXXXKKKKKKXXXKKKKKKKKKKKKKXXXXXXXXXKXXXKKKKKKXKKKKX    //
//    dxxxkkkkkkkkkkkkxxxxxxxxxxxdddoooollllooddddxxxkxxxc.   .:kXWWWWWWWWWWWWWWWWWWWWWWW0'   .dOkkxxxddooddoddooooooooooddddddxxxxxxxkxc.  ;xOOOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKX0d:'.,lxKXXXXXNXOdc;..                        ..,:lxO0kdco0XXXXXXKKKKKKKKKKKXXKKKKKKKXXKKKKKKKKKKKKKKXXKXXXXKXXXXKKKKKKKKKKKKKK    //
//    xxxkkkkOkkOkkkkxxxxxxxxxxxxxdddooolllloodddxddxxxkOOx;     'ckXWWWWWWWWNWWWWWWWWWWNo    ;kOkkxxddooddoddooooooooododddddxxxxxxxkd:. .ckOOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKXKx:'.;oOXXXXNNX0xc,.   ..,:lodxkkOO000000OOkxdl:,..    ..;lx0XXXXXXXXKKKKKKKKXXXXKKXKKKXXKKKKKKKKKKKKKXXKKKXXKXXXXKKXKKKKKKKKKKKKX    //
//    xxxxkkOkkOOkkxxkxxxxxxxxxxxdddooolllloodddddddddxxxkOOd:.     .;loxk000XNNNWWWWWWWK,   'xOkkxxddooddodoooooooooodddddddxxxxxxxxo,  .oOOOO0000KKKKKKKKKKKKKKKKKKKKKKKKKXKOl,.,oOXXXNNX0xl,.   .,lx0XWMMMMMMMMMMWWWWWWWWWWWWNX0kdl;'.   .;okKXXXXXXXXXXXXXXXXKKXXKKKKKKKKKKKKKKKKKXXKKXKXXXXKKXKKKXKKKKKKKKKXX    //
//    xxxkkkkkOOkkxxkxxxxxxxxxxxxddoooollloooodddddoodddxkkO00Od:.        .....'';clodoc,   ,xOkxxddoooddodoooooooooododddddxxxxxxxxl.  ;xOOOO000KKKKKKKKKKKKKKKKKKKKKKKKKXKx:.'lkXXXNNXOo;.   .'cxKNMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMWNKOdl,  .,dKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKXXXXXXXKKXXXKKXKKKXKKKKKKKKKXXXX    //
//    xxkkOOOOOkkxxkxxxxxxxxxxxxddoooollloooodddddoddooddxkkOOKKK0dc;'..                    :kkxdddoooooooolooooooooodddddxxxxxxxkx:. .ckOOOO000KKKKKKKKKKKKKKKKKKKKKKKKX0o,.;dKNNNNN0o,.   'cd0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWo   'xKXXXXXXXXXXXXXXXKXKKKKKKKKKKKKKKXXXXXKXXXXXKKKKKKXKKKKKKKKKXXXXX    //
//    xkkkkOOOkkxxxxxxxxxxxxxxxdooooooloooooddddoooooooddxxxkOO0KKKXXKOkddollcc:;'...  .';;cdxddddoooooooolooooooooddddddxxxxxxxkd,  .lkOOOO000KKKKKKKKKKKKKKKKKKKKKKKKOl''ckXNNNN0o;.  .,oONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWM0'   oNNXXXXXXXXXXXXXXXKKKKKKKKKKKKKXKXXXXKKXXXKKKKKKKKKKKKKKKKKKKXXXXX    //
//    kkkkOOkkkxxxxdxxxxxxxxxxdodoooolooooodddoooooooooooddxxkOOO0000000000KKKKK000kxxdxOkkxxdoddoooooooolooooooooddddddxxxxxxkxc.  ;dOOOO0000KKKKKKKKKKKKKKKKKKKKKKKOc',o0NNNNXx;.  .,o0NMMMMMMWOc;cdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWd.  '0NNXXXXXXXXXXXXXXXKKKKKKKKKKKKKXXXKKKXXXKKKKKKKKKKKKXKKKKKKXXXXXXX    //
//    kkkkkkkkxxxddxxxxxxxxxxdddooooooooooddddooooooooooooddxxxxkkOOOOkOOOOOOOOO00OOOOkkxxxddoddooooooooloolooooodddddxxxxxxxko,  .lkOOOO0000KKKKKKKKKKKKKKKKKKKKKXKo',xXNNNNOl.   ,o0WMMMMMMMMXl.    ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   lNNNNXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKXXXXKKKXKKKXKKKKKKKKKKXXXXXXXXX    //
//    kkkkkkxxxxdddxxxxxxxxddddooooooddooddddoooolooooooododddddxxxkxdxkkkkkkkkOOkkOkxxxdddooddooooooolllolloooodddddxxxxxxxxc.  ;dkOOOO0000KKKKKKKKKKKKKKKKKKKKKXKo;dXNNWNO:.  .cONMMMMMMMMMMWo      .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:   :KNNNXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKXXXKXKKKXKKKKKKKKKKKKXXXXXXXXXXX    //
//    kkkxxxxxdddddddxxxxxddddooooodooodddddoodoloooooooooooooodddddodxxxxxxxxkkxkkxxxddddooddoooooollllolloooodddddxxxxxxxo'  .okOOOOO000KKKKKKKKKKKKKKKKKKKKKKXXXKKNNNNOc.  ,xXMMMMMMMMMMMMMWl      '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  'OWNNNXXXXXXXXXXXXXXXKKKKKKXKKKKKKKKXXKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXX    //
//    kkxxxxxdddddddxxxxdddddooooodooodddddooddooooooooooooooooooooodddddddddxxdxxddddddooloooollolllllllloooodddddxxdxxxxc. .:xOOOOO0000KKKKKKKKKKKKKKKKKKKKKKXXXXNNNNO:.  ;kNMMMMMMMMMMMMMMMM0;    'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWx.  .dNNNNXXXXXXXXXXXXXXX                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STL is ERC721Creator {
    constructor() ERC721Creator(unicode"Strange Lives ❤️", "STL") {}
}
