
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: BORN FROM NOTHING
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//    BBBBBBBBBBBBBBBBB        OOOOOOOOO     RRRRRRRRRRRRRRRRR   NNNNNNNN        NNNNNNNN     FFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRRRRRRRRR        OOOOOOOOO     MMMMMMMM               MMMMMMMM     NNNNNNNN        NNNNNNNN     OOOOOOOOO     TTTTTTTTTTTTTTTTTTTTTTTHHHHHHHHH     HHHHHHHHHIIIIIIIIIINNNNNNNN        NNNNNNNN        GGGGGGGGGGGGG    //
//    B::::::::::::::::B     OO:::::::::OO   R::::::::::::::::R  N:::::::N       N::::::N     F::::::::::::::::::::FR::::::::::::::::R     OO:::::::::OO   M:::::::M             M:::::::M     N:::::::N       N::::::N   OO:::::::::OO   T:::::::::::::::::::::TH:::::::H     H:::::::HI::::::::IN:::::::N       N::::::N     GGG::::::::::::G    //
//    B::::::BBBBBB:::::B  OO:::::::::::::OO R::::::RRRRRR:::::R N::::::::N      N::::::N     F::::::::::::::::::::FR::::::RRRRRR:::::R  OO:::::::::::::OO M::::::::M           M::::::::M     N::::::::N      N::::::N OO:::::::::::::OO T:::::::::::::::::::::TH:::::::H     H:::::::HI::::::::IN::::::::N      N::::::N   GG:::::::::::::::G    //
//    BB:::::B     B:::::BO:::::::OOO:::::::ORR:::::R     R:::::RN:::::::::N     N::::::N     FF::::::FFFFFFFFF::::FRR:::::R     R:::::RO:::::::OOO:::::::OM:::::::::M         M:::::::::M     N:::::::::N     N::::::NO:::::::OOO:::::::OT:::::TT:::::::TT:::::THH::::::H     H::::::HHII::::::IIN:::::::::N     N::::::N  G:::::GGGGGGGG::::G    //
//      B::::B     B:::::BO::::::O   O::::::O  R::::R     R:::::RN::::::::::N    N::::::N       F:::::F       FFFFFF  R::::R     R:::::RO::::::O   O::::::OM::::::::::M       M::::::::::M     N::::::::::N    N::::::NO::::::O   O::::::OTTTTTT  T:::::T  TTTTTT  H:::::H     H:::::H    I::::I  N::::::::::N    N::::::N G:::::G       GGGGGG    //
//      B::::B     B:::::BO:::::O     O:::::O  R::::R     R:::::RN:::::::::::N   N::::::N       F:::::F               R::::R     R:::::RO:::::O     O:::::OM:::::::::::M     M:::::::::::M     N:::::::::::N   N::::::NO:::::O     O:::::O        T:::::T          H:::::H     H:::::H    I::::I  N:::::::::::N   N::::::NG:::::G                  //
//      B::::BBBBBB:::::B O:::::O     O:::::O  R::::RRRRRR:::::R N:::::::N::::N  N::::::N       F::::::FFFFFFFFFF     R::::RRRRRR:::::R O:::::O     O:::::OM:::::::M::::M   M::::M:::::::M     N:::::::N::::N  N::::::NO:::::O     O:::::O        T:::::T          H::::::HHHHH::::::H    I::::I  N:::::::N::::N  N::::::NG:::::G                  //
//      B:::::::::::::BB  O:::::O     O:::::O  R:::::::::::::RR  N::::::N N::::N N::::::N       F:::::::::::::::F     R:::::::::::::RR  O:::::O     O:::::OM::::::M M::::M M::::M M::::::M     N::::::N N::::N N::::::NO:::::O     O:::::O        T:::::T          H:::::::::::::::::H    I::::I  N::::::N N::::N N::::::NG:::::G    GGGGGGGGGG    //
//      B::::BBBBBB:::::B O:::::O     O:::::O  R::::RRRRRR:::::R N::::::N  N::::N:::::::N       F:::::::::::::::F     R::::RRRRRR:::::R O:::::O     O:::::OM::::::M  M::::M::::M  M::::::M     N::::::N  N::::N:::::::NO:::::O     O:::::O        T:::::T          H:::::::::::::::::H    I::::I  N::::::N  N::::N:::::::NG:::::G    G::::::::G    //
//      B::::B     B:::::BO:::::O     O:::::O  R::::R     R:::::RN::::::N   N:::::::::::N       F::::::FFFFFFFFFF     R::::R     R:::::RO:::::O     O:::::OM::::::M   M:::::::M   M::::::M     N::::::N   N:::::::::::NO:::::O     O:::::O        T:::::T          H::::::HHHHH::::::H    I::::I  N::::::N   N:::::::::::NG:::::G    GGGGG::::G    //
//      B::::B     B:::::BO:::::O     O:::::O  R::::R     R:::::RN::::::N    N::::::::::N       F:::::F               R::::R     R:::::RO:::::O     O:::::OM::::::M    M:::::M    M::::::M     N::::::N    N::::::::::NO:::::O     O:::::O        T:::::T          H:::::H     H:::::H    I::::I  N::::::N    N::::::::::NG:::::G        G::::G    //
//      B::::B     B:::::BO::::::O   O::::::O  R::::R     R:::::RN::::::N     N:::::::::N       F:::::F               R::::R     R:::::RO::::::O   O::::::OM::::::M     MMMMM     M::::::M     N::::::N     N:::::::::NO::::::O   O::::::O        T:::::T          H:::::H     H:::::H    I::::I  N::::::N     N:::::::::N G:::::G       G::::G    //
//    BB:::::BBBBBB::::::BO:::::::OOO:::::::ORR:::::R     R:::::RN::::::N      N::::::::N     FF:::::::FF           RR:::::R     R:::::RO:::::::OOO:::::::OM::::::M               M::::::M     N::::::N      N::::::::NO:::::::OOO:::::::O      TT:::::::TT      HH::::::H     H::::::HHII::::::IIN::::::N      N::::::::N  G:::::GGGGGGGG::::G    //
//    B:::::::::::::::::B  OO:::::::::::::OO R::::::R     R:::::RN::::::N       N:::::::N     F::::::::FF           R::::::R     R:::::R OO:::::::::::::OO M::::::M               M::::::M     N::::::N       N:::::::N OO:::::::::::::OO       T:::::::::T      H:::::::H     H:::::::HI::::::::IN::::::N       N:::::::N   GG:::::::::::::::G    //
//    B::::::::::::::::B     OO:::::::::OO   R::::::R     R:::::RN::::::N        N::::::N     F::::::::FF           R::::::R     R:::::R   OO:::::::::OO   M::::::M               M::::::M     N::::::N        N::::::N   OO:::::::::OO         T:::::::::T      H:::::::H     H:::::::HI::::::::IN::::::N        N::::::N     GGG::::::GGG:::G    //
//    BBBBBBBBBBBBBBBBB        OOOOOOOOO     RRRRRRRR     RRRRRRRNNNNNNNN         NNNNNNN     FFFFFFFFFFF           RRRRRRRR     RRRRRRR     OOOOOOOOO     MMMMMMMM               MMMMMMMM     NNNNNNNN         NNNNNNN     OOOOOOOOO           TTTTTTTTTTT      HHHHHHHHH     HHHHHHHHHIIIIIIIIIINNNNNNNN         NNNNNNN        GGGGGG   GGGG    //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BORNFROMNOTHING is ERC721Creator {
    constructor() ERC721Creator("BORN FROM NOTHING", "BORNFROMNOTHING") {}
}
