
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Open the door
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    The sky is slightly bright, before the rooster crows, Chen Ping an has got up, the thin bedding, really can not keep the heat, and Chen Ping an in porcelain apprentice, also developed the habit of getting up early and going to bed late. Yard Chen Pingan opened the door and went to the soft soil, after take a deep breath of relief, stretched himself, out of the yard and turned to see a slight figure, bent, hands carrying a bucket of water, is their gates, with his shoulders handmaid of song dynasty set salary, she should be just back from apricot blossom lane far away. the well to draw water over there.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Chen Pingan look away, across the street, lane, trotted to the town to the east, mud lane in the town of west, the east gate, a man is responsible for the business travel in and out of the town and the night the scouts, usually also charge transfer, some letter from outside come back, Chen Pingan next thing to do, is to send the letter to the town and the people, for a letter of a copper wire, This is the way for him to make money, Chen Ping 'an has been with the other side about, after the rise of the dragon in February, began to take over the business.                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract OTB is ERC721Creator {
    constructor() ERC721Creator("Open the door", "OTB") {}
}
