
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Her good poison
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    "Rather than that, I'd like to know why you two are at Gamut's house." Wang Jue looked at the two girls and said quietly.                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    The two girls saw Wang Jue as their hope for survival and spoke freely.                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    It turned out that the two girls were called Kurabashi Ari-ri and Takagi Suzuka.                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    Have accidentally found a video with the curse of chastity son, the results also silly open to see the last of course received the chastity son call.                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    And bell flower is a dead bear child, the middle-aged man called the hide, the little girl called bead thread, two people have warned bell flower, don't enter the coconut ghost house, but how can stop the curiosity of bear children, finally bell flower or dead into the coconut home, successfully contaminated with the grudge.    //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    When Wang Jue heard this, countless alpacas galloped by. It seemed that it was human nature to die.                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    "Then why are you back in this haunted house?" "Wang Jue asked.                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    Have in and bell flower coincidentally point to the hidden.                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    When there is no more time after the curse, can only look for the supernatural people to help.                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    Did not expect that the so-called master is also half a bucket of water goods, was directly to seconds, and have in the behavior of the zhen son also offended, critical moment, the hidden with bead xu came to the rescue.                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//    Later saved the bell flower in the ghost house.                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HGP is ERC721Creator {
    constructor() ERC721Creator("Her good poison", "HGP") {}
}
