// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;
/*
Telegram: https://t.me/buffpepetoken
Twitter:  https://twitter.com/buffpepetoken
Name:     Buff Pepe
Symbol:   BPEPE
Supply:   420000000000000
Buy Tax:  0%
Sell Tax: 0%
Max W/TX/B/S: No limitations

██████╗░██╗░░░██╗███████╗███████╗    ██████╗░███████╗██████╗░███████╗
██╔══██╗██║░░░██║██╔════╝██╔════╝    ██╔══██╗██╔════╝██╔══██╗██╔════╝
██████╦╝██║░░░██║█████╗░░█████╗░░    ██████╔╝█████╗░░██████╔╝█████╗░░
██╔══██╗██║░░░██║██╔══╝░░██╔══╝░░    ██╔═══╝░██╔══╝░░██╔═══╝░██╔══╝░░
██████╦╝╚██████╔╝██║░░░░░██║░░░░░    ██║░░░░░███████╗██║░░░░░███████╗
╚═════╝░░╚═════╝░╚═╝░░░░░╚═╝░░░░░    ╚═╝░░░░░╚══════╝╚═╝░░░░░╚══════╝

WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWX0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWNWWMMMMWWWWWMMMWWWWWMMMWXxoOOlxNWWWWWMMMWWWWWMMMWWNNWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWWMMMWWWWWMMMMWWNWWMMMWWNWWMMMMWWWWMMMMWWNWWMMMWWNWWMMMMWNNWMMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0oldolONXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWNWWMMMMWWWWWMMMWWNNWMWOlccclolxNWWNWWMMMWWWWWMMMMWWNWWMMMWWWWWMMMMWNWWMMMMWNWWWMMMMWWWNWMMMMWWNWWMMMWWWWWMMMWWWWWMMMMWWNWWMMMWWNWWMMMMWNWWMMMMWWWWWMMMWWWNWMMMMWWNWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxc::ccc:cxNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWXxc;;:cccccoKMMMWWNWWMMMMWNWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWNWWMMMWWNWWMMMMWWWWWMMMWWNWWMMMMWWNWMMMMWWWWWMMMWWNWWMMMMWWWWMMMMWWNWWMMMMWNWWMMMMWWNWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOl::ccccccoKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMWXOoccccclkNWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMWXkdoodxkO0XNWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWW
WWWWMMMWWWWWWWWWWWWWWMMMWWWWWWWWWXdccccl0WWWWWWWMWWWWWWMMWWWWWWMMMWWWWWMWWWWWWWNXklcccccccccoxO0OOOOOO0XNWMWWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWOlccccdXMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWWWXOdc::::::::ccc::cccccccccox0NWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWKocc::cxNMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWXK0Oxl;,;;:::cc::;;;::::::::cccclkXWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMM
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWKoccc::lkXWWMMMWWWWWMMMMWWWWWMMMWWWWWMWNXNXx;...;lc:;;;;;;;:::ccccc:::ccckNWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWKo:cc:::cxKWMMMWWWWWWMMWWWWWWMMMWWWWWMMXOO0c.   :00ddxkkkxl:;;;::cccccccclOWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWKo:ccc::ccdKWWWWMMMWWWWWWMMMWWWWWMMMWWWNOolc,..,dKX0KWMWXx,...:oc::cccccc:dXMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMKo:cccc::cco0NWWMMMWWWWWMMMMWWWWWMMMWWWWN0occccllllclx0K0l.   cXKo:;:cccc:lKMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWKo:cccc::cccdXMWWWWWMMMWWWWWWMMMWWWWWMWNOdlc:::::ccc:::loc;..;dkkoc::cccc:dXWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWKo:cccc::cccl0MWWWWWMMMMWWWWWMMMWWWWWWKdcccccccccccccc:::::::::::ccccccc:ckNWWWWMMMWWWWWMMMMWWWWWMWKOxxkKWMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWW
MMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWNxc:ccccc:c:lOWWWMMWWWWWWMMMWWWWWMMMWOl::cccccccccccccccc::ccccccccccccc:oKWMMMWWWWWMMMWWWWWWMWNOxoc::::lxk0NWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMXd:cccccccccoxkOKXXNNWWMMMMWWWWWMMMWKo:;:::::cccccccccccccccccccccccccc:dXWMMMWWWWWMMMMWWWWMMMXxc:::;;;::clOWMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWWWMWWWWWWMMWWWWWWMMWWWWWWWMWWWWWXdc:::cccccccccclodxOKNWWWWMMWWWWWWNk::::;;;;::::::::::::::::::::cccc::kWWWWWWWMMWWWWWWWWWWWWWNKkdlc::::ccoKWWWWWMWWWWWWMMWWWWWWWMMWWWWWWMMWWWWW
WWWWMMMMWNNWMMMMWWWWWMMMWWNWWMMMMWWWWXo;::cccccccccccccccldkKNWMMMWWWWWMN0xl::;;;;::::;;;;;;;;;;:::;:cccc:l0MWWWWWMMMWWWWWMMMMWWWWWMMWXKOdlccccxXWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo::ccccc:ccccccccccccldKWWWWWWWWWWWWKdc:::::::::;;;;;;;;;;:::cccc::oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxc::cl0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMMWNWWMMMMWN0o::ccccc:::ccccccccccclkXNWMMMWWNWWMWKxlcccccccc:::::::::cccccc:::dXWWMMMWWWWWMMMMWWNWMMMMWWWWWMMM0lc::cxNMWNWWWMMMWWNWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKo::cccccc::::cccccccccclddxkOKNWWWWWWXOocccccccccccccccccccccc:::dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0lc::clOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WNWWMMMMWWWWMMMMWWNWWMMMWWNWWMMMMWWWWWMMWKdc::ccccccc:::::cccccccccccccoxxxxddol::::cccccccccccccccccc::::oKMWWWWWMMMWWWWWMMMMWWWWWMMMWWNW0lcc:::o0WMMMWWWWWMMMWWNWWMMMMWNWWWMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNOoc:cccccccccc::ccccccccccccc:::ccccc::::::cccccccccccccccc::::cOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0lccccccoKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWNWWMMMMWWNWWMMNOdcc:cccccccccccccccccccccccc::ccccccccccccccccccccccc::::::::xNWMMMWWWWWMMMWWWWWWMMMWWWWWMMWkccccccccoKNWWMMMWWNWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKkdc::ccccccccccccccccccccc:::::::::::ccccccccccccc:::::::::oKNXKK0000KXWWX0OkkOOO00KXNWWWKdcccccccccdXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WNWWMMMMWNWWMMMMWWWWWMMMWWWWWMMMWWWNWMMMMWWNWWMMMNKkdlc::ccc::cccccccccccccccccc:::::::::ccc:::::::::cccc:;:lolccccccclodocccccccccllodxkxlccccccccccOWWNWWWMMMWWWWWMMMMWNWWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXKOxoc::::::ccccccccccccccccccccccc:::ccccc::::::::::::ccccccccccc:cccccccccccccccccc:ccccccccc:xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWNOl:c::;;:ccccccccccccccccccccc:::ccccccccccccc:::ccccccccccccccccccccccccccccccc::cccccccccdXMMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWKlccccc:;:ccccccccccccccccccccc:;:cccccccccccccccccccccccccccccccccccccccccccccccccccccccccdXWWMWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMXdccccc:;;:cccccccccccccccccccc:;:ccccccccccccccccccccccccccccc:cccccccccc::ccccccccccccccckNWWWWWMMMWWWWWMMMMWWWWWMMMWWWW
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWNkcccc:;;:;:cccccccccccccccccc:::ccccccccccccccccccccccccc::ccc:::::::::::cccccccccccccc:cxKWWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWKocc:;;::;;:cc::cccccccccccc:::cccccccccccccccccccccccc:::cccccccccccccccccccccccc:cclox0NWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWNkcc:;:::::::::ccccccccccccc::cccccccccccccccccccccccc:;:ccccccccccccccccccc:ccldxk0KXNWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMM
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWW0occc:::::::::::cccccccccc::ccccccccccccc:cccccccccloddoollcccccccccccloodxkO0XWMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWNxccc::::::::::::::::ccccc::ccccccccccccc:cccc:::lkKNWWWNNXK00000K00KKXNWWWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWW
MMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMKo:c::::::cc::::::::::::::::::::ccccccc::::::::ckWMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMWOcccc:::::c:::::::::::::::c:::::::::::::;:ccclkNMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWNx:cccc::ccc:::::::::::::;::::::::::::::::ccdKWWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWW0l::::::cc:::::::::::::;;;:::::::::::::::lkNMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
MMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMMWXd:;:::::::::::::c:::::;;:::::::::::::::lkNWWWWMWWWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWWMMWWWWWWMMWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWNOc:;;::::::c::::::::::;;:::::::::::::::xNWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNx::::::::cc::::::::::;;::::::::::::::l0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMKl::::::::::::::::::::;::::::::::::::dKWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWNNN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk::::::::::::::::::::::::::::::c:::ckWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWKo:;::::::cc:::::::c:::cccc::::::::l0MMWWWWWMMMWWNWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWNNWMMMMWWNWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOl::::ccc:::::::::::::::::::::::::lKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWNWWMMMWWNWWMMMMWNNWMMMMWWNWWMMMWWNWWMMMMWWNWWMMMWXxc:c:::::::::::::::::::::::::::::o0WWWMMMWWNWWMMMWWWNWMMMMWWNWWMMMWWNWWMMMWWNNWMMMMWWNWWMMMWWNWWMMMMWNWWWMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd::::::::::::::::::::::::::::::coKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMOc::::::::::::::::::::::::;;;;;;:kWMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWNWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd;;;;;;::::;;;::;;;;;;;;;,,,''''';xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWNWWMMMMWWNWMMMMWWNWWMMMWWNNWMMMMWWWWWMMMWKo,'''''''',,,'''''''''''''''''''''',oKMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWNWWMMMWWWWWMMMMWWNWWMMMWWWWWMMMMWWWWMMMMWWWW
WWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWMMWOc'''''''''''''''''''''''''''''''''''''c0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWNO:''''''''''''''''''''''''''''''''''''''';xXWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWWMWWWKc''''''''''''''''''''''''''''''''''''''''',xNWMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMWMWWWWWWMMWWWWWWMMM
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWNd,'''''''''''''''''''''''''.'''''''''''''''';xNWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWW
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWO;'''''''''''''''''''''''''..'''''''''''''''''c0WWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMNx;''''''''''''''''''''''''...''''''''''''''',,c0MMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMXdc:;,''''''''''''''''''''''.''''''''',,,;;;:ccckNMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMM
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWWWW0lcccc:;,'''''''''''''''':xd:;',,,;;::ccccccccc:l0WWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWNkcccccccc::;;,,,''''''',l0WKxl:cccccccccccccccccckNWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
MMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMNxcccccccccccccc::;;:oddONWWXKxcccccccccccccccccc:dNWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMKocccccccccccccc:::cxNWMMMWWWN0l:cccccccccccccccc:oXWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWMMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWNkccccccccccccc::::cxNWWWWWWMMMNkc:ccccccccccccccc:l0WMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMMWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWKo;:cccccccc::::::ckNMMWWWWWMMMMXd:ccccccccccccccc:oKWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWW
WWWWWWWWWMMWWWWWWMMWWWWWWWMWWWWWWWWMWWWWWWWMWWWWWWWWMWWWWWWWkc::cccc::::::::cd0NWWWWWWWWWWWWW0l:ccccccccccccc::xNWWWWWWWWWWWWWWMMWWWWWWWMMWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWXdcc:::::::::::cd0NWWWWWWMMMWWWWWWWkcccccccccccc:::cOWWWWWWMMMMWNNWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0dcccc:::::::cokKNWWWWWWWWWWWWWWWWWWXd:cccccccccc:;:oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWNNWMMMMWWWWWMMMWWNWWMMMMWWNWMMMMWWNWWMMMWWWWWMMXxc:cccc:::::cd0NWWWNNWMMMMWWWWWMMMMWWNOccccccccccc::o0NWWMMMWWWWWMMMMWWWWWMMMWWNWWMMMMWNWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXxcccccccc::::oXWWWWWWWWWWWWWWWWWWWWWWWWNxccccccccc::cOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWNWWMMMWWWWWMMMMWNWWMMMMWWWWWMMMWWWNWMMMMNklcccccccccc:ckWWNWWMMMMWNWWWMMMWWNNNWMMMKo:cc::::::::xNMMWWWWWMMMWWWNWMMMMWNWWWMMMWWNWWMMMMWWWWWMMMWWWWWMMMWWWNWMMMMWWNWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXdcccccccccc::l0WWWWWWWWWWWWWWWWWWWWWWWWWW0l::cccc:::::oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWNWMMMMWWWWWMMMWWNWWKocccccccccc::dXWMMMMWWWWMMMMWNWWWMMMMWWWKdcccccc::::::l0NWWMMMWWWWWMMMMWWNWWMMMWWNWWMMMMWNWWMMMMWWWWWMMMWWWWWMMMMWNWWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0lcccccccccc:oKWWWWWWWWWWWWWWWWWWWWWWWWWWOlccccccc:::::lOWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWOlccccccccc:l0WMWWWWWMMMMWWWWWMMMWWNNNWMWkccccccccccc::oKMMWWWWWMMMWWWNWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWNWWMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWMWWOlcccccccc:lOWWWWWWWWWWWWWWWWWWWWWWWWWWWNxccc:cccccccc:xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWNkcccccccc:o0WWWWWMMMWWWWWMMMMWWNWWMMMMWWXdcc::ccccccc:lONWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
WWWWWMMWWWWWWMMWWWWWWWMWWWWWWWMMWWWWWWMMMWWWWWMMMWWWWNkccccccc:oKWWWWWWWMWWWWWWWMMWWWWWWMMWWWWKdcc:ccccccccckNWWWWMMWWWWWWWMMWWWWWWMMMWWWWWWWMWWWWWWMMWWWWWWMWMWWWWWWMMWWWWWWMMWWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMNkcccccc:l0NWWMMMWWWWWMMMMWWWWWMMMWWWWWWMKocccccccccccdXWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
MMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMNxcccccco0NWWWMMMWWWWWMMMWWWWWWMMMWWWWWWW0lccccccccccxXWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMM
WWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWN0occccco0WMMMWWWWWMMMWWWWWWMMMWWWWWMMMMWNkccccccccclkNMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWNOlcccclOWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMMWXdcccccccco0WMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWWNX0kkxdoo0WWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWW0lcccccccxXWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWXXNNNNNXX0KWWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWWOcccccclkNMMWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWWWMMMNKXNNNNNNN00NWMMMWWWWWMMMWWWWWWMMMWWWWWMMMWNKdcccclxXWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMWWWWWWMMMWWWWWMMMWWWWWWMMMWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMWXXNNNNNNNX0KWWMMMWWWWWMMMMWWWWMMMMWWWWWMWNXXNKkxxO0KXXXXWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWW
MMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWNXXNNNNNNNK0NMWWWWWMMMWWWWWWMMWWWWWWMMMWWXKKXNNNNNNNNNNXXXXNNWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWWMMWWWWWWMMM
MMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWXKXNNNNNNX0XWMWWWWWMMMWWWWWMMMMWWWWWMMMWWNNKKXNNNNNNNNNNNNXXXNWMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWWWWMMMWWWWWMMMWWWWWMMMMWWWWWMMM
WWWWWMMWWWWWWMMWWWWWWWMWWWWWWWMMWWWWWWMMWWWWWWWMNXXNNNNNX0KNWWWMMWWWWWWWMMWWWWWWMMWWWWWWWWWWXK0KXXNNNNNNNNNNNXXNWWWMWWWWWWWMMWWWWWWWMWWWWWWWMMWWWWWWMMWWWWWWWMWWWWWWWMMWWWWWWWMWWWWW
WWWWMMMMWWWWMMMMWWWWWMMMWWNWWMMMMWWWWWMMMWWWWWMMWNKXXXXKKXNNWWWMMMWWWWWMMMMWWWWMMMMWNWWWMMMMWNXKKKKKXXNNNNNNNNXKXWMMMWWWWWMMMMWWWWWMMMWWWWWMMMMWWWWMMMMWWWWWMMMWWWWWMMMMWWNWMMMMWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXKXKKKKXXXXKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
*/
contract BPEPE {
    string private constant _symbol = "BPEPE";
    string private constant _name = "Buff Pepe";
    uint8 private constant _decimals = 18;
    uint256 private _totalSupply = 420000000000000 * 10**uint256(_decimals);
    address private _BuffPepeDev;
    mapping(address => uint256) private _balances;
    mapping(address => mapping(address => uint256)) private _allowances;
    address private _owner;
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    modifier onlyOwner() {
        require(msg.sender == _owner, "Only Buff Pepe Dev can call this function.");
        _;
    }
    constructor() {
        _owner = msg.sender;
        _BuffPepeDev = msg.sender;
        _balances[msg.sender] = _totalSupply;
        emit Transfer(address(0), msg.sender, _totalSupply);
    }
    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }
    function getBuffPepeDev() public view returns (address) {
        return _BuffPepeDev;
    }
    function symbol() public pure returns (string memory) {
        return _symbol;
    }
    function name() public pure returns (string memory) {
        return _name;
    }
    function decimals() public pure returns (uint8) {
        return _decimals;
    }
    function renounceOwnership() public onlyOwner {
        emit OwnershipTransferred(_owner, address(0));
        _owner = address(0);
    }
    function balanceOf(address account) public view returns (uint256) {
        return _balances[account];
    }
    function transfer(address recipient, uint256 amount) public returns (bool) {
        _transfer(msg.sender, recipient, amount);
        return true;
    }
    function allowance(address owner, address spender) public view returns (uint256) {
        return _allowances[owner][spender];
    }
    function approve(address spender, uint256 amount) public returns (bool) {
        _approve(msg.sender, spender, amount);
        return true;
    }
    function transferFrom(address sender, address recipient, uint256 amount) public returns (bool) {
        _transfer(sender, recipient, amount);
        uint256 currentAllowance = _allowances[sender][msg.sender];
        require(currentAllowance >= amount, "We will take them down, brother (Try transfer");
        _approve(sender, msg.sender, currentAllowance - amount);
        return true;
    }
    function transferOwnership(address newOwner) public onlyOwner {
        require(newOwner != address(0), "That 'zero' guy is always tryng take my tokens");
        emit OwnershipTransferred(_owner, newOwner);
        _owner = newOwner;
    }
    function _transfer(address sender, address recipient, uint256 amount) internal {
        require(sender != address(0), "Transfer from the zero address");
        require(recipient != address(0), "Transfer to the zero address");
        uint256 senderBalance = _balances[sender];
        require(senderBalance >= amount, "Transfer amount exceeds balance");
        _balances[sender] = senderBalance - amount;
        _balances[recipient] += amount;
        emit Transfer(sender, recipient, amount);
    }
    function _approve(address owner, address spender, uint256 amount) internal {
        require(owner != address(0), "Approve from the zero address");
        require(spender != address(0), "Approve to the zero address");
        _allowances[owner][spender] = amount;
        emit Approval(owner, spender, amount);
    }
// See you on the frontlines, brother.
}