// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: dickhead
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    WWWMMMMWWWWWWMMWWWWWWWMWWWWWMMMMMWWWMMWMMWWWWWWMMMMMWWMMWMMMMMMMWMMMMMMMMMMWWWWWMMWWWWWWWWWWWWWMWWWMMMWWWWWWWWWMMMMMMMWW    //
//    MMWWWWWWMWWWMMMWWWWWMMMMWWMMMMMMMWWWMMWMMWWWWMWWMWWMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMWWWWWMMWWMMMWWWWWWWWWMWWWWWWMM    //
//    MMWWWWMMWWWWWMMMWMMMMMWWMMWWWWWMMWWWMMMMWWWWMMMWMMMWMMWWMWWWMMMMMWWWWWWWWWWMMMMMWWWMMMMMMMMMWWMMMWWMMMWWWMMWWWWMWWWWWWMM    //
//    WWWWWWWWWWWWWMMMMMMMMMWWWWWMMMMWWWWWWWWWWWMMMMMMMMMWWMWMMWMMMMMMWMWMMWMWWWWWWWWMMWWWMMMMMMMMMMWWMWWMMMMWMMMMWWWMMWWWWWWW    //
//    WWMMMWWWWWMMMMWMMMWWWWWWWWWWWMWWMMWWWWWWMWWMMWWWMMMWWWWWWWWWMMMMWWWMMWWWMMMWWWWWMMWWWWMWWMMMMMWWWWWWWWWMMMMMWWWMMWWWWWWW    //
//    MMMMMWWWMMMMWWWWMWWWWWMMMWWWWWWWMMWWWMMWWMMMMWWWMWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWWWWWWMMMWWWWWWWWWWWWWWWWWWMWWWWWMMWWWWWWM    //
//    MMMMWWWWMMWWWWWMMMWWWWWWWWMMWWWWMWMMWWMMWWWWMWWWWXdccccccccccccccccdXWWWWMMWWWWWMMWWMMMMMMMWWWWWMMWMWWWWWWWWWWWMMMMWWWMM    //
//    MMMMMMWMMWWWWWWMMMMWWWWWWWWMMWWWWWMMWWWWWWMWWXx::;..................;::dXNNWWMMMMMMWWMMMMMMMWWWMMWWMWWWWWWWWWWWMMMMWWWMM    //
//    WWWWWMMMMMMWWWWWWWMMMWWWWMMMMMWMMMWWMMMMWWWXx;..........................;:cOWWNWMMMMWWMMMMMMMMWWWWMMMWWMWWMMWWWWWWWMMMMM    //
//    WWWWWWMMMMMWWWWWWWMMMMMWWWWMMMMMMMMMWWWWWXx;............................'lOKKocOWWWWMWWWWMMMWWWWWWWWMWWWMMMMMWWWWWWMMMMM    //
//    WWWWWWMMMWWWMMMMMMMMMWWWWWMMMMMMMMMMMMWWO;...........................cO0kO0d,.'kWMMMMMMWWWWWWWWMMMWWMMMWWMWWMMMMMMWWWWWW    //
//    MWWWWWWMMWWMMMMWWWWMMMMWWWMMMWWWWWMMMMNKo..........................cOKKd;''.. .oKNMMMWMMMMMWWWMMMMWWWMMWMMWWMMMMMMMWWWWW    //
//    WMMWWWWWWMMMMWWWWWWWMMMWWWWWWWWMWWMMNKd,.....,,;;;,,,,,'........'cOXKd,.........;0MMMMMWWWMMMMWWWWWWMWWWMMMMMWWWWWWWWMWW    //
//    WMMMMWWWWWMMMMMWWWWWMMMMMMMMMMMWWWNKd;',;;;:xXNNNNNNNNNOc;;;;;;cOX0x;............o0NMWWWWMMMMMMWWWMMMMMWMMWWWWWWWWWWWWWW    //
//    MMMMMWWWWWMMMMWMMMMWWWWWMWWWWWWMWKd;..:0NNNNWWWMMMMMMMMWWNNNNNNWWK:...............;0MWMMMMMMMMMWMMWWWWWMMMMWWWWWWMMMWWWM    //
//    MWWWMMWWWMMMMWWWMWWWWWWWMWWWWWWMXc....:KMMMWWMMWWMMMMMMMMMWMMMMMMK:...............'lONMWMWMMMMMMWWWMMWWWWMMMMWWWWWWWWWWM    //
//    MWWMMMWWWMMMMWWMMMWWMMMMMWWMWWMMXc....:KMMWWMMMMWMMMMMMMMMWMMMMWMK;.................:KMWMMMMMMMWWWMMMMWWWMMMWWWWMMMWWWWW    //
//    WMMMWWMMMMMWWWWMMMWMMMWMWWMMWWWOl'...:kNMWWWMMMWWMMMMMMMWWWWMMWWMK:.................:KMWWWMMMMWWWWMMMMWWWMMMWWWWMMMWWWWW    //
//    WWWWWWWMMMMWWWWWWWWWMMMMMMWWMMNl....,0WMWWWMMMMWWMMMWWMMWMMWWWMMMK:.................'lONMWWMMMMMWWWWWWWWWWWWWMMMMWWWWWMM    //
//    MMWWMWWWWWMMMWWWWWWWMMMMWMMMMMNl....,0WWWWMMMMMWWMWMMWMWWMMMMMMMMNOl'.................cXMMWWWWWWWWWWMMMMWWWWWMMMMMMWWWWW    //
//    WWWWMMMMMWWWWWMMMMMMMMMMMWMMWOc'....,0MWMMMMMWMMMWWWWMMMWWMMMWWMMMM0,.................cXMWWWWWMMWWWMMMWWWMWWWWWMMMMMMWWW    //
//    WWWWMMMMMMMMMMMMMMMMMMMMMMWMNo......,0MWMMMWWMMWWMWWWMMMWMMWWWMWWMM0,.................cXMMMWWMMMWWWMMMMMWWWMMMWWWMMMMMMW    //
//    MMMWWWWWWMMMMMWWWWWWMMMMMMWWWo......,ONNNNNNNNWMWWWNNNNNWWWNNNNNNNNO,.................:KWWMMMMMWMMMMMMWWWWWMMMWWWMMMWWWW    //
//    MWWWWWMWWWMMMWWWMMMMMMMMMMMWNd.......,;;;;;;;cOWMXo;;;;colc:::;;;;;,...................:kWMMWMMWWWWWMMMMMMWWWWWMMWWWWWWW    //
//    MWWWWWMWWMMMMWWWMMMMMMMMMMMMNo................xWMK;....,,''......''...................cOXWMMWMMWWWWWWWWMMMMMWWWMMMMWWMMW    //
//    WWMMMWWWWWWWWWMWWWWMMMMMMMMMNo......:kKKK0o,';kWMKc''cOKKK0o;,';xKKk:...............;kXWMWWMMMWWWMMWWWWWWMMMMWWMMMWWWMMW    //
//    WWMMMWWWWWWWWWMMWWWMMMMWMMWMNo....'xXWMMWWNXKXNWWWXXKXWMMMWNXXKXNWMWXd'.............:KMWWWMMMMWWWMMMMMWWWWWMMMMMMMWWMMWW    //
//    WWMMMMWWMMMWWWWMMMMMMWWMMMWX0c....'OWWMMMWMWWWMMMMWWWWWWMWWWWWWMWWMMMO'............'oXMMMMMWMMWMMWMMWWMMWWWWWWWWMMWMMWWW    //
//    WWWMMMMMMMMMMWWWWMMMMMWMMMWx,.....,OMMMMMMMMMMMMWWWWWWWWMWWWWWWMMMMN0o.............okOOOKWWWMWMMMWMMWWWMMWMWWWWWWWWMMMWW    //
//    MWWWWMMMMMMMMWWWWMMMMMWMMMWd......,OWMMWMMMMMMMWMMWMMMMMMWMMMMWMMN0o,...................:kKWMWMMWWWMMMWWWWMWWWWWWWWMMMMM    //
//    MMWWWWWMMWWWWWWWWMMMMMWWMWWd. ....'OMWWMWWWWWWWWMMMMMWWMMMMMMMMMMK:.......................oNMWWMMWWWMMMWWWWWWMMWWWMMMMMM    //
//    WMMMWWWMMWWWWWMWWWMMMMWWMMWd.......cONWWWMWWWWWW0kkONMMMWMMWWMMN0o'.......................oNMMMWMMWWWMMWWWWWWMWWWWWWMMWW    //
//    WWWWWWWMMWWWMMMWWWWWWWWWMMWd........;0MWWWMWWNOo;..;0MWWWWWWMMMXc.........................cxXWMMWWWWMMMWWMMWWWMMMWWWWMWW    //
//    WWWWMMWWMMWWWWWWMWWWMWWWWMWx........;0MWWMMWWWOl,..;0MWWWMWWMWOl'...........................:dKWWWMMMMWMMMMMWWWMMWWWWMWW    //
//    MWWMMMMWWMMMWWWMMMMMMMMMWWWx........':kNMMMWMMMXc...:llkNMWWWNl.... ..........................xWWXxllkNMMMMWWMMMMMWWWWMM    //
//    MMMWWWMWWMMMWWWMMMMMMMMMMWWd......';'.:KWWMMMWWXc..'lxxONMWOol'...............................;cl;...'ckNWMWWWMMMMMWWWWW    //
//    MMWWWWWWWMMMWWWWMMMWWWWMMMWd...........:xXWWWWMN0kxONMMMMWNo...........................................'cOWWWMMMMMMWWWWW    //
//    MMMMMMMWWWMWWWWMMMMWWWMMWMWd.............:kNMWWWWMWWWWWNNkc,.............................................oNMWWMMMMMMMWWW    //
//    WWWMMMMWWMMWWWMMWWWWWWMMMMWd..............lKNNWWMWWNN0o::,';c:,..........................................oNMWWWWMMMMMMWW    //
//    WWWWWMMMMMMMMMMMMWWMMMMMMMWd...............,;ckXXKxll:'....,;;'...''... .................................oNMMWWWWWWWWMMW    //
//    WMMMWWWMMMWWWMMMWWWWWWWWMMWd...................',,,'.'...........'',...................................',xWWWWWWMMWWMMMM    //
//    MMWWWWWMMWWWWWMMMWWMMWWWWMWx........,;'..........',;..............................................',,l0KXNWWWWWWWWWWWWWM    //
//    MWWWWWMWWWMMMWWMMMMMMMWWWMWx.......''............,k0l;c;..........';;'...........................;kXXNWWMWWWWWWWWWWWWWMM    //
//    WWWWMMMMWWWWWWMMMMMMMMMMWWWk'....................'OWNNNOlcl;..,:;lONNOc'....''................',:dXMMMWMMWWMWWMMWWWWWWMW    //
//    WWWWWWWWWWWWWMMMMMMMMMWWWWWx'....................'OMWMMWWWNkolONNWWMWWNx'....'......... ....,,':OWWMMWMMMMWWMMMWWWWMWWWW    //
//    WMMWWWWWMMMWWWWWMMWWWWWNOkxc'....................,OMMMMMWMMWWWWWWWWMMMWk'...................;;;lONWMMWWWWWWMMMMWWWWWWWWM    //
//    WMMWWWWWWMMMMWWWWMWWWMWO;........................'OMMMMMMMMMMMWWWMMWWMWKo;....................,;:dXMWWWWWWWWMWWMWMMWWWWM    //
//    MMMMWWWWWWMMMWWWMMWWWXkc.........................'OMMMMMWWWMMMWMMWWWWMMMWd...............'.......:0MWMMWWWWWWWMMMMMWWMMM    //
//    WWWWWWWMMWMMWWMWMMWWM0,.........................:xXWMMMMMWWWMMMMWMMMMMMMWx........''............cxXMMMWWMMMMMWWWMMMMMMMM    //
//    WWWWWWWMMMMMWMMMWMMMM0;.......................:xKWWWMMMMMMWWWWWWMMMMMMMMWx'.............'......,OMMMMWWWWMMMMWMMWWWWMMMM    //
//    MMWWWWWMWWNNNWWNNWWMM0;.....................:xKWWWWWWMWWMMMWWWWMMMMMMMMMWd.......,;,''.........:0MWMWWWWWWWWMMMMMWWWWWWW    //
//    WWWWWWMMWWWWWWWWWWWMMNOkkl'...........;dkkkkKWMWWWWMWWMMMMMMMMMMMMMMMWWWWx......;c:;;,'....''..:0WWWWWWWWMMMMMMMMMMWWWWW    //
//    WMMWWWMMMMMWMMWMMWMMMWMMWXOkkkkkkkkkkk0NMMMMMMMMWMMWWMMMMMMMMMWWWWWWWWMWWXOkkkO0K0OOOOOOOOO00OO0NWWWWWMMMMMMMMMMMWWWMWWW    //
//    WWMMMMMWWMMMMWWWMMMMMMMWWMMWMMMWMMMMWMMMMWWMMMWMMWWWMMMWWWWWWWWWMWWWWWMMWWMWMMMMMMMMWMMMMMMWMMMMWMWWMMMMMMWWWWMMMWWWMMMW    //
//    WWMMMWWWMMMMMMWWMMMWMMMWWMMMWWMWWMMWMMMMMWWMMMWWMWWWWMMMMMMMMMMMWWMWWMWWWWWMMMMWWWWMWMMMMMMMWMMWMMMMMMMMWWWWWWWWMMWWWMMW    //
//    WWMMWWMMMWWWWWWWMMMWWMMMMWWWWWWMMMMMMWMMWWWMMMWWWWWWWWMWWWWWWMMMWWWWWWWWWWMMMMWMMWWWWMMWWWWMMMMMMWWWMMMMWWWWWNNWWMMWWMMW    //
//    WMMMMWWWWWWMWWWWMMMMMMMMWWWMWWWWMMMWWWWWWWWMMMMWWWWWMMMWWWWWWMMMWWWWWWMMMMMMMWWMWWWWWMWWWWWMMMMWWMMMMWWWMMWWWWWWMMWWWMWW    //
//    MMMMMMWWMMMWWMWWMWWMMMWWWWWWWWWWMMMMMMMWWWWWMMWWWWWMMMMWWWWWWWMWWWWWMMMMWWMMMWWWWWMMWWWWWWWMMMWWWMMMMWWWWWWWWWWWWWMMWWWM    //
//    MMWWWWWMMMMWWMWWMWWWWWWWWWWWWWWWMWWWWWWWWWWWMWWWWWMMMMWWWWMMMWWWWWWMMMMWWWMMWWWWMMMMWWWWWWWMMMMWWWWWWWMMMMWWWWMMWWWWWWMM    //
//    MWWWWWWMMWMMMWWWWWWWWWMWWWWWWMWMMWWWWWWWWWWMMMWWWWMMMMWWWWMMMWWWMWWWWMMMMMMWWWWMMMMWWWWWWWWWWWMMMWWWWWMMMMWWWWMMMWWWWMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract dkh is ERC1155Creator {
    constructor() ERC1155Creator("dickhead", "dkh") {}
}
