//"SPDX-License-Identifier: UNLICENSED"

pragma solidity ^0.6.12;

//PERFECT SQUARE PRINCIPLE 1 :

//NOTARISED ON THE BLOCKCHAIN ON OCTOBER 20 2020 AT 20.20 PM THAI TIME .

//YOU ARE ENTITLED TO ABSOLUTE FREEDOM OF SPEECH ,
//BUT BE PREPARED TO FACE THE CONSEQUENCES ,
//ESPECIALLY IF IT ENCROACHES ON ANY ASPECT OF HUMAN DIVERSITY .

contract perfectSquarePrinciple
{
   
}