// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Recovery For 001
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                          //
//                                                                                                                                                                          //
//    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    //
//    //                                                                                                                                                              //    //
//    //                                                                                                                                                              //    //
//    //    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::            //    //
//    //       .5GPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGPGGGGGGGGGGGGGPPPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGPGGGGGGBBBBBB##########BBBBBBGGGGPGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGPGGGB###&BGPPGYJ?777!!!!!!777?JYGPGG#&#B#BGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGPPGB###BP5?!~:.                       ..:~!?PPB##BBGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGB&#G57^.                                      :~75B##BGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .5GPPGG#&GJ^.                                              .~YB&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPG#&5~                                                     .!P&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGG&#~  ~55YJ: :!??J^  ^7J~  ^JY5~ .?    ?::7??J:^555J: .?. 7:  7&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PB&#:   J&^^YB !@?77:.5BJJB !#?^7#7.&7  JB.?#777.?@^:Y# :@: @~   ~&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PB@7    !@:^GP ~@777 ?G.   .&~   !& !&.^@^ 7&777 !@:^PP :@: @!    Y@GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .5B@?    !@5#P. ~@77! PJ  .^:@:  .PY  P5G7  7&77! !@5#G. :G. G~    5@GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PB#&^   !@.^GY.~@??Y:~B?7GY YG77PG.  ^@P.  7&??Y.~@.^GY..?. ?^   7@#GPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGG&&!  :!  .?. ~!!~. ^??!   !?J!     !^   .~!!~.:!  .?..P: J^ :Y&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPG#&5~                                                     :J#@BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGB#&GY^.                                              :75&&BGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGB&#G57^.                                     .^!YP&##GPGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGPGGB###BP5?!~^:..                    ..:^!?55B###BGGPPGPGGGGGGGBGGGGGGPPGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGPGPGGB####&BGPPP5YJ????7!:     ~5PGG###B#BGGPGGGGB#&#&&&@@@@@@@&&&&&#BBBGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGPPGGGGGBBB#BBBBBB###G~  ^@#BGGGGGPPPGGB#&&@@@@@@&@@@@@@@@&@&@@@@@@&&#BGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGPGGGGPGPPPGPPPGGG#&P^:B&GPGGGPGGB&@@@@@&@BGGJ?7!!!~~!!!7?JPGB@&@@@@&&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG##PY#&#GPGB&@@@@&@GY7~..                ..~7YG@&@@@&&BGPGGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGB&#&#G#&@@&@&P7^.                          .^7P&@&@@&#GPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGPGG#&@@&&BJ^                                  ^JB&&@@&#GPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGB&@@&@#7.         ^.  .             .^         .?B@&@@&BPGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGP#@@@&&Y:       ~5. #^ P~          Y~ ~&  J~       :5&&&@&BPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGG#@@&&#~      .Y!.5PJP?YB..J!    ~?:^#JJP?5G.^7.      ~#@&@@#PGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPG#@@&&G^        ^?B?^!!!^?PY?.    .7JP?^!7!~JPJ!        :B&&@@#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPB@@&&#:          :@ ~@#@J 57        ?J 5@#@^ @.          :#&&@@BPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGG&@@#@^           .B7:?5J^~G:        ^G^^JY7:?P.           ~@#@@&GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPB@@#@Y             .7Y!!!J?:          ^?J!!7Y7              5@#@@BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG&@@#@^                .::.              .::.                ^@#@@&GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG@@@&&:    .~J!                                      !J^.    :@&@@@GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG@@&@#.  ~5GY!5:                                    :B!YG5~  .#@&@@GPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG@@@&@.  !Y^  !B.                                  .B7  ^J7  .@&@@@GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPG&@@#@^        5G:                                :GP        ^@#@@&GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPB@@#@Y        .5B!                              !#P.        Y@#&@BPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPG&@@&@^         Y@P~.                        .!G@5.        ^@#@@&GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB@@&&#:         7#&G?:.                   ^?G@#?         :#&&@@BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGP#@@&&G:         :J#&#BJ7^:.        .:^7YB#&#Y:         :B&&@@#GPPGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPG#@@&&#!          :?G&&@#BBP55Y555GBB&@@&G?:          ~#&&@@#GPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPGGGB@@&&&Y:           ^?5B&&@@@@@@@@&#B5?^           :Y&&@@@BGPGGGGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGPGGPB&@@&@B?.        ^?. .^!7JYYJYJ7~~: :7:        .?B@&@@&GGGGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGPGB&@@&&BJ^   .~57Y!  5..!. 7 ^!Y!^ 7J?Y^    ^JB&&@@&#GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPG#&@@&@&P7^^7^^B^ ~#YP^  B:..Y!  !P^~?:^?P&@&@@&#GGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGB&@@@@@&GY!~7. 7! J7  P:  :5  :!~!YG&@@@@&&BGPGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGB&@@@@@&@BGGJ77!?!~77!!7?JGGG@&@@@@@&BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGGB#&&@@@@@@&&&@@@&@@@&&@@@@@@&&#BGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGGGB##&&&&@@@@@@@@&&&&#BBBGGPPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPPPGGGGGGGGGGGGGGGPPPGGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGPGP.       //    //
//    //       .PGPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPG5.       //    //
//    //        ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::        //    //
//    //                                                                                                                                                              //    //
//    //                                                                                                                                                              //    //
//    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    //
//                                                                                                                                                                          //
//                                                                                                                                                                          //
//                                                                                                                                                                          //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract NFTForRecovery is ERC1155Creator {
    constructor() ERC1155Creator("Recovery For 001", "NFTForRecovery") {}
}
