
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The birth of
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    The bottomless abyss, where all the evils of the multiverse converge, is also the opposite of all that is good, good, and pure.                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    Here from no friendship, family, love, only betrayal, killing, destruction of evil land.                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    The sea from which the demons originate, located in the abyss, or otherwise called the River Styx, runs through the abyss's infinite planes. It represents the ultimate death, the very foundation of the multiverse, devouring everything that comes near, even the gods whose scarlet waters are devoured by it, but it is also the birthplace of demons, endless demons born here.    //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    A scarlet light shone from the sky, from the scarlet stars, on the endless banks of the river. The bottomless abyss, where all the evils of the multiverse converge, is also the opposite of all that is good, good, and pure.                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    Here from no friendship, family, love, only betrayal, killing, destruction of evil land.                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    The sea from which the demons originate, located in the abyss, or otherwise called the River Styx, runs through the abyss's infinite planes. It represents the ultimate death, the very foundation of the multiverse, devouring everything that comes near, even the gods whose scarlet waters are devoured by it, but it is also the birthplace of demons, endless demons born here.    //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//    A scarlet light shone from the sky, from the scarlet stars, on the endless banks of the                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TBO is ERC721Creator {
    constructor() ERC721Creator("The birth of", "TBO") {}
}
