
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Wisdom? Experience!
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//    That's right, gene lock." Chu Xuan confirmed that by the way popularized the knowledge of gene lock.                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//    In very ancient times, about 30 million years ago, when the world we live in today was murky, our ancestors were apes.                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//    There are archaeological gaps in this era, and don't believe the book's depiction of human evolution slowly. The most advanced genetics tell us that the evolutionary period from ape to man is only 120 years old.                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//    That is, in this short time of more than 120 years, the eruption of the potential of the ancient ape directly completed all the basic conditions for the evolution of human beings; Everything in the human genome, from the oldest single-celled organisms to the present human genome, has been shown in genetic decoding, and finally to the present human genome.    //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract WEP is ERC721Creator {
    constructor() ERC721Creator("Wisdom? Experience!", "WEP") {}
}
