
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The Wolf king was released from prison and killed on the spot
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    The iron gate of quancheng fourth prison opened slowly.                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    "Quick!"                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    "Surround!                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    Dozens of burly men who had been waiting in the square outside immediately rushed up and surrounded the iron gate.                                                                                                                                                 //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    Today, an ex-con came out of jail.                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    The prisoner walking in front was dumbfounded.                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    What's going on?                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    Dozens of burly men in uniform black suits stood with their hands clasped and their faces grim, clearly not good.                                                                                                                                                  //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    The first was a young man.                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    The young man was holding a photo and comparing it with the prisoners one by one, as if he was looking for someone. This made the prisoners sweat on their foreheads and wondered, "Are there enemies of these people among the people who came out with them?"    //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    It's bad luck to be revenged as soon as you get out of prison!                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    So each ran faster than the other.                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    In two minutes.                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    The first seven prisoners left one after another, and Xiao Zhan was the last one out of the prison. He closed the iron gate and scanned the scene outside. His face was as flat as water and he asked, "Are you looking for me?                                    //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//    "Young master!                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TWKWR is ERC721Creator {
    constructor() ERC721Creator("The Wolf king was released from prison and killed on the spot", "TWKWR") {}
}
