
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Some girls elegance
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//    When Xiao Ying was alive, Xiao Lie in the status of xiao door can be said to be no one, even then the owner of the house is very respectful to him. The reason is very obvious, that is xiao Ying's amazing talent is destined to him in the future must be xiao Men that generation of the strongest, in the world with xuanli respect, as xiao Ying's father Xiao Lie nature is respected by xiao Men. But Xiao Ying was assassinated and died, Xiao Lie's only grandson Xiao Che is a mystery disabled, Although Xiao Lie is currently the city of clouds the first strong, but the son died, grandson disabled, no successor, who will fear him? His position in the xiao Gate also plummeted.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//    Xiao Lie did not get angry, he usually has long been accustomed to these people's cynicism, indifferent smile, way: "Thank you for coming to the banquet must drink a few cups."                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SGE is ERC721Creator {
    constructor() ERC721Creator("Some girls elegance", "SGE") {}
}
