// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Peter Pan; or the Boy Who Wouldn't Grow Up
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   dddddddd                  ''''''                                                                                                                                                                              //
//    PPPPPPPPPPPPPPPPP                              tttt                                                       PPPPPPPPPPPPPPPPP                                                                                                     tttt         hhhhhhh                                      BBBBBBBBBBBBBBBBB                                                WWWWWWWW                           WWWWWWWWhhhhhhh                                   WWWWWWWW                           WWWWWWWW                                lllllll             d::::::d                  '::::'         tttt                       GGGGGGGGGGGGG                                                                                 UUUUUUUU     UUUUUUUU                       //
//    P::::::::::::::::P                          ttt:::t                                                       P::::::::::::::::P                                                                                                 ttt:::t         h:::::h                                      B::::::::::::::::B                                               W::::::W                           W::::::Wh:::::h                                   W::::::W                           W::::::W                                l:::::l             d::::::d                  '::::'      ttt:::t                    GGG::::::::::::G                                                                                 U::::::U     U::::::U                       //
//    P::::::PPPPPP:::::P                         t:::::t                                                       P::::::PPPPPP:::::P                                                                                                t:::::t         h:::::h                                      B::::::BBBBBB:::::B                                              W::::::W                           W::::::Wh:::::h                                   W::::::W                           W::::::W                                l:::::l             d::::::d                  ':::''      t:::::t                  GG:::::::::::::::G                                                                                 U::::::U     U::::::U                       //
//    PP:::::P     P:::::P                        t:::::t                                                       PP:::::P     P:::::P                                                                                               t:::::t         h:::::h                                      BB:::::B     B:::::B                                             W::::::W                           W::::::Wh:::::h                                   W::::::W                           W::::::W                                l:::::l             d:::::d                  ':::'        t:::::t                 G:::::GGGGGGGG::::G                                                                                 UU:::::U     U:::::UU                       //
//      P::::P     P:::::P  eeeeeeeeeeee    ttttttt:::::ttttttt        eeeeeeeeeeee    rrrrr   rrrrrrrrr          P::::P     P:::::Paaaaaaaaaaaaa  nnnn  nnnnnnnn                     ooooooooooo   rrrrr   rrrrrrrrr        ttttttt:::::ttttttt    h::::h hhhhh           eeeeeeeeeeee           B::::B     B:::::B   ooooooooooo yyyyyyy           yyyyyyy      W:::::W           WWWWW           W:::::W  h::::h hhhhh          ooooooooooo         W:::::W           WWWWW           W:::::W ooooooooooo   uuuuuu    uuuuuu   l::::l     ddddddddd:::::dnnnn  nnnnnnnn    ''''   ttttttt:::::ttttttt          G:::::G       GGGGGGrrrrr   rrrrrrrrr      ooooooooooo wwwwwww           wwwww           wwwwwww      U:::::U     U:::::Uppppp   ppppppppp       //
//      P::::P     P:::::Pee::::::::::::ee  t:::::::::::::::::t      ee::::::::::::ee  r::::rrr:::::::::r         P::::P     P:::::Pa::::::::::::a n:::nn::::::::nn    ;;;;;;       oo:::::::::::oo r::::rrr:::::::::r       t:::::::::::::::::t    h::::hh:::::hhh      ee::::::::::::ee         B::::B     B:::::B oo:::::::::::ooy:::::y         y:::::y        W:::::W         W:::::W         W:::::W   h::::hh:::::hhh     oo:::::::::::oo        W:::::W         W:::::W         W:::::Woo:::::::::::oo u::::u    u::::u   l::::l   dd::::::::::::::dn:::nn::::::::nn         t:::::::::::::::::t         G:::::G              r::::rrr:::::::::r   oo:::::::::::oow:::::w         w:::::w         w:::::w       U:::::D     D:::::Up::::ppp:::::::::p      //
//      P::::PPPPPP:::::Pe::::::eeeee:::::eet:::::::::::::::::t     e::::::eeeee:::::eer:::::::::::::::::r        P::::PPPPPP:::::P aaaaaaaaa:::::an::::::::::::::nn   ;::::;      o:::::::::::::::or:::::::::::::::::r      t:::::::::::::::::t    h::::::::::::::hh   e::::::eeeee:::::ee       B::::BBBBBB:::::B o:::::::::::::::oy:::::y       y:::::y          W:::::W       W:::::::W       W:::::W    h::::::::::::::hh  o:::::::::::::::o        W:::::W       W:::::::W       W:::::Wo:::::::::::::::ou::::u    u::::u   l::::l  d::::::::::::::::dn::::::::::::::nn        t:::::::::::::::::t         G:::::G              r:::::::::::::::::r o:::::::::::::::ow:::::w       w:::::::w       w:::::w        U:::::D     D:::::Up:::::::::::::::::p     //
//      P:::::::::::::PPe::::::e     e:::::etttttt:::::::tttttt    e::::::e     e:::::err::::::rrrrr::::::r       P:::::::::::::PP           a::::ann:::::::::::::::n  ;;;;;;      o:::::ooooo:::::orr::::::rrrrr::::::r     tttttt:::::::tttttt    h:::::::hhh::::::h e::::::e     e:::::e       B:::::::::::::BB  o:::::ooooo:::::o y:::::y     y:::::y            W:::::W     W:::::::::W     W:::::W     h:::::::hhh::::::h o:::::ooooo:::::o         W:::::W     W:::::::::W     W:::::W o:::::ooooo:::::ou::::u    u::::u   l::::l d:::::::ddddd:::::dnn:::::::::::::::n       tttttt:::::::tttttt         G:::::G    GGGGGGGGGGrr::::::rrrrr::::::ro:::::ooooo:::::o w:::::w     w:::::::::w     w:::::w         U:::::D     D:::::Upp::::::ppppp::::::p    //
//      P::::PPPPPPPPP  e:::::::eeeee::::::e      t:::::t          e:::::::eeeee::::::e r:::::r     r:::::r       P::::PPPPPPPPP      aaaaaaa:::::a  n:::::nnnn:::::n              o::::o     o::::o r:::::r     r:::::r           t:::::t          h::::::h   h::::::he:::::::eeeee::::::e       B::::BBBBBB:::::B o::::o     o::::o  y:::::y   y:::::y              W:::::W   W:::::W:::::W   W:::::W      h::::::h   h::::::ho::::o     o::::o          W:::::W   W:::::W:::::W   W:::::W  o::::o     o::::ou::::u    u::::u   l::::l d::::::d    d:::::d  n:::::nnnn:::::n             t:::::t               G:::::G    G::::::::G r:::::r     r:::::ro::::o     o::::o  w:::::w   w:::::w:::::w   w:::::w          U:::::D     D:::::U p:::::p     p:::::p    //
//      P::::P          e:::::::::::::::::e       t:::::t          e:::::::::::::::::e  r:::::r     rrrrrrr       P::::P            aa::::::::::::a  n::::n    n::::n              o::::o     o::::o r:::::r     rrrrrrr           t:::::t          h:::::h     h:::::he:::::::::::::::::e        B::::B     B:::::Bo::::o     o::::o   y:::::y y:::::y                W:::::W W:::::W W:::::W W:::::W       h:::::h     h:::::ho::::o     o::::o           W:::::W W:::::W W:::::W W:::::W   o::::o     o::::ou::::u    u::::u   l::::l d:::::d     d:::::d  n::::n    n::::n             t:::::t               G:::::G    GGGGG::::G r:::::r     rrrrrrro::::o     o::::o   w:::::w w:::::w w:::::w w:::::w           U:::::D     D:::::U p:::::p     p:::::p    //
//      P::::P          e::::::eeeeeeeeeee        t:::::t          e::::::eeeeeeeeeee   r:::::r                   P::::P           a::::aaaa::::::a  n::::n    n::::n              o::::o     o::::o r:::::r                       t:::::t          h:::::h     h:::::he::::::eeeeeeeeeee         B::::B     B:::::Bo::::o     o::::o    y:::::y:::::y                  W:::::W:::::W   W:::::W:::::W        h:::::h     h:::::ho::::o     o::::o            W:::::W:::::W   W:::::W:::::W    o::::o     o::::ou::::u    u::::u   l::::l d:::::d     d:::::d  n::::n    n::::n             t:::::t               G:::::G        G::::G r:::::r            o::::o     o::::o    w:::::w:::::w   w:::::w:::::w            U:::::D     D:::::U p:::::p     p:::::p    //
//      P::::P          e:::::::e                 t:::::t    tttttte:::::::e            r:::::r                   P::::P          a::::a    a:::::a  n::::n    n::::n  ;;;;;;      o::::o     o::::o r:::::r                       t:::::t    tttttth:::::h     h:::::he:::::::e                  B::::B     B:::::Bo::::o     o::::o     y:::::::::y                    W:::::::::W     W:::::::::W         h:::::h     h:::::ho::::o     o::::o             W:::::::::W     W:::::::::W     o::::o     o::::ou:::::uuuu:::::u   l::::l d:::::d     d:::::d  n::::n    n::::n             t:::::t    tttttt      G:::::G       G::::G r:::::r            o::::o     o::::o     w:::::::::w     w:::::::::w             U::::::U   U::::::U p:::::p    p::::::p    //
//    PP::::::PP        e::::::::e                t::::::tttt:::::te::::::::e           r:::::r                 PP::::::PP        a::::a    a:::::a  n::::n    n::::n  ;::::;      o:::::ooooo:::::o r:::::r                       t::::::tttt:::::th:::::h     h:::::he::::::::e               BB:::::BBBBBB::::::Bo:::::ooooo:::::o      y:::::::y                      W:::::::W       W:::::::W          h:::::h     h:::::ho:::::ooooo:::::o              W:::::::W       W:::::::W      o:::::ooooo:::::ou:::::::::::::::uul::::::ld::::::ddddd::::::dd n::::n    n::::n             t::::::tttt:::::t       G:::::GGGGGGGG::::G r:::::r            o:::::ooooo:::::o      w:::::::w       w:::::::w              U:::::::UUU:::::::U p:::::ppppp:::::::p    //
//    P::::::::P         e::::::::eeeeeeee        tt::::::::::::::t e::::::::eeeeeeee   r:::::r                 P::::::::P        a:::::aaaa::::::a  n::::n    n::::n  ;:::;;      o:::::::::::::::o r:::::r                       tt::::::::::::::th:::::h     h:::::h e::::::::eeeeeeee       B:::::::::::::::::B o:::::::::::::::o       y:::::y                        W:::::W         W:::::W           h:::::h     h:::::ho:::::::::::::::o               W:::::W         W:::::W       o:::::::::::::::o u:::::::::::::::ul::::::l d:::::::::::::::::d n::::n    n::::n             tt::::::::::::::t        GG:::::::::::::::G r:::::r            o:::::::::::::::o       w:::::w         w:::::w                UU:::::::::::::UU  p::::::::::::::::p     //
//    P::::::::P          ee:::::::::::::e          tt:::::::::::tt  ee:::::::::::::e   r:::::r                 P::::::::P         a::::::::::aa:::a n::::n    n::::n ;:::;         oo:::::::::::oo  r:::::r                         tt:::::::::::tth:::::h     h:::::h  ee:::::::::::::e       B::::::::::::::::B   oo:::::::::::oo       y:::::y                          W:::W           W:::W            h:::::h     h:::::h oo:::::::::::oo                 W:::W           W:::W         oo:::::::::::oo   uu::::::::uu:::ul::::::l  d:::::::::ddd::::d n::::n    n::::n               tt:::::::::::tt          GGG::::::GGG:::G r:::::r             oo:::::::::::oo         w:::w           w:::w                   UU:::::::::UU    p::::::::::::::pp      //
//    PPPPPPPPPP            eeeeeeeeeeeeee            ttttttttttt      eeeeeeeeeeeeee   rrrrrrr                 PPPPPPPPPP          aaaaaaaaaa  aaaa nnnnnn    nnnnnn ;;;;            ooooooooooo    rrrrrrr                           ttttttttttt  hhhhhhh     hhhhhhh    eeeeeeeeeeeeee       BBBBBBBBBBBBBBBBB      ooooooooooo        y:::::y                            WWW             WWW             hhhhhhh     hhhhhhh   ooooooooooo                    WWW             WWW            ooooooooooo       uuuuuuuu  uuuullllllll   ddddddddd   ddddd nnnnnn    nnnnnn                 ttttttttttt               GGGGGG   GGGG rrrrrrr               ooooooooooo            www             www                      UUUUUUUUU      p::::::pppppppp        //
//                                                                                                                                                                                                                                                                                                                                       y:::::y                                                                                                                                                                                                                                                                                                                                                                                            p:::::p                //
//                                                                                                                                                                                                                                                                                                                                      y:::::y                                                                                                                                                                                                                                                                                                                                                                                             p:::::p                //
//                                                                                                                                                                                                                                                                                                                                     y:::::y                                                                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PP is ERC1155Creator {
    constructor() ERC1155Creator("Peter Pan; or the Boy Who Wouldn't Grow Up", "PP") {}
}
