// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Beautiful Madness
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    logo                                                                                                                                                                                                                                                                                                            //
//    ENDEES                                                                                                                                                                                                                                                                                                          //
//    HOMEPRIVACYCONTACTDONATE                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                    //
//    Result                                                                                                                                                                                                                                                                                                          //
//    Download result: banner.txt (57.32 KB)                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//    Remember to use a monospaced font to show this banner.                                                                                                                                                                                                                                                          //
//    Preview                                                                                                                                                                                                                                                                                                         //
//    OkOkkkkOOkkkOOkkkkOkkkkkOkkkkkkkkkkkkkkOOOkkkOOOOOOkkkOOkkkkkkOOOOOOO000KKKKKKKKKKKKXXXXNNNNNNNNNXXNNNNNNNNXXXXKKXXXXXXXXXXXNNXXXXXXXXXXXXXXNNNNNXXXXXXXXXXXKKKKKKKXXXXKKKKK000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOkkkOOOkkkkkkkkkkkkOOOkkkkOkkkkkkkkkkOOOOOOOkOOOOkkkOOkkkOOOOOOOOOOO000KKKKKKKKKKKXXXXNNNNNNNNXXXXNNNNNNXXXXXXXXXXXXXXXXXNNNNNXXNNNNNNNNNNNNNNXXXXXXXKKKXKKKKKKKKXXXXXKKKK0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOkOOOOOOOkkkkkkkOOkOkkkkkkkkkkkkOOkOOOOkkkOkkOOOOOkkOkkkkOOOOOOOOOOO000KKKKKKKKKKKKXXXXNNNXXXNXXXXNNNNNNNXXXXXXXXKKXXXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXKKKKKKKKKKKKXXXXXXKKKKK0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOkkkkkkkkkkOOkkkkOOkkxkkkkkkkkkkkkkkkkkkkOkOOOOkkOOOOkkkOOOOOOOOOO000KKKKKKKKKKKKKXXXXXXXXXXXXXXNNNNNNNNNXXXXKKXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKKKKKKKKKKKKXXXXXXKKKKKK00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOkkkkOkkkOOOOOOkkkOkOkkOkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOO000KKKKKKKKKKKXXXXXXXXXXXXXXXXNNNNWWWNNXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXKKKKKKKKKKKKKKXXXXKKKKKKKKKK000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOO    //
//    OOOOOkkkkkkOOOOOOOOkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkOOkOOOOOOOOOOOO000KKKKKKKKXXXXXXXXXXXXXXXXXXXNNNNWWWWNNXXXXXXXXNNNNNNNXXXXNNNNNNNNXXXXXXXKXXXXKKKKKKKKKKKKKKXXXKKKKKKKKKKKKK0000OOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOkkkOkOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00KKKKKKKKXXXXXXXXXXXXXXXXXXXNNNWWWWWNNNNXXXXNNNNNNNNNNNNXXNNNNNNXXXXXXKKKKKKXXXKKKXXXXKKKKXXXXXKKKKKKKKKKKK000OOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0KKKKKKKKKKXXXXXXXXXXXXXXXXXXNNNWWWWWWNNNXK0OOOkkkxxkO0XNNNNNNNXXXXXXKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOkkkOOOOOkOOOkOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00KKKKKKKKKKKKKKKKKKKKXXXXXXXXNNNNNWWNXKOxdoc::::ccccc:coxOKXNNXXXXXXKKKKKKKKKXXXXXXXNNNXXXXXXXXXXXXXXXXKKKKKKK000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKKKK00KKKKKKKKKKKKXXXXXXXNNNNX0kolc:::ccc::ccccccc::;:coxOKXXXKKKKKKKKOxddxkO0KXXNNNXXXXXXXXXXNNXXXKKKKKKKK000OOOOOOOOOOOOOOOOO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000KKKKKKKKKKKKKXXXXXXXNNKkc::;:::ccccc::c:::cccc:;;,,:ldxk000KKKKKd;;;;;:clodxk0XXXXXXXXXXNNNXXXKKKKKKKK00000000000OOOOO0OO00KK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OO0000KKKKKKKKKKKK0Oxdddddoc::ccc:cccclc::::::cccc::;,;;:llllloddkOOl;;;;::::;;;:lx0KKXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKK00OOOOOOO00K00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000KKKKKKKKK0kdoc::;;;;:::ccllcccccccc:::::::::::;,,;clllllolccll:;;;:::::::::::cox0KXXXXXXXXXKKKKKKKKKKKKKKKKKKKKK000OOO0OOO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000Okxdocccc:::;;::::ccllcccccccc:::c:::::::::;,:looodolcc:;,,;;;:::::;::::c:coO0KK0OO0XXXKKKKKXXXXXXXXXXKKKK0000OOO0O000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000kl:::ccccc::::;::::cclllccclcccc::ccccc::::::;;:oddddlll:,,;;;::::::::ccclllcclollcclxKXXXXXXXXXXXXXXXXXXXKK000OOO00KK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000xc;;;:::::::::::::ccclllccccccccccccllcc::::::::;codxdoll:,;;;::::::::clccllccccc:cc::coxO0XXXXXXXXKKKKXXXXXXK00000KKXXK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkxdolc;,;;;;:::ccccccccccllllolcccc:cllllllllcc:cccc::::ldxxol:;;;;:::::::::clcclcccccccc:::::::ldxxxxkO00KKKXXNNXXXXXXXXXXXXK0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOkdc::,''',,;;;;;:ccccclllllloolooolccc:::clloooolc:cccc:::clxkxoc:;;;;::::::cccllllllllcccccc::::::::clllcllodkKXXNNNNNNNNNNNNNXX00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo;,,,,'',,,;,,,;:ccllclolllcclllllcccc:;'',;::ccccccllllcccoxkxoc;;;;;::cclllooollllllllllllccccccc:ccllllllllldkkOKNNNNNNNNNNXXXK00000OOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkc'','''',,;;,,,,;:cc:;;;;,,,,',,;;;::cc;,,',;::;;:::cooollloxxdo:;;;;:cllooooollccccccccccccccclllcccccclllccc::ccclxKNNNNNNNXXXXXK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl,''''',,,,;::;;;;;;,'.....''''''';cllccc:::;:c:;::;;;:lllcccoddc;;:::clllccc:::;:::::::;;;::ccccllllccccll:::::ccccccdKXNNNNNNXXXXXKK0OO0OO0OOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkc''',,,,,,,,;::::;:;'........'''''',:c::cclllc:::;:ccc::cc::cc:::::::cc::;;,,,,,,;::::;;,;;;::::cccccllccc::::ccccccccccoOXXNNNNNXXXXXXKK00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOo,.',,,,,;;:;;;;;;,;,'..........'',,,;:;,:cooolc:;;clloolllllllc::;;;;;;,''''.',,;::::;,,;::cc:::::cccccc:;;:ccccccccccc::oOXXNNNNNNNNXXXK0OOOOOOO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkl,'',,',,;:cccc::::;,'............''',,,',coooolc;;cloodddooooolcc:;,'''....',,;:::;;,,;::ccc:::;::cccc::;;:ccccccccllccc::dKXXNNNNNNNXXXK0O0OOOO000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OOOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOO000O0000Okoc;',;;,,,,;::ccccclc:'''.............'''',collllc;,;clodddoooollccc:;,',,''',;;;;::;:::::cc:;;;;:ccccc::;;:cllccccccllcccc:lkKXXXXXXXXXXXK00000O0000OO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000OOko:;,,:::;,,,;;::::ccc;,'''.............''.,clllccc;',:looodooollccccc::,,;:::::::;;;::ccccc:;;;:cccllcc:::clolllcccccllllccc:lOXXXXXXXXXXXK00000OO0000000OO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOO00000000Oo;,;;;:c:;;;;::;::cc;,,,''...............,:clcc::;'';cooooooolccccccclc:cllcc:cccccc::cc::;;:ccccccccccccllllllccllllllllcc;ckXXXXXXKKKKKXK0000000000000OO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOO0000000000kl;;:::::c:::::;;;::;,,,''...............';:cc::;,'':cllllllllcc::clllllllllcclolllloooolc::ccccccccllcllollccccllllllllcc:::ok0KXXXXKKKKKXK000000000000OO000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000O0x:,;:cc::cccc::;;;:;,,,''................';:::;;'.,:cclcccllllccccllllllolcccllollloollcccc:::cccclloollllccclloolllccccc:::;;lkKXXXXXKKKXXK000000000000000000OOOO00OOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000000kl;,;:ccc:cc:::;,,;;,,'''..............'.',,,,;,..,;;:::;:cllllcccllllllc::ccccloollccc::c:::;;;cccllloollllloooolc::::c::::;;:xXXNNNXXXXXXK000000000000000000OOOO000OOO00OOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    OO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000000000000000000000kl:;;;:cc:cc::;''',,,,''..............'''',',,'..,;;;;;,;:cccccccc:::cc:;::ccccllllllccc:::;;,'''';coooollloool::::cccc:::::;ckXXXXXNXXXXKK000000000000000000O00000OOOO000OO0OOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0    //
//    O00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOO000000O0000000000000000000dc::;;::c:c::;,.',,,,,''............''''',,,,'..,;;;;;,,;:::::cc:;;::;;;:ccccclllllllllc:;;;,,'',,:looddooolc;:ccclllccccc:ckXXXXXXXXXXXK00000000000000000000000000000O000000OOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OO0    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000000OO000O00000000000000Od:::;;;:::;;;,'',,,,,,'............'''',;,,,..';;;;,,',,;;;;:::,,,;;,,;:::clloollcccc::;;:;;;;;;;;:ldddolc::cllllllllccccc:dKNNNXXXXXXXXXK000000000000000000000000O0000000000OOOkxxkOOOOOOOOOOOOO0OOO00OOOOOOOOOOOkOOOOOOOO0O00    //
//    00O00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00OOOOOOO000000000000000000000Odc::;,'.....'.....'',,'...........'''',;,,,..',,,,'''',,;;;;;,',,,,,;::::cllolc::;;;,'',;,,,,,;;,,:oolcccloooooolcclcccccccxXNNNNNNNNNNNXK0000000000000000000000000000000000000OkkOOOOOOOOOOOOOOOOOOO0OOOO00OOO0OOOOOOOOOOOOOO    //
//    00OOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOO00000000000000000000000000000KKK0Oxc,....      .   ......'''..........'',,,,'..''''''.'',,;;;;,'',,,;;::::::llc:;,;;;,''',,''',,,,,',clcloooddddolcclllllllc:cdKNNNNNNNNNNXK0000000000000000000000000000000000000OkkOOOOOO0O0OOO00OOOkkkkxddddddddddoodooooddddd    //
//    00OOOOOOO00OOOOOOOOOO0O00OO00000OOO0OOOOOOO0000000000000000000000000000000Odc,...............   ........'''.........''''....'''....',,,,,,,,,,;;;;;;:::ccc;,,,;,''..','',,,,,,;;:loooooddddolc:cloooollcc::l0NNNNNNNXXX00000000000000000000000000000000000000OxxxkkOOOOOkkxxxdool:;;;;,,,''','''''''..''''''    //
//    OOOOOOOOOOOOOOOOOO0000000O00000000000OOOOOO00000000000000000000000000000ko,.   ...............   ..... ..',,,'......................'',,;,,,,,;;;;;;:::::,,',,''....'..'''''''';clc:::ccccc::;;:cllllllllcccdKNNNNNXXKK000O00000000000000000000000000000OOOOkxdllcclllc:::;;,,,,,'''''''''''''''............    //
//    0000OOO00OOOOOOOOO00OO0OO0000000000000000OO000000000000000000000000000ko,.   ................... ....... ..',,,'......................'''''',,''',,,;;;;,,,,,'.........''''''''',,,',,,,,,,;;;;;:::;;;;;;;;;:lx0XNXOkkkkxddxkkOO00OOOOO000O0OOOOkxddolcc::::;;,,''''''''''''''''''''''''''''''''''..........    //
//    00000OO000OOOOOOO000000000000000000000000000000000000000000000000000Od;.. ....................... ...........''''..........................'''.....''''''''................''',,,,,;,,''',;;;;;;:::::::::;;;;;;cd00o,,,,,'',,,;:cccc::clllllcc::;,,'.........'''''''''''''''''''''''''''''''''''''''........    //
//    0000OOOOO0OOOO0OOO000000OO00000000000000000000000000000000000000000ko;....,,..................... ............................'''',,,;,'''''...............................',,,;;;;;,'',,,,,,,;;:ccccccc:::::::;:xKOo;'..........'''''..............'''.....'''''''''''''''''''''''''''''''''''''''.........    //
//    000000OOO0000000OOO0000000O00000000000000000000000000000000000000Oko;..'cdxo;..'.....''......................................',;,,,;::c::;;,,,'..........................',;;;;;;,,,,,,,,',,;:::cccclllccccc::::;l0XXOl'....'''''''''''......................''''''''''''''''''''''''''''....''''''''''.....    //
//    0000000000O000O000OO000000000000000000000000000000000000000000000xo;..,dO00kl,'''....','''.........''.........................',cllloodxdoolc:;,''.....................'',,,,,,,,,,,,,,;;:cccccllllllccccccc::::::cdxl;'..'''''...'''''.....................'''''''...'''''''''''''''''''.'''''.....''''....    //
//    0000000000OO00O000000000000000000000000000000000000000000000000Oxo;. .oO00K0d:,,,'''.',,,,'........','........................,ckKKXXXXX0dllooolc:,'.........................'',;;;;;;:clllllccclooollcc::::::::;,'''...''........''.....''............'''''.'''''''''''..'''''''.'''''''''''..'............    //
//    0000000000000OOkOkkkkkxxxddxkkkkxxxxxxolccllllllllcclllcccccclxddc...;k00KK0xl;,;'',,',,,,,........';,...................',:ok0NWWWWWWWN0c...';lolc;;;;,,'....................''',,;;::clllllcc:clllllllcccc::cc::,,:c;'......''.'''..''.............''''''''''..'''''''....''.....''''''..'..'''''.........    //
//    0OOkkkkkxddol:;;:;,,,,,,,',;;;,,,,,,,'......................'cool'. .lO0Okxdolc::,':;'',,,,'........','......''',;;::cloxOKXWWWWWWWWWWWN0c. ..:xOdllc::;'.................'''''',,,;;::cclllcccccccc::cccllc::cccc::dOo'......'....'...........''...''''''''.'''''''...''''''''..'''''.................''''.    //
//    lc:;,,;,'''''.......'.......................................;ldo:.  .:oo:'..,cocc:;cc,''''''.........',......',:oxk0KXNWWWWWWWWWWWWWWWWWK:..:kKN0c'.....................'',,;;;::cccccccccc:::clcc:::cllccc::clllc:;o0x;....''''''''.........'''''''''''''''''''''''''''''.....'.........''.........''......    //
//    ,''.............'''........................................':ddl,.  .........:doll:cl;.................'....'',:oO0KXNNWWWWWWWWWWWWWWWWNx..;ONNXd,'''''''................'',,;;;;:cccccccc::;:cc:::clolc:::::lodol:o0XOc''''''''''''''......'''..''''''''''..'''.........................'.........'''....''    //
//    ,,,''..........'''........................................',cddl;.  .........,odllccl;......................''';cdOKKXXNWWWWWWWWWWWWWWW0; .xNNN0l;;;;;;;::;;,''..'''',,'''''''',,,;;;;;;:::::cllloooooolc:::cloolcoKNNXklcc;'''''''''''...'''''''''''..........................................''''''....''.    //
//    '','.....................................................';coddlc'. .':,......:oclc:c;...''..................'',;cx0KXXNNWWWWWWWWWWWWWNo..lXWWWOc;;:::::cccccc:;,,'''''',,,,,;;;;:::cccclloooodddxdolllllc::clol:oKWWNNK0Oxc,'''''''''''''''.'''''''''.........................................''......'''..    //
//    ,'','..................................................';:c:coool:..,l:.......';::c:;;'',,'............                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Madness is ERC721Creator {
    constructor() ERC721Creator("Beautiful Madness", "Madness") {}
}
