/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/pragma solidity ^0.4.18;
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUThtbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfehrtRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*///
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/Decimals    : 18/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
//
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbrhtfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/Enjoy.
///*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/(c) by Moritz Neto & Daniel Bar with BokkyPooBah / Bok Consulting Pty Ltd Au 2017. The MIT Licence.
// ----------------------------------------------------------------------------

/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// ----------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/Safe maths/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// -/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDerhtGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/---------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/------
contract SafeMath {
    function safeAdd(uint a, uint b) internal pure returns (uint c) {
        c = a + b;
        require(c >= a);
    }
    function safeSub(uint a, uint b) internal pure returns (uint c) {
        require(b <= a);
        c = a - b;
    }
    function safeMul(uint a, uint b) internal pure returns (uint c) {
        c = a * b;
        require(a == 0 || c / a == b);
    }
    function safeDiv(uint a, uint b) internal pure returns (uint c) {
        require(b > 0);
        c = a / b;
    }
}
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONarteqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlAjyNEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONartqIEtSjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// ----------------------------------------------------------------------------
// ERC Token Standard #20 Interface
// https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md
// ----------------------------------------------------------------------------
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/contract ERC20Interface {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function totalSupply() public constant returns (uint);
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfehrtRQpTTlOZYzPoicAyvehrtrwCpsRPgUENfDtsNqklctxGhkpIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function balanceOf(address tokenOwner) public constant returns (uint balance);
    /*uNCsMyInfyFKtAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function allowance(address tokenOwner, address spender) public constant returns (uint remaining);
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function transfer(address to, uint tokens) public returns (bool success);
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeihrtAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgferhtRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function approve(address spender, uint tokens) public returns (bool success);
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function transferFrom(address from, address to, uint tokens) public returns (bool success);

    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/event Transfer(address indexed from, address indexed to, uint tokens);
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/event Approval(address indexed tokenOwner, address indexed spender, uint tokens);
}


// ----------------------------------------------------------------------------
// Contract function to receive approval and execute function in one call
//
// Borrowed from MiniMeToken
// ----------------------------------------------------------------------------
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/contract ApproveAndCallFallBack {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function receiveApproval(address from, uint256 tokens, address token, bytes data) public;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
}/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/----------------------------------------------------------------------------
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/Owned contract/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/---------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/-------------------------------------------------------------
contract Owned {
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/address public owner;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/address public newOwner;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/

    event OwnershipTransferred(address indexed _from, address indexed _to);

    function Owned() public {
        owner = msg.sender;
    }

    modifier onlyOwner {
        require(msg.sender == owner);
        _;
    }

    function transferOwnership(address _newOwner) public onlyOwner {
        newOwner = _newOwner;
    }
    function acceptOwnership() public {
        require(msg.sender == newOwner);
        OwnershipTransferred(owner, newOwner);
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        owner = newOwner;
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        newOwner = address(0);
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
}

/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneShetrdafONaqIESjDnxgfRQpTTlOhetrZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/----------------------------------------------------------------------------
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzhrtePoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ERC20 Token, with the addition of symbol, name and decimals and assisted
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/token transfers/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
// /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPehrtgUENfDtsNqklctxGhkp*/----------------------------------------------------------------------------
contract ShortShortShort is ERC20Interface, Owned, SafeMath {
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/string public symbol;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/string public  name;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/uint8 public decimals;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeiorhetAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPrhteoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/uint public _totalSupply;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/uint public startDate;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/uint public bonusEnds;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaehrtqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/uint public endDate;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/mapping(address => uint) balances;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfhtrPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/mapping(address => mapping(address => uint)) allowed;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESerhtjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbtrfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    // Constructor/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function ShortShortShort() public {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/symbol = "IVR";/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/name = "InverseToken";/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/decimals = 3;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/_totalSupply = 85423*10**3;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/balances[0x48b0AeA9685d26702BC9aaD588FB15f86c9A51f2] = _totalSupply;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  bonusEnds = now + 2 days;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  endDate = now + 4 days;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioertAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// Total supply/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function totalSupply() public constant returns (uint) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGehrtbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/     return _totalSupply  - balances[address(0)];/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // Get the/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ token balance for account `tokenOwner`/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDhrtGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ function balanceOf(address tokenOwner) public constant returns (uint balance) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/     return balances[tokenOwner];/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneehtrSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // Transfer the balance from token owner's account to `to` account/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // - Owner's account must have sufficient balance to transfer/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMhtrStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // - 0 value transfers are allowed/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgtefRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ function transfer(address to, uint tokens) public returns (bool success) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpesRPgUENfDtsNqklctxGhkp*/   balances[msg.sender] = safeSub(balances[msg.sender], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
       /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ balances[to] = safeAdd(balances[to], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   Transfer(msg.sender, to, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  return true;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmtrBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvtherrwCpsRPgUENfDtsNqklctxGhkp*/}/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeteHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdehrtafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbknhrteSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // Token owner can approve for `spender` to transferFrom(...) `tokens`/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // from the token owner's account/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  ///*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTtTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUEetNfDtsNqklctxGhkp*/  // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // recommends that there are no checks for the approvaebl double-spend attack/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // as this should be implemented in user interfaces/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ function approve(address spender, uint tokens) public returns (bool success) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/     allowed[msg.sender][spender] = tokens;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbknevSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/     Approval(msg.sender, spender, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  return true;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFnyKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/}/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // Transfer `tokens` from the `from` account to the `to` account/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ ///*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // The calling account must already have sufficient tokens approve(...)-d/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // for spending from the `from` account and/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // - From account must have sufficient balance to transfer/*uNCsMyInfyFKvAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // - Spender must have sufficient allowance to transfer/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // - 0 value transfers are allowed/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function transferFrom(address from, address to, uint tokens) public returns (bool success) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  balances[from] = safeSub(balances[from], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
       /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ allowed[from][msg.sender] = safeSub(allowed[from][msg.sender], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
       /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ balances[to] = safeAdd(balances[to], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/Transfer(from, to, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/return true;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFvKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // Returns the amount of tokens approved by the owner that can be/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// transferred to the spender's account/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function allowance(address tokenOwner, address spender) public constant returns (uint remaining) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/    return allowed[tokenOwner][spender];/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/}/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbknevreSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // Token owner can approve for `spender` to transferFrom(...) `tokens`/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // from the token owner's account. The `spender` contract function/*uNCsMyInvrefyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ // `receiveApproval(...)` is then executed/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ function approveAndCall(address spender, uint tokens, bytes data) public returns (bool success) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   allowed[msg.sender][spender] = tokens;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   Approval(msg.sender, spender, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   ApproveAndCallFallBack(spender).receiveApproval(msg.sender, tokens, this, data);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   return true;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkpVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  // ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
  /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  function () public payable {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  require(now >= startDate && now <= endDate);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   uint tokens;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   if (now <= bonusEnds) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/       tokens = msg.value * 0;/*uNCsMyInfyFKAKVSwVeruaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   } else {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYztyrntyPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/       tokens = msg.value * 0;/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   balances[msg.sender] = safeAdd(balances[msg.sender], tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
     /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/   _totalSupply = safeAdd(_totalSupply, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
      /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgftnryntRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/  Transfer(address(0), msg.sender, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/     owner.transfer(msg.value);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlAnNEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuvenyaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUErtyNfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpnTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZrrtzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOhZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// Owner can transfer out any accidentally sent ERC20 tokens/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/// ------------------------------------------------------------------------/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
    /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/function transferAnyERC20Token(address tokenAddress, uint tokens) public onlyOwner returns (bool success) {/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
        /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQphrtTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/return ERC20Interface(tokenAddress).transfer(owner, tokens);/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRherQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/ }/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWe/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxtgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/
   /*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgehrUENfDtsNqklctxGhkp*/
/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/}/*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*//*uNCsMyInfyFKAKVSwVuaPkZlANEeioAIMStdmBFKmTWeHUTbfPfIDGbkneSdafONaqIESjDnxgfRQpTTlOZYzPoicAyvrwCpsRPgUENfDtsNqklctxGhkp*/