// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Pigment TCG
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdl0NMMMMWX00000K000000000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK; ,0MMMNo.. .......     ..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWNX0Ok0NKdxNMMMk.                 .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWNX0Oxoc;'..  .lXMMMMMMk.                 .kMMMMMMMMMMNkc;cdOXWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMM0c,'..           .dWMMMMMk.       ...       .xMMMMMMMMMNo      .,cdkKNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMX:                 ;KMMMMMk.      ;0X0;      .xMMMMMMMMWd.           .':oONMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNc                 .dWMMMMk. 'xk,.dMMMd.,kk' .xMMMMMMMMk.                 cXMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMk.      ;l,   ..   ,KMMMMk. .xWK:oMMWo:KWx. .xMMMMMMM0'                  :XMMMMMMMMMM    //
//    MMMMMMMMN0XMMMMNc     'OMX:.lKx.   dWMMMk.  .:d;'dOd';d:.  .xMMMMMMX:  ..  .'.         .OMMMMMMMMMMM    //
//    MMMMMMMMKokWMMMMk. .co,lXMd'kWo    ;XMMMx.                 .kMMMMMNl  'Ox.'ONx.       .xWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMX:  cXK::0d.:o.    .kMMMk.                 .xMMMMWd.  :N0:xMNl.;oc.   lNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMx.  'o: ..         :NMM0'                 .kMMMMk.   .o:,kO:;kN0:   :XMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMX;                 .kMMX:                 .OMMMX;        .. :d:.   '0MMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMx.                 cNMM0lc:;;;;;;;;;;;:clOWMMWd.                 .OMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNc                .dWMMMMMMMMMMMMMMWWMMMMMMMMWd.                .xWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0'        .',:ldOXWMMMXdlkNMMMWW0l;;dNMMMMMMMW0xc'.            oNMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM0c:clodk0XNWMMMMMMMMWo   :KMM0o'    dMMMMMMMMMMMNKkdc'.      cXMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   :XMx'.    oWMMMMMMMMMMMMMMMWKOdl::dXMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWKkxkKWMMMMMMMMMMMW0:.  lNk:.   ,0MMMMMMMMMMMMMMN0kxOXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXd:;;;:d0WMMMMMMMMMMMNk, 'kkl'  :KWMMMMMMMMMMMMNOo:;;;lOWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMXo;;;;;,;:dKWMMMMWXOxl:;.  ...   .,;cok0NMMMMMNOl;;,;;;;cOWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMO:;;;.  .';ckWW0d;.                    .'cxXWXo;;.  .';;;oNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMM0c;;,.    .,:c;.                           .:c;,.    .;;;oXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWk:;;.                                               ';;cOWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMW0o:;'..                                         ..,;:dKWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMN0O0KOxoc;'.       .cd:.             .:dc.       .,:ldxO00OKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMKl;;:coxkkOl        oWMNc             cNMWo       .dxddoc:;;:kNMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWx;;;;;'..,l;       .dMMWl             lWMMd       .;;...,;;;;c0MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0c;;;'              'x0d.  .lc...cl.  .d0x'             .,;;;lKMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWOc;;;.                    .xXX0XXx.                   .';;;l0WMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMXOdl:;,''.                 ';:;'                 .'',;cldONMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWNXKKKKk'                                     :0KKKKXNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.                                   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.                                 'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;                              .cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.                         'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko'                   ,d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc.               .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o.               ;kXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,                    .:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,                       ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl                         lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.                         .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:                           :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.          .,:::,.          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.         ,OWMMMWO,         .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:.       dMMMMMMMd       .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:'.   :KWMMMWK:   .'cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOl. .:ccc:. .o0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d:,'.',cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PGMNT is ERC1155Creator {
    constructor() ERC1155Creator("Pigment TCG", "PGMNT") {}
}
