
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Star hidden grass
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//    Xiao Che said three things let the summer tilt month closed phoenix eyes immediately opened: "what do you want to do?"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//    "Do you really know how to get it?" See summer tilt month unexpectedly did not directly veto, Xiao Che immediately asked hopefully.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//    The summer tilts month slightly sink eyebrow, slowly say: "7 xuan linglong grass I have never heard of, the xuan Dan of the ground xuan beast needs to hunt the ground xuan beast to obtain, whole cang feng empire can hunt the ground xuan beast how many people again? Immortals must be rare, if they exist. And purple vein day crystal is no more money can not be bought, four large doors will be crazy heaven and earth treasure! If you get one, it's worth a dozen years of penance. These three things, let alone me, are almost impossible even for the master of the palace to possess at the same time."    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//    Xiao Che chest heavy ups and downs, and then closed his eyes, silent for a long time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SHG is ERC721Creator {
    constructor() ERC721Creator("Star hidden grass", "SHG") {}
}
