
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Shock from a distance
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    The sky is crimson.                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    Leisurely and come of an Ziqing, all over in light, release, dare not long to see the canran light.                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    That kind of light, just like the beauty of blood jade, natural charm shine.                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    The appearance is beautiful she, at this moment, like enveloped with a different kind of spirit.                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    All the people in the valley, with heavy hearts, also looked at her.                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    People are watching.                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "Originally, that morning, that scene, is not my illusion." Yuyuan heart bitter, recall that day yuan lotus Yao to the morning, he happened to see the scene                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    Seriously injured the ground regulus lotus Yao, also think of that day, before she left, the perception of an abnormal blood movement.                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    At that time, she also gave a little "eek".                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    However, even she did not think that the abnormal qi and blood came from a small servant girl near the yuyuan.                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    She only thought it was another member of the yu family who secretly practiced some secret sorcery.                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "When Yin jue came late at night, he blocked you with the force of ice. You turned into an ice sculpture. I thought you were unconscious." After being silent for a few seconds, Yuyuan said, "You saw everything then?"                                                                                                //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    An Ziqing chuckled as she walked, "I could see the power of my master at that time. I looked at the young master with poison Dan, so that Yin absolutely suffering. And looked at the young master, and covered his mouth, lest he should cry out. The young master at that moment was really adored by the slaves."    //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "I am very curious. With your realm and practice, why are you in yu's house?" YuYuan way.                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "Sorry, I can't answer this question." An zi Qing one face is embarrassed, "however, I to master you, more curious. I don't care how many people die in the dark Moon city, as long as my brother's Yin God can be smoothly condensed. As for you, master, maidservant is hope can continue to accompany."              //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "To continue?" Yuyuan pulled the corners of his mouth and said with a half-smile, "You might as well carry me off and take me with you."                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
//    "Master, I really think it's my honor to serve you." An ziqing a very sincere expression, "after you wake up, the future avenue can be. Only dark moon city, only yu house, will limit you. We blood god, is the master you better choice."                                                                             //
//                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SFAD is ERC721Creator {
    constructor() ERC721Creator("Shock from a distance", "SFAD") {}
}
