
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: A sword assembles
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Near the town, the monk let go of Ma Kuxuan's shoulder. Ma Kuxuan felt dizzy, shook her head and asked, "Do you know who is the problem? Isn't it my father or uncle who gives his treasure to outsiders? One is reluctant to give it to them, and the other is forced to ask for it. The result is almost as bad as Liu Xianyang, causing big trouble?"                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    Negative with bitter xuan ma jian men walk briskly, shake head a way: "is yangshan apes are outrageously to move mountain, do not hesitate to breaking the rules, by itself is valuable in part because of the sword, but the most important reason, is still the yangshan and fenglei garden old old rivalries, if not fenglei garden Chen Songfeng both feet came to town, the head move oreopithecus never as for crime. Therefore, even if practitioners in this town do not dare to act too openly, Mr. Qi, who is sitting here, after all..."    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//    The man suddenly stopped talking and looked up at a roof at the far end of the street. A wild cat, as black as ink, was squatting on a roof. When it saw Ma Kuxuan, it screamed.                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract ASA is ERC721Creator {
    constructor() ERC721Creator("A sword assembles", "ASA") {}
}
