
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Wedding night
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    Summer tilting month did not ask again, with this white woman's height and identity are so sure to say "impossible", that really should be a little possibility will not have.                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    "Lean Moon, I know you are eager to repay your kindness, and want to repay your birth as much as you can before you return to Immortals, but you married him, and that is enough. Upon your return to Immortals, your identity will be revealed. He may be mocked more in the future, but whatever the case, the identity of the disciple husband of Icunasgard is there. With this status, at least in this little city of clouds, no one would dare really harm him." "Said the woman in white soothingly.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//    Xia Leans month gently nod: "hope can be so."                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract WN is ERC721Creator {
    constructor() ERC721Creator("Wedding night", "WN") {}
}
