
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: sunrise
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    Town is modest, and more than six hundred households, the town portal from poor families, Chen Pingan know mostly, as for the background of substantial rich, high threshold, ni tuizai teenager can cross, some large cluster spacious alleyway, Chen Pingan didn't even set foot, on the other side of the street, many shop in large chunks of the green flag, rainy day, never stepped down mud flowed. The excellent quality of the blue SLATE, after thousands of years of vehicle trampling, has been smooth as a mirror.                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    The four surnames of Lu, Li, Zhao and Song were called da in this part of the town, and xiang Shu was their money. Most of them owned two or three large dragon kilns outside the town. The official residence of the kiln supervisors was on the same street as these families.                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    Unfortunately, Chen Ping 'an today to send ten letters, almost all of the town's famous rich households, this is also very reasonable, dragon born dragon born chicken chicken, mice born son hole, can send a letter home from afar, family must not be bad, otherwise there is no confidence to go on a long journey. Nine of the letters, Chen Pingan actually went to two places, Fulu Street and Peach leaf lane, when he first stepped on the big as a bed on the green SLATE, the young some uneasy, slowed down the pace, actually some ashamed, can not help but feel his sandals dirty street.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SI is ERC721Creator {
    constructor() ERC721Creator("sunrise", "SI") {}
}
