
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Ornamental Foundation
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                //
//                                                                                                //
//    BB88BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBORNBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTOBBBBBBBBBBB    //
//    BBBBBBBBBIBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBU!;+7Z#BBBBBBBBBBBBBBBBBBBBBBLOVEBBBBBBBB    //
//    BBBBBBBBBJUSTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB$T'           -1F#BBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBLOVEBBBBBBBBBBBBBBBBBBBBBBBBBBB$T      `*v"'          '!aBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBORNSBBBBBBBBBBBBBBBBBBBBBBBBNx      !GBBBBBBBBN9i"`       $BBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBa'     1pBBBBBBBBBBBBBBBBBNw!    NBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBb     _4BBBBORNITHINGBBBBBBBBBB/   1BBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB`   "NBBBBBBBBBBBBBBBBBBBBBBBBBN    4BBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBV    BBBBBBBBBBBBBBBBBBN$BBBBBBBB4    NBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBN    aBBBBBBBBBBBE>/      /BBBBBBBB"   1BBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBB8wfPBBBT   'BBBBBBBBBBBQ     '!1  kBBBBBBBH    MBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBDv;'      !    eBBBBBBBBBBBT  7BBBB$  ;BBBBBBBB"   *BBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBq?~                !XNBBBBBBBBB   NBBBW";?pBBBBBBBB>   ;BBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBN"      ~vPBBbI\-        'QBBBBBBk  _BBBBBBBBBBBBBBBW`   7BBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBB!    |qBBBBBBBBBBB$e1'    `NBBBBB?  _BBBBBBBBBBBBBM!   ;0BBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBB4   !BBBBBBBBBBBBBBBBBBBH'  `NBBBBQ'  '@BBBBBBBBBM!   `HBBBBBBB8ETHBBBBBBBBB    //
//    BBBBBBBBBBBB   `NBBBBORNIWHEREBBBBBBB$   'NBBBBB|   >I]A]Viv_       /#BBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBt   ABBBBBBBBBBBBBBBBBBBBBBG   "BBBBBBX            !o;     `eBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBN    BBBBBBBBBNf[vv[8BBBBBBBBT   /BB404BB$pPEGGkk9ENBBBBe-     |NBBBBBBBBBBBBB    //
//    BBBBBBBBBB>   7BBBBBBBBB!      NBBBBBBBN    @BBBBBBBBBBBBBBBBBBBBBBBN7     hBBBBBBBBBBBB    //
//    BBBBBBBBBB    MBBBBBBBBH   BBHJMBBBBBBBt   TBBBBBBBBLXCKBLLBBBBBBBBBBBBn   ,BBBBBBBBBBBB    //
//    BBBBBBBBBI   "BBBBBBBBB!  ;BBBBBBBBBBG    pBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    #BBBBBBBBBBB    //
//    BBBBBBBBB`   eBBBBBBBBB   ~5QBBBBBB0;   >NBBBBBBA'```''~~;"*7HBBBBBBBBBBT   *BBBBBBBBBBB    //
//    BBBBBBBBD    NBBBBBBBBN~      'vIG"   `pBBBBBBB1             ,BBBBBBBBBB@    BBBBBBBBBBB    //
//    BBBBBBBB>    BBBBBBBBBBBBN4T;`       }BBBBBBBB"  ~NBBBBBBBN   gBBBBBBBBBB    mBBBBBBBBBB    //
//    BBBBBBBB'    $BBBBBBBBBBBBBBBBB#A*"!MBBBBBBBBT  ~NBBBBBBBBB"  TBBBBBBBBBB"   1BBBBBBBBBB    //
//    BBBBBBBBT     `]NBBBBBBBBBBBBBBBBBBBBBBBBBBB1  `NBBBBBBBBBB8  `BBBBBBBBBB}    BBBBBBBBBB    //
//    BBBBBBBBBNI'     "wBBBBBBBBBBBBBBBBBBBBBBBBA   NBBBBBB;`{bi    BBBBBBBBBBm    QBBBBBBBBB    //
//    BBBBBBBBBBBB$T      |EBBBBBB88TO888BBBBBBBB_   HBBBBBBh     !5BBBBBBBBBBBN    eBBBBBBBBB    //
//    BBBBBBBBBBBBBBBW!    ` "fMBBBBBBBBBBBBBBBB$7    fBBBBBBBG#BBBBBBBBBBBBBBBa    ?BBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBK1`      "nMBBBBBBB@o|'        'gBBBBBBBBBBBBBBBBBBB0>      eBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBG"       ,!xT!`        `!?    ?NBBORNITIMEBBBBMt`     `ABBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBE"             `14$88BB0'    1MBBBBBBBBbt_       >MBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBG!    '"T4NBBBBBBBBBBB7     ;PBMF1`        *WBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB$_              !ZNBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBq`       'vEBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB5''!z$BBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB88BBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBOVERDREAMER88BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTOBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB888BBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//                                                                                                //
//                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////


contract ORN is ERC721Creator {
    constructor() ERC721Creator("Ornamental Foundation", "ORN") {}
}
