
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Higher up
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//    Choi, who had been sitting on the ground in a daze, 瀺 cast a slanting glance at the girl and the scroll and said, Even if the sky falls, this scroll will not be damaged at all. You know what the sky is falling? There was once an unknown man in The Middle Earth, who pierced the Sky river with a single sword, leading down an endless stream of water from the Yellow River. From a distance, it looked as if the sky had opened a big hole and water was pouring down.                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//    Only have produced the second ten views of the Yellow River water heaven, and is located in the treasure between clouds, treasure of the duke, that would be great, is one of the few dare to ruling as demons taught lean, romantic, I have had the privilege of handtalk, is in the clouds outside the treasure river, known as clouds, 10 bureau, lose much less, but the moment, After all, the flag that reads' Feng Rao Tian plays chess first 'has been erected at the head of the White Emperor City for more than 600 years, and there are only a handful of chess players who are qualified to compete with the master..."    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//    The little girl does not like to listen to these some have not of, angry way: "you say so much show off what, I say the scroll is broken is broken! If I win, let me put another stamp on your forehead with a stamp? Dare you bet? !"                                                                                                                                                                                                                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HHU is ERC721Creator {
    constructor() ERC721Creator("Higher up", "HHU") {}
}
