
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The magic son
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Wilderness road, white clouds leisurely.                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The end of the ancient road is a rolling mountains, from afar, see a peak, straight into the seven layers of clouds, and the day to meet!                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    On the ancient road, a thin man covered with blood, holding a baby in his arms, is struggling to run.                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The man while running, while also from time to time toward the back of the look, it seems that behind what fierce beast birds of prey in pursuit of him.                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    A moment later, behind him, a black streak of air appeared in midair, like a rolling black dragon, chasing him.                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The emaciated man's face changed suddenly at the sight of the dark air, and he drew from his back a small triangular flag with many inscriptions on it, the most striking of which was a bloody skull with black eyes that looked like a bottomless abyss.                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    When the man uttered the incantation, the red skull flag suddenly became larger against the wind, from the original two-foot flag, into a zhangyu flag in a blink of an eye.                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The man holds the red skull and crossbones flag in his hand, brandishing several times to the mass of black gas that gallops and comes, a moment of time, several blood manns burst out from the red skull and crossbones flag, in the shadow wind and the ghost whistles, that several blood manns fly toward the man behind the black gas that rolls and comes to meet.    //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Black qi and blood awn collided in mid-air, sending out a roar.                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Blood awn disappeared, black qi scattered.                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    After the black qi dispersed, there appeared a man in a black robe. His age looked about 50 years old. He was haunted by strange black qi all over his body.                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    There was some despair in the thin man's eyes when he saw the black-robed man.                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Even if he had not been injured, he would not have stood a chance against the black-robed man.                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Hanging in midair, the man in the black robe looked at the thin man on the ancient road and said with a smile on his face, "Blood slave, you can run quite well. For the sake of our friendship for a hundred years, hand over your baby and I will save your life. Otherwise, don't blame me for missing the friendship of the past."                                       //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    With a somber groan, he reached out and touched a mysterious ancient bracelet on his wrist, clumsy in shape but black throughout, as if it could devour a man's soul.                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The emaciated man named blood slave gave a sad smile, looked at the baby in his arms and said, "Soul eater, I died in your hands today. I was not killed by those despicable people. I am satisfied with my blood slave.                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    "Blood slave, why are you so foolishly loyal? The law of the jungle has always been the law of the jungle in holy religion for thousands of years. Your demon master is dead, the temple has been taken over by the Demon Clan, and all the factions of the demon clan have been annexed. Why are you so stubborn?"                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    "Bah!"                                                                                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The blood slave spat angrily, "If you want to kill, you can kill. Even if I die, I will not give the little Lord to you!"                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Say that finish, see him shake the hands of the banner, will be wrapped in the arms of the baby in which, see the ancient road at the end of that lofty peak, transport the whole body strength, force a throw!                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    Whoosh!                                                                                                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The huge red jolly Roger, wrapped around the baby, vanished in a flash into the sky and shot into the distant peak.                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    After a look, He suddenly changed his face wildly and shouted, "You are crazy! That's Cangyun Mountain!"                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//    The blood slave laughed and shouted, "Go to cangyun Gate if you dare!"                                                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TMS is ERC721Creator {
    constructor() ERC721Creator("The magic son", "TMS") {}
}
