
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: DIAMOND DREAMS
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    lldxk000000000KKKKXXWMMMXxddxkO00KKKXXXXXXNWWMMMWNK0000KKKXNNNNNNNWWWNNNNNNNNWMMMMMWWWWWWWWWWWWWWWWW    //
//    clodxO000000000KKKKXNWMMXxdxxkO0KKKKXXXXXNNWWWWWWXK00000KKXXNNNNNNNNNNNNNNNXNWMMMMWWWWWWWWWWWWWWWWWW    //
//    cllodkO00000000KKKKXXNWMXxdxkO00KKKKXXXXXNWWWWWWWX00O0000KKXXNNNNNNNNNNNNNXXNWMMMWWWWWWWWWWWWWWNNNNN    //
//    lllloxk00000000KKKKKXXWMXxdxkO00KKKKKXXXXNWWWWWWWX00OOO000KKXXNNNNNNNNNNNNXXXWMMWWWWWWWWWWWWWNNNNNNN    //
//    llllodxO00000000KKKKXXNWXxxkO00KKKKKKXXXNNWWWWWWWX00OOOO000KKXXNNNNNNNNNNNXXXWMWWWWWWWWWWWWNNNNNNNNN    //
//    lllllodkO0000000KKKKXXXNKkxOO00KKKKKKKXXNNNNNNNNNX0OOOOOO000KKXXNNNNNNNNNNXXXNWWWWWWWWWWWWNNNNXXXNNN    //
//    lllllldxk000000KKKKKKXXNKkkO00KKKKKKKKXXNNNNNNNNNX0OOOOOOO000KXXXNNNNNNNNNXXXNWWWWWWWWWWNNNNXXXXXXXX    //
//    llllllodkO00KKKKKKKKKXXXKOOO00KKKKKKKKXNNNNNNNNNNK0OOOOOOOO000KXXXNNNNNNNNXXXNWWWWWNNNNNNNXXXXXXXXXX    //
//    llllloodxk00KKKKKKKKKKXXKOO00KKKKKKKKXXXXXXXXNNNNK0OOOOOOOOO00KKXXXNNNNNNNXXXNWWWNNNNNNNNXXXXXXXXXXX    //
//    oooooooodxO0KKKKKKKKKKXXK000KKKKKKKKKXXXXXXXXXXXXK0OOOOOOOOOO00KKXXNNNNNNNXXXNWNNNNNNNNNXXXXXXXXXXXX    //
//    oooooooodxkO0KKKKKKKKKKXK000KKKKKKKKKXXXXXXXXXXXXKOOOOOOOOOOOO00KXXXNNNNNNXXXNNNNNNNNNNXXXKKKKKKKKKK    //
//    ooooooooddxO0KKKKKKKKKKXK00KKKKKKKKKKKKKKKKKKXXXXKOOOOOOOOOOOO00KKXXNNNNNNNXXNNNNNNNNNXXKKKKKKKKKKKK    //
//    ddddddddddxkO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOOOOOOOOOOO000KKXXNNNNNNXXNNNNNNNNXXKKKKKKKKKKKKK    //
//    ddddddddddxxO0KKKKKKKKKKKKKKKKKKKKK00000KKKKKKKKK0OOOOOOOOOOOO0000KXXXNNNNNXXNNNNNNNNXXKKKKKKKKKKKKK    //
//    dddddddxddxxkO0KKKKKKKKKKKKKKKKKK00000000000000000OOOOOOOOOOO00000KXXXXXNNXXXNNNNNNNNXKKKKKKKKKKKKKK    //
//    xxxxxxxxxxxxkO0KKKKKKKKKKKKKKKKKK0OOOO000000000000OOOOOOOOO0000000KKXXXXXXXXXXNNNNNNXXKKKKKKKKKKKKKK    //
//    xxxxxxxxxxxxkk0KKKKKKKKKKKKKKKKK0OOOOOOOOOOOOOOOOOOOOOO00000000000KKXXXXXXXXXXXXNNNNXXKKKKKKKKKKKKKK    //
//    kkkkkkkkkkkkkk0KKKKKKKKKKKKKKKKKKOkOkOOOOOOOOOOOOOO000000000000000KKXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK    //
//    kkkkkkkkkkkkkO0KKKKKKKKKKKKKKKKKK0kkkkkkkkkkkkkkOOO00000000000000KKKXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK    //
//    OOOOOOOOOOOOOO0KKKKKKKKKKKKKKKKKKKOkkkkkkkkkkkkkkO00000000000000KKKXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK    //
//    OOOOOOOOOOOOO00KKKKKKKKKK00KKKKKKK0kxxxxxxxxxxxxxO000K0KKKKKKKKKKKKKXXXXXXKKKXXXXXXXXXKKKKKKKKKKKKKK    //
//    OOOOOOOOO00000KKKKKKKKKKK000KKKKKK0Oxxxxxxxxxxxxxk00KKKKKKKKKKKKKKKKKXKXKKKKKXXXXXXXXXKKKKKXXXXXXXXX    //
//    000000000000000KK00KKKKKKOO000KKK00Okxdddddddddxxk0KKKKKKKKKKKKKKKKKKKKKKKK00KXXXKKKKKKKKKXXXXXXXXXX    //
//    000000000000000000000KKK0OOO0000000OOxdddddddddddk0KKKKKKKKKKKKKK0KKKKKKK0000KXXKKKKKKKKKKKXXXXXXXXX    //
//    KKKKKKKKK000000000000KKK0kkkOO00000OOkdooooooodddk0KXXXXXXXXXKKK0000KK0000OOO0XXKKKKKKKKKKKXXXXXXXXX    //
//    KKKKKKKKKK00OOOOOO000KKK0xxkkOOOOOOOOkxooooooooook0KXXXXXXXXXKK000000000OOOkk0XXKKK0000000KKXXXXXXXX    //
//    KKKKKKKKK00OOOOOOOO00KKX0ddxkkkOOOOOOkkdoooooooook0KXXXXXXXXKK00000000OOOkkxx0XKKK000000000KXXXNNNNN    //
//    XXXXXXXK00OOOOOOOOO000KNKdodxxkkkOOkkkkxolllllllokKXNXNNNNXXK00OOOOOOOOOkkxdxKNXKK0000OO000KKXNNNNNN    //
//    XXXXXXKK0OkkkkkkkOOO00XWKolodxxkkkkkkkkxdolllllllkKXNNNNNNXKK0OOOOOOOkkkxxdodKWXKK00OOOOOOO0KKXNNNNN    //
//    XXNNXXK0OkkkkkkkkkOO0KNMKoclodxxxkkkkxxxxolllllllkKXNNNNNNXK0OOOkkkkkkkxxdoloKMWX000OOOkOOOO0KXNNWWW    //
//    NNNNXX0OkxxxxxxxkkOO0XWMKoclloddxxxxxxxxxdlllllllkKXWNWNNXK0OOkkkkkkxxxddollo0MWNK0OOOkkkkkOO0KXNWWW    //
//    NNNNXKOkxxxxxxxxkkOOKWMMKoccllodddxxxxxdddollccllkKNWWWNNX0Okkkxxxxxxxddolllo0MMWX0OOkkkxkkkkO0KNNWW    //
//    NWWNX0kxddddddxxkkO0XWMM0occclooddddddddddollclllkKNWWWNXK0kkkxxxxxxdddoollco0MMMN0OOkkxxxxkkOOKXNWW    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DDRMS is ERC721Creator {
    constructor() ERC721Creator("DIAMOND DREAMS", "DDRMS") {}
}
