
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: On the
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//    Chen Pingan pick a bucket to far away. well, after working the middle lane of several shop early, stomach is not hungry, without a word just cash-strapped, young only crustily skin of head line up water, he there are three families, before his turn, childish, the horizontal thrust a foot suddenly carry only a small bucket, the people immediately behind don't want to.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//    Though not swearing, but it also does not speak well, especially a woman rickets, said the horse mother-in-law, two sons are very productive, having a bank kiln, although minimal, in three mouth bank kiln bottom, can be on this side of apricot blossom lane natural sky high conversion of the riches and honor, but somehow, woman and both daughter-in-law relationship is bad, Son daughter-in-law had moved to the other side of the peach leaf lane, woman has been living in the ancestral home of apricot blossom lane, in Chen Pingan liu Yang admire this generation's eyes, horse mother-in-law has been a terrible elders, call names very malicious, particularly is mean, winter courtyard the snow outside, she was going to his house, if there are children snowball fights with her door snow, Or unplug the ice awl under her eaves. She could chase and scold with a broomstick for blocks without getting tired.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract OT is ERC721Creator {
    constructor() ERC721Creator("On the", "OT") {}
}
