
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Nod your head
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    Walk on parts of the barren hillocks wild fox rabbit burial, between negative sword man suddenly stopped before a tombstone, before you come to a small small topped next to the tombstone of squatted and reached to strip winding stone rattan grass, show it's face, blur, can only vaguely identify less than half of text, man sighed, "Shinto collapse, reed height. The war of a hundred is about to begin."                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    After the man up, see that has not entered the true Wushan formal worship of the apprentice, positive always when the direction, the young mouth, ears and nose are bleeding, making the dark face, is particularly ferocious terror, the boy raised his arm to wipe a disorderly, continue to stare at the side.                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//    Man said: "ma xuan, according to you before the given reason, because you know that girl outside, in the alleyway fly fencing with one hand, teamed up with big sui prince and the eunuch, and kill you in my life the first teacher, so your heart hard, must before leaving the town to the enemy, I think this is plausible, will not stop you, let you life and death. After all, for a man of practice to encounter such an enemy of the road is both a crisis and an opportunity."    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract NYH is ERC721Creator {
    constructor() ERC721Creator("Nod your head", "NYH") {}
}
