
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Carrying a silver mountain
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Near the City God temple, the street is mostly to burn incense, both sides of the street there are many selling characteristic food and children's toys of various stalls. Chen Pingan Li Bao bottles and Li Huai one person bought a bunch of ice-sugar gourd, then two children started to compete who sugar-coated berry bigger star, proved Li Huai better luck, a total of a string of six, won Li Bao bottle, four times and then jumped dalai Li Huai began to happy and lifted the string of sugar-coated berry, around the Chen ping AnLin keep a run around in circles.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Li Bao bottle silently eating sugar gourd, and then quietly stretch out a leg, Li Huai an inattention to trip, fell a dog, hand that string of sugar gourd roll out far away, fortunately green bamboo small bookcase bound is still strong, Li Huai sat on the ground tore heart crack lung burst into tears.                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Red cotton-padded jacket girl raise head, looking to left intentionally, spirit again funny Chen ping hits to admire her a heavy Chinese chestnut, go and put your feet about Li Huai to assist, and sad lung injury children bought a bunch of sugar-coated berry, Li Huai smile through tears, took the clean sugar-coated berry, and pick up the string of muddy sugar-coated berry, a string, this be Li Bao bottle far away some, Shake sugar gourd from side to side.                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Li Bao bao rolled her eyes and said, "Childish!"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Very strange, li Huai seems to be no matter how li Bao bottle bully, have never hated the schoolmate girl, even angry are not to speak of, most is wronged, their own sad.                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    This point Chen Ping an and Lin Shouyi can not understand, Lin Shouyi can only be explained as one thing, Li Huai will need li Aquarius to clean up.                                                                                                                                                                                                                                                                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CASM is ERC721Creator {
    constructor() ERC721Creator("Carrying a silver mountain", "CASM") {}
}
