// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Mies Graffiti Art
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMWWWMMMMMMMMMMXXWMMMMMMMMMMMMMMMMMMMN0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.:XMMMKdcckNKl,;xWMMMMMMXo'cXMMMMMMMMMMMMMMMMMM0;..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  ,KMMM0,  .;' .cKMMMMMMK;  .dWMMMMMMMMMMMMMMMMWc   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMXkd0WMMMMMMMMMMMMMMMMMWo   '0MMMMO'    .lXMMMMMMMx.   .kWMMMMMMMMMMMMMMMWo    .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWk'  .lKMMMMMMMMMMMMMMMM0'   .OMMNOc.     .,lx0NWMMX:    .xWMMMMMMMMMMMMMMMX:     :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMk.     .xNMMMMMMMMMMMMMWl    .xMXo,,c;  .lo,..;d0XKXk'    .dNMMMMMMMMMMMMMMMXc     .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMx.       ;0WMMMMMMMMMMM0'     lWWNXNMk.  dMWX0xc,.....      lXMMMMMMMMMMMMMMMNd.     ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMK;        .dNMMMMMMMMMWd      ;XMMMMMKc,:OMMNo.              ;0MMMMMMMMMMMMMMWN0c.    .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWd.         :KMMMMMMMMX:      .kMMMMMWWWWMMWd.   .''.         .xWMMMMMMMMXkl:,','.      .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMX;          'OWMMMMMMO.       lWMMMMMNklclo'    ..:xxc.       .lXMMMMMNd'                .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWd.          .dNMMMMWo        '0MMMMNc    ..       .l0Xx:.      ,OWMMNc      ..            .lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNKNMMMMMMMMMMMMK,            cXMMMX;         lWMMM0'     :;        .l0N0l.     ,KMMx.  .;dk00Okdc,.        .oXMMMMMMMMMMMMMMMMWXXWMMMMMMMM    //
//    MMMMMMMMMWKl'.;xNMMMMMMMMMMWo             ;0WMk.  ,l.    .OMMM0'     :Kx;.       .:ONKl.  .oNMWo   ,KMMMMMMMMWXkl,.      'kWMMMMMMMMMMMMWKl..;xXMMMMMM    //
//    MMMMMMMMMWx.    'dXMMMMMMMMMO'    ,c.      'OWo   oX:     :XMMX:     .OMNO;.       .;kX0llOWMMM0'   'lx0NWMMMMMMMWKd;.    .dWMMMMMMMMMW0l.    ;KMMMMMM    //
//    MMMMMMMMMWKkd:.   'dXMMMMMMMNc    'Ox.      .o,  '0Mk.     oWMWo      lNO;.           ,xXMMMMMMW0;     ..;codk0KXWMMWKo,   ;XMMMMMMMW0c.   'lxONMMMMMM    //
//    MMMMMMMMKc..;dko,   ,kWMMMMMMd.   .kWk.          lWMNc     .kWMO.     'c.               'oKWMMXOXNk:.          ..';:loxxoclOWMMMMMMXo.  .:xko'.,xNMMMM    //
//    MMMMMMMMO,.   'oOk:. .OMWMMMM0'    oWM0,        '0MMMO.     ,0MNc          .ckxo:,.       .kMX:.xWMWKx:'.               .';lxKWMMMWo  'oOk:.   .lXMMMM    //
//    MMMMMMMMMN0o;.  .cOOodOo;:xXWN:    :NMMK;       oWMMMWo      ;KMk.          .lKWMWKOxl;.  .xWo  .kWMMMMN0xl;'.               .;oKWMOld0k;   .cxKWMMMMM    //
//    MMMMMMMMMMMMWKd;. .kW0'    .l0o    ,KMMMXc     ,KMMMMMX:      :XNc            .oKWMMMMWXkokNWl   .dNMMMMMMWKkOOxoc:,'...        .lXMMXc  .ckXMMMMMMMMM    //
//    MMMMMMMMMMMMMMMW0l;xWO'      ..    .kMMMMNo.  .xMMMMMMM0,      :XO.             .c0WMMMMMMMMMO'    :KMMMMNd. ,xNMMMWNXK0Oxoc,.    ;KMXl;xXWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWWMWKd'           dMMMMMWk::kWMMMMMMMMO'      :0l       .       .:kNMMMMMMMWO'    'kWMWo     ,kNMMMMMMMMMMW0l.   oWMWWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXo.         cWMMMMMMMMMMMMMMMMMMWO'      ;x;      :xl.       'oKWMMMMMMK:    .lXO' ..    :0WMMMMMMMMMMWo   lWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMKc.       ;KMMMMMMMMMN0kxxddxkOOx'      'c.     .cOXd'       .:kNMMMMMNd.    ,:. ;ko.   .oXMMMMMMMMMX:  .OMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWO,      .kMMMMMMMWk;.        ...       ..       cNMNk:.       'o0WMMMW0;        'dd;    ;OWMMWNKkl'  .xWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc     .dMMMMMMWx.                             '0MMMWKo,       .;dKWMMNx.        ..     .::;,'.    ;OWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.   '0MMMMMMNd''.....                      .cXMMMMMMNkc.       .:xXWMKc.                     .:kNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  .kWMMMMMMMWWNXXXK0Oxoc;.             .:OKNMMMMMMMMMWXx:.       .cxKNx.   .,,....      .:okKWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKooKMMMMMMMMMMMMMMMMMMMMMWXOo;.          .xNWMMMMMMMMMMMMWKd;.       .;c.   .OWNK00Ok;   'OWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx;.       .dNWMMMMMMMMMMMMMMMW0d;.           .OMMMMMMMXc   .kWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.    .dNMWKk0WMMMMMMMMMMMMMMWKxc,.       ;KMMMMMMMMNd.  'OWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo,'cOWMMO' .,oOXMMMMMMMMMMMMMMMWKkoc;,;l0WMMMMMMMMMW0c'.cXMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkxdoolcc:::;::::::lodxko.     .:okKWMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMNKXWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:;'..       .........                   .':lxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  ..,:cldxkOO00KKK0kdoc;'.                      .';:ldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0ook0XWMMMMMMMNKkdl:,..         ............              ..,cokXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:'.     .';:lodxkO0000KKKKKKK000Okkxdolc:;'...     cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   .':oxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOkxdd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,cx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MG is ERC721Creator {
    constructor() ERC721Creator("Mies Graffiti Art", "MG") {}
}
