
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Founder as the ce
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    around is gradually covered by frost, flowers and trees began to wither, as if all life will be the end.                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    "What a terrible force of death!!                                                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    Seeing this, the black robe's face changed as well, and he backed away hastily, taking a rune from his bosom and holding it in his hand. But before he could make another move, Fang Zheng seemed to be aware of his presence and turned to look at the black robe in front of him. Then he raised his sword and pointed at the black robe.    //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    "Crash!                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    For a moment, the black Robe was completely frozen by the sudden appearance of the ice, and his movement remained the moment he grasped the rune, as if time had stood still. But soon, out of the black robe's body, a vague, wailing figure flew, screaming and sucked into fang's longsword.                                                //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
//    "Evil undead, how dare you blaspheme the soul!!"                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract FATC is ERC721Creator {
    constructor() ERC721Creator("Founder as the ce", "FATC") {}
}
