
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Hypnos
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhysyossssyhhdddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs-.`..----------.```./NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`  `--:/::--.-..````./NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdyo+/:/:///++osyydddmMMMMMMMMMMMMMMMMyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMyMMMMMMMMMMMNMMMMMMMMMMMN+hMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh ho//ohmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMhdoMMMMMMMMMMMM dMMMMMMMMMMyyMMMMMMMMMM:/sMMMMMMm:+:+///+osydmNMMMMMMMMMddMMMMMMMMMd dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.:MMNdo:-:ohmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMyy/MMMMMMMMMMMm yMMMMMMMMMMN-oMMMMMMMMo.+mMMMMMMM.y-NNmdhyso+oo+NMMMMMMM+.+mMMMMMMMh +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMs hMMMMMMmho:-:sdNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMhs.MMMMMMMMMMMh sMMMMMMMMMMMm.oMMMMMMh s:MMMMMMMM.s sMMMMMMMMNs+MMMMMMMM/-..sNMMMMMm -MMMMMMMMMMMMMMMMNhsMMMMMMMMMMMMMMMMN:/sdNMMMMMMMMMMM.:MMMMMMMMMMMNhs+omMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMd+`NMMMMMMMMMMy +MMMMMMMMMMMMm.sMMMMN.-ssMMMMMMMM/+..MMMMMMNy-oMMMMMMMMM/.Ns`:hMMMMM` NMMMMMMMMMMMMNh/. `NMMMMMMMMMMMMMMMN    `:ymNMMMMMMNsyoshmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMd:.hMMMMMMMMMMs :MMMMMMMMMMMMMm.sMMM/ h.NMMMMMMMMo./ hMMMNy-:mMMMMMMMMMM+ NMN/`/mMMM: dMMMMMMMMMMmo.     oMMMMMMMMMMMMMMM:        -dMMMMMMMMMms/:/sdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMm--oMMMMMMMMMMs -MMMMMMMMMMMMMMm.dMy /y/MMMMMMMMMy o +MNs..hMMMMMMMMMMMMo hMMMm-`oNMo sMMMMMMMMN+`        +NMMMMMMMMMMMN:         .NMMMMMMMMMMMMMdo:.-+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMN`/:MMMMMMMMMM+ .MMMMMMMMMMMMMMMm:d``m.dMMMMMMMMMh o .+./hMMMMMMMMMMMMMMs yMMMMMy..hh /MMMMMMMMh`          `omMMMMMMMd+`         -NMMMMMMMMMMMMMMMMMMds/../smMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMN +`MMMNmddhhy: `hNMMMMMMMMMMMMMMN. os:MMMMMMMMMMm .. yNMMMMMMMMMMMMMMMMs oMMMMMMN+ / -MMMMMMMMMNo`           `:://:`          `sMMMMMMMMMMMMMMMMMMMMMMMMNho:-/yMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMN + syssyyhddm/  mMMMMMMMMMMMMMMMm .N.hMMMMMMMMMMM `/ hMMMMMMMMMMMMMMMMMh oMMMMMMMMd- `MMMMMMMMMMMNs.                        `oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMdo:hMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM`+ hMMMMMMMMM+  mMMMMMMMMMMMMMMM/ ys-MMMMMMMMMMMM. / yMMMMMMMMMMMMMMMMMm +MMMMMMMMMN/ :mMMMMMMMMMMMNh+.                   --oNMMMMMMMMMMMMMMMMMMMMMMMMMMdo-:yNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM`o sMMMMMMMMMs  dMMMMMMMMMMMMMMd :N.hMMMMMMMMMMMM/ + dMMMMMMMMMMMMMMMMMN`+MMMMMMMMMMh -.yMMMMMMMMMMMMMo-y+:-.``     `.-+smNNh+yMMMMMMMMMMMMMMMMMMMMMMdo.-+mNmdMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM`y +MMMMMMMMMy  mMMMMMMMMMMMMMM/`mo/MMMMMMMMMMMMM+ ssMMMMMMMMMMMMMMMMMMM./MMMMMMMMMMN sh-+NMMMMMMMMMN/+NMMMNNNmmy -mNNNMMMMMMMNMMMMMMMMMMMMMMMMMMMdo.-+dNms:+mMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM.h`:MMMMMMMMMd  NMMMMMMMMMMMMMm om.mMMMMMMMMMMMMMo oMMMMMMMMMMMMMMMMMMMM:/MMMMMMMMMMM-oMNo:dMMMMMMMMNdMMMMMMMMMMy -MMMMMMMMMMMMMMMMMMMMMMMMMMMMdo--+hNNh/:omMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM-d::MMMMMMMMMN  NMMMMMMMMMMMMMo.N/yMMMMMMMMMMMMMMo sMMMMMMMMMMMMMMMMMMMM+/MMMMMMMMMMMo/MMMd/sMMMMMMMMMMMMMMMMMMMd /MMMMMMMMMMMMMMMMMMMMMMMMMds::+hNMNs:/hNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM:mo.MMMMMMMMMM. MMMMMMMMMMMMMM-hh/MMMMMMMMMMMMMMMs dMMMMMMMMMMMMMMMMMMMMs+MMMMMMMMMMMd-MMMMNyoMMMMMMMMMMMMMMMMMMM+hMMMMMMMMMMMMMMMMMMyoosssooymNMMMMhymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM/Nh/MMMMMMMMMMo-MMMMMMMMMMMMMMyM/NMMMMMMMMMMMMMMMy.NMMMMMMMMMMMMMMMMMMMMdsMMMMMMMMMMMM-MMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMmMNhMMMMMMMMMMNmMMMMMMMMMMMMMMMNmMMMMMMMMMMMMMMMMNhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract hypnos is ERC721Creator {
    constructor() ERC721Creator("Hypnos", "hypnos") {}
}
