
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dancing Palms
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMWWWMMWWWWMMWNWMMWWWWMMWWWMMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMMWWWMMWWWWMMWWWMMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKOkddONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWMMWWWWMWWKd:'...'xWWWWMMWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWMWWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWNk,.....;kNWMMWWWWMMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWWMMWWWWMMWWWMM    //
//    MWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWO' ...,o0WXOxooooox0NWMWWWWWWWWWWWWWWWMWWWWWWWWWWMWWWWWWWWWWMWWWWWWWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0dllokKNWWWXc... .xKkl,..   .';lKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWXk:. ..:ONWk. .. .;,.....::.:ONWWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWWWMM    //
//    MMWWWWMWWWWMMWWWMMWWWWMMWWWMMWNWWWNk;.....lKd.........,llxXXKXWWWWMMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWNXXKKKKXKOo'....;,..... 'lxKXKKKKKKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWNOl:,''...',;:,............'cc;,''....';cokXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MMWWWWMWWWWMMWWWMMWWWWMWNKOxd:.',..................  ............ .;kNWWMMWWWMMXooKMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWNX000lcllo,......................::;;,'.,kOdx0NMWWW0, ;0WWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWWWMM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXOoc'.............'lOxddxOkKXKXX0lcOx,..;dKWWO' .dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk:..................'lkXWWWWWWWWWWNXNNo. ..,kW0, .lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWW0:...........'......... .dWMWWWWWMWWWWMW0d;.. .xx. .dXOxdlcccoONWWMWWWWMMWWWMMWWWWMMWWWMM    //
//    MWWWWWMWWWWMWWWWWMWWWWMWWWWWMNd'...,cc,... .l:..........'dXWWMWWWWWMWWWWMO,.. :o..':;......;lkNWWWWWMWWWWMWWWWMMWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWNo....cK0:.....,kx. ...'.....,0WWWWWWWWWWWWWWN0x;..'.......'lkKXWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWMWWWWWWWWWWMWWWWMMWWWWMWWO' .,dXXc......dNO,....:l....lNWWWWWMWWWWMWWWX0d:..........':lkXWWWWWMWWWWMWWWWWMWWWWMWWWWWM    //
//    MMWWWWMWWWWMMWWWMMWWWWMMWWWMO,'l0WMk'....'dXMXo.....ld' .lNWMMMWWWMMWWWKd;.. .......... . .'cOWWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWKxONWWX: ..,lONWWNKc... ,Od. .xWWWWWWWWWWNx'........... .:o;......dNWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWOcclkKNWWWWWNk:.. ,0Nc. 'OMWWWWWWWNd. .........;c. .oO0kc,...xWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MMWWWWMWWWWMWWWWMMWWWWMWWWWMMWWWWMXXNWWMWWWWMWWNK:..cXM0, .cOXMWWWWMK,..;:'.ll.. ;Oc...cXWNKOd;oNWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWWMMW0,;0WWNo. .,xWWMWWW0,.oOc;kWO,. :0l....lNWMWWKKWMWWWWMMWWWMMWWWWMWWWWMM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKOXWWWO' . ;KWWWWMNOO0c:0WWK: .xNo... ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc.  .xWWWWWWWKc:0WWWk,;kNW0:.. 'OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWWMMWWWWMMWWWd. ..cXMWWWWNl;OWWMNOONMMWNk'. ;KMMMWWWMMWWWWMMWWWMMWWWWMMWWWMM    //
//    MMWWWWMWWWWMWWWWWMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMMk. . 'OWWWMWd,xWMWWWMMWWWWMX:.;OWWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0, ...dWWWWO,lNWWWWWWWWWWWWNOkXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK; ...cNWWXc;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MMWWWMMWWWWMMWWWMMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMMX: .. ,0WWk,dWWMMWWWMMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWMWWWWWMWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWNc... .kMXc;KMWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWWM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNc... .dWk'dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MWWWWWMWWWWMWWWWWMWWWWMWWWWWMWWWWMWWWWMMWWWWMWWWWMWWWWWMMXc.....oXc,0WWWMWWWWWMWWWWMWWWWWMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWWMMWWWWMMWNWNc ....lx':XMMWWWWMWWWWMMWWWWMWWWWMMWWWMMWWWWMMWWWMMWWWWMMWWWMM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMK; ....;;.dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM0, .......kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWNWO' ..... 'OWWMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMWWWWWMWWWWMWWWWMM    //
//    MMWWWWMWWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMMx. ..... ,0WWWWMMWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXK0kxdoo,....... .:lodxkO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOxol:;'.....  ..........    ....',;coxOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    MMWWWMMWWWWMMWWWMMWWWWMMWWWMMWWWWMWWWWXko;'.................................... ...;cd0NMMWWWWMWWWWMMWWWWMWWWWMMWWWWMWWW    //
//    WWWMWWWWMMWWWWMWWWWMMWWWWMWWWWMMWWWWWO:'..............................................,dXWWMMWWWWMWWWWMWWWWWMWWWWMWWWWMM    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWMWWWWWWWWWWWWWWWMWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWMWWW    //
//    NWWMMWNWMMWWWWMWWNWMMWNWMMWWWWMMWNWMMWWWWMMWWWMMWWWWMMWNWMMWWWWWMMWNWMMWNWWMWWNWMMWNWMMWWWWMMWNWMMWWWWMMWNWMMWWWWMMWNWMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DPLMS is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
