
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Jing xuan pool
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//    Jing Xuan teacher Mrs Narrowing her eyes, looking at Ye Xiaochuan, way: "drunk brother, you this good apprentice, over the past few years have added a lot of trouble to you, small thief little wine money is just, but as far as I know, he often steal female disciples room steal female disciples of personal accessories. Drunk elder brother, you should know very well that this kind of thing is the most taboo thing among us right people. If I don't teach him a lesson this time, he'll go astray."    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//    Drunk way person's facial expression slightly a change, way: "Static xuan teacher sister, words heavy, words heavy."                                                                                                                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JXP is ERC721Creator {
    constructor() ERC721Creator("Jing xuan pool", "JXP") {}
}
