
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: The depths of the sky
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Silver city.                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Inspection department.                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Young Li Hao, slightly thin figure, some black eyes, as if I stayed up late last night.                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Wearing inspection division three inspection uniform, Li Hao stepped into the inspection division office area.                                                                                                                                                      //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    As a new member of the inspection department for only a year and a half, Li Hao in the inspection department of seniority is not deep, usually a little earlier, simply clean the office area, and then boil water, waiting for the arrival of other colleagues.    //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    But today's Li Hao, to a little later than usual, at the moment there are many people have arrived in the office area.                                                                                                                                              //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    See Li Hao enter the door, the door desk, a middle-aged woman in uniform, a face of enthusiasm, with some sense of humor, jokingly said: "Xiao Hao, came late today, black circles are out, last night is not to natural and unrestrained?"                         //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Li Hao showed a pure smile, as if very simple simple, hurriedly waved his hand: "Yu elder sister, don't talk nonsense, I haven't found a girlfriend, spread out, no one married me later!"                                                                          //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    "Ha, ha, ha, you this child, in the inspection department has spent a year, this words all can not pick up."                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Middle-aged women seem to like to make fun of Li Hao.                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Look at Li Hao's eyes, also with some different, hearty smile for a while, suddenly old words repeat: "Xiao Hao, usually a person has no time to cook, eat outside is not clean, go back to my house to eat."                                                       //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Li Hao smiled again, but still refused, "Sister Yu, I won't give you any trouble."                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Yu Jie did not speak, not far away, a middle-aged man hissing, interrupted: "Xiao Hao, you yu Jie is calling you to dinner? Is to call you to come to be a son-in-law, you this boy, why not on the way!"                                                           //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    "Ha ha ha!                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Laughter broke out in the office area.                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Sister Yu was not embarrassed to be found out. Her eyes widened and she scolded fiercely, "I'm glad! Xiao Hao how good, good character, good brain, good appearance, really give me when the son-in-law, I dream can wake up laughing!"                             //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    At this, the crowd laughed, or many people nodded in agreement.                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
//    Li Hao this young man, many people or very optimistic.                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Thedoorofthered is ERC721Creator {
    constructor() ERC721Creator("The depths of the sky", "Thedoorofthered") {}
}
