// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Rich McCoy Wylder
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc',;;ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.,OXO:.cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,'OWWXo,;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.,oOMWXkd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMM0,.,xWMMMXk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc::lkXWMMMMMMMMMMMWd..cNMMMMXKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,      .oXMMMMMMMMMMMK; .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.         ;kNMMMMMMMMMWx,..kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl .';,      .lXMMMMMMMMMKx; ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMXkolccccccclllodkOKNWMWd. .;xc      .cKMMMMMMMMWXl  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNx,                 ..,codlld0WK;      .kMMMMMMMMWWx.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMKc.                        .;o0WWk.      lXMMMMMMMMMO.  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWO,                             .:kk'      .xWMMMMMMWWx.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMO'                                ...      .xWMMMMMMKx;   oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX:                                           ,OMMMMMWo.   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWx.                                           .kMMMMMK,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK;                                            ,0MMMMMO.   .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWx.                                            .kMMMMMk.    dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNc                                             'OMMMMMO.    ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0,                                             ,KMMMMMX:     oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0'                                              cXMMMMWx,.   .dNMMMMMMWNXK0OOkkkkkkkOO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOO0NWMMM    //
//    MMMMMMMMMMMMMMMMMMMK;                      .:lllll,                 ,dKWMMXOc    .lKKOxolllccccllloooollllllllldkKNMMMMMMMMMMMMMMMMMMMMMMNOc'.. .'oKWM    //
//    MMMMMMMMMMMMMMMMMMMWo                    .c0WMMMMMx.                  .;d0NN0;     ,clooc::cclllllookKNWMWWNX0kdlcclxKWMMMMMMMMMMMMMMMMXx;. .;dd:. .xW    //
//    MMMMMMMMMMMMMMMMMMMMK;                 'l0WMMMMMMWd.                     ..''.  .:d0NWNo'ckO0KKKK0kdl:cxNMMMMMMMMNKxl:ckNMMMMMMMMMMMWKd'   .xNMMK,  ,0    //
//    MMMMMMMMMMMMMMMMMMMMM0,            .,lkXWMMMMMMMMWd.                          ,dKWMMMMWd.,loxOKXNWMMWXx;:OWMMMMMMMMMWXd::kNMMMMMMMW0l.    .xNMMMK,  :X    //
//    MMMMMMMMMMMMMMMMMMMMMK;......';:ldOKNMMMMMMMMMMMMWo                         'xNMMMMMMMMX;     ..,:coxO0k;;OMMMMMMMMMMMMXo,lXMMMMWOc.     'OWMMMWd. ;0M    //
//    MMMMMMMMMMMMMMMMMMMMMO''loooddxkkkOKWMMMMMMMMMMMMWo                       ;d0MMMMMMMMMMWx.            ....,oxk0XNWMMMMMMWk,lNWXk:.     .cOWMMMWk. :KMM    //
//    MMMMMMMMMMMMMMMMMMMMMXdlol,        'OMMMMMMMMMMMMWl                      .xWMMMMMMMMMMMMK,                    ..',:loxk0K0l,cc'       'kWMMMMM0,.cXMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMXd,.     .dWMMMMMMMMMMMWl                      .kMMMMMMMMMMMMMX;                             ....         .dKWMMMMMX: :XMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxo:;..dWMMMMMMMMMMMWl                       lKNMMMMMMMMMMMO'                                        .l0WMMMMMMWd..OMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'dWMMMMMMMMMMMWl                       .'cKWMMMMMMMNk,        .;l:,',;.  ..                .',l0WMMMMMMMMX; :XMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'dWMMMMMMMMMMMWl                          .:oxxxxoc'           ,kXNNWNl.l00xddoc,;c:,'...,cONWWMMMMMMMMMM0' oWMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'dWMMMMMMMMMMMWl                                                 'lONK;:KMMMMMMWWWMWN0c,xNWMMMMMMMMMMMMMMK,.dWMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'dWMMMMMMMMMMMWl                                                   .cl,xWMMMMMMMMMMWO:;kWMMMMMMMMMMMMMMMMNl.lNMMMMM    //
//    MMMMMMMMMNOolloxKWMMMMMMMMMMMMMMMWx'dWMMMMMMMMMMMWl                                                  ..''oNMMMMMMMMMNkc;oKMMMMMMMMMMMMMMMMMMMK;'kWMMMM    //
//    MMMMMMMMWd. ,:,..;d0WMMMMMMMMMMMNk;.dWMMMMMMMMMMMWl                      ....;lclc;.               .lo;,dNMMMMMMWKkl:cdKWMMMMMMMMMMMMMMMMMMMMMXdkWMMMM    //
//    MMMMMMMMWx..dNN0o' .;xXWMMMMMWKd,. .dWMMMMMMMMMMMWl                .,'.'lOXKXWMMMMWXOdl:.          ';:oKWMNX0kdlccld0NMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMM    //
//    MMMMMMMMMWO:.,dKWXd'  .l0NWXk:.    .dWMMMMMMMMMMMWl                'kXXNWMMMMMMMMMMMMMMWO'           ,xXNx:clldk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNk;..dXWXo.  .,;.       .dWMMMMMMMMMMMWl                 .c0WMMMMMMMMMMMMMMMMK;,d:.         'c;':looxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNx,.,dKXo.            .dWMMMMMMMMMMMWl                   .oXMMMMMMMMMMMMMMMK;.cl,.           .:dxdoollcldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNx' ..              .dWMMMMMMMMMMMWl    ...   .          cXMMMMMMMMMMMMMMW0xxxxkkxc'.        'lONMWNKOdc:lxXMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMW0o.             .,' .dWMMMMMMMMMMMWl  .o0K0kxk0Ol'       .oNMMMMMMMMMMMMMMMMMMMMMMWN0o;.        'lOXWMMWKx:;dXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW0:.            ';lO0; .dWMMMMMMMMMMMWl  .OMMMMMMMMWXx'      ,KMMMMMMMMMMMMMMMMMMMMMMMMMMWKd:'.       .cxXWMMNk;:OWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXo.          .;oOXWMMk. .xWMMMMMMMMMMMWo  :XMMMMMMMMMMW0;    .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNk, .       .l0WMMKc,kWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMK:       ..:okXWMMMMMMk. .OMMMMMMMMMMMMMk. .dXMMMMMMMMMMMXd,,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'oOl.      .cOWMXc;0MMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMNl     .:k0XWMMMMMMMWWXo..xNMMMMMMMMMMMMMWx'  cXWWMMMMMMMMMMWWMMMWWNXKKXNWMMMMMMMMMMMMMMMMMMMMMMMM0,cNWXkxl;.   .:kXk,oWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMK,     lNMMMNOxdooolllccd0WMMMMMMMMMMMMMMMWXxc:cllooddONMMMMMMWKdlccllllcclxKWMMMMMMMMMMMMMMMMMMMMK;;XMMMMMW0d;.   ':.cXMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMX;    .dWMMMK,.;clodxkOKKKKKKKKKKKKKKKKKKKKKKK0Oxdol:.'OMMMMMXo;lkKXNWWNNKxc;oXMMMMMMMMMMMMMMMMMMMK;;KMMMMMMMMNOo;.   .xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWx.    ,OWMMXo:llllllllc'.........;:'..........;lllll:lKMMMMXc,kWMMMMMMMMMMWk,cXMMMMMMMMMMMMMMMMMM0,:XMMMMMMMMMMMWKd'  .cKMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNx.    .lOXWWWWWWWWWWWXc         ,ko.        'OWWWWWWWMMMMWx'dWMMMMMMMMMMMMWo'kMMMMMMMMMMMMMMMMMMk,oWMMMMMMMMMMMMMNl..  ,OWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWKd,.    .;lkKNWMMMMMM0'         oXl        ,KMMMMMMMMMMMWd'xMMMMMMMMMMMMMWd'xMMMMMMMMMMMMMMMMMNc,OMMMMMMMMMMMMMNd,o0o. .oXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMN0d:'.    .':okKWMMNc        ,0M0,        :XMMMMMMMMMMMk,lNMMMMMMMMMMMMNl,OMMMMMMMMMMMMMMMMNd,dWMMMMMMMMMMMMXo,dNMW0:  cXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWNK0Oxl;..  .:xXNl        .xW0'        lNMMMMMMMMMMMNo,dNMMMMMMMMMMMO,cNMMMMMMMMMMMMMMMXo,dNMMMMMMMMMMMNx::OWMMMMXl .dWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWN0d:.  .c,        .xWO.       .dNMMMMMMMMMMMMNd;l0NWMMMMMMMNl,OMMMMMMMMMMMMMMNk:;kWMMMMMMMMMWKd::xXMMMMMMMX: 'OMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx;           ;XMO,        ;0MMMMMMMMMMMMMW0l;;ckXWMMMMk,lNMMMMMMMMMMWN0d::dXMMMMMMMMNKxc:ckNMMMMMMMMMM0' cXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;         lNMWKOd'    cKWMMMMMMMMMMMMMMMWKOdc:lx0NWO::lodxxxxxdollcclkNWMMMMWX0xlcclxXWMMMMMMMMMMMMWd..kMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;       .kMMMMMMKocokNMMMMMMMMMMMMMMMMMMMMMWKxocclllcccccclllodxO0KXXKOkxollccox0NWMMMMMMMMMMMMMMMMX: lWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.       :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xdollllllllllllccllllooxOKNWMMMMMMMMMMMMMMMMMMMMMX: :XMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.       ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXKKKKKXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.,kWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.        ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0NMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.        ..:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNOl.        .o0x:kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNk,.        'lKWMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNo.       'lOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNl.     'lONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMk.    ;kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMM0,  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWk' cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0okWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract RMcW is ERC721Creator {
    constructor() ERC721Creator("Rich McCoy Wylder", "RMcW") {}
}
