
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Soul return xi
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Three hundred years later.                                                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Dry xuan continent, silver Moon Empire, dark moon city, yu home town.                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    The night was deep.                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    In medicinal material old family -- the old curtilage ancestral hall periphery of yu home, the wind howled, withered leaves whirled.                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "Come back, come back!                                                                                                                                                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    A gray clothes withered old man, shaking the copper bell, around the ancestral temple walk. Accompanied by the clanging of copper bells, the old man from time to time gave out a dark and deep low noise, like the evil spirits crying in the depths of the earth.                                             //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Ancestral hall four corners, respectively, erected four poles of conjuring flags, flags fluttering in the wind, the flag painted carved ghosts, such as to break free and out, choose and bite.                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    After a long time, the old man stopped silent and shook his head at the Venerable Master.                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Yu Can, the venerable master who had broken both his legs years before, sat slumped in his wooden wheelchair. His face was sad. "Is it true that my grandson will never come back?"                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    Ning Ji put away the bell, took a look at the ancestral hall, silence half ring, way: "life is born with three souls of heaven, earth and man. The soul of the earth gathers memory, the soul of heaven opens wisdom, and the soul of man controls his own flesh and blood shell, all actions and practice."    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "Master Yu... Different from ordinary people, I have judged early, its heaven, earth and three souls, only the soul of man born."                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "As for the earth and heaven spirits, for some unknown reason, they never appeared."                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "Yu master these years, has been difficult to remember, the things that happened before, remember not to teach lessons and studies, all because the soul of the ground is missing, making all kinds of life experience, all kinds of memory, can not be branded together."                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "As for the unexamined and capricious acts, the unopened soul of heaven leads to wisdom... Chaos."                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "However, although the soul of the earth and the soul of the day is important, but the soul is the key to life and death. The soul of man is also called the soul of life, the soul of the Lord, the soul of man is not destroyed, people will not die."                                                        //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "Is muddled, do not know the past, because the soul is alive, yu master still safely through seventeen years."                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    "But now it is the human soul that is in serious trouble!"                                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SRX is ERC721Creator {
    constructor() ERC721Creator("Soul return xi", "SRX") {}
}
