
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Hearing zhang Tianhai say this,
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    Zhang Tianhai helped the German M35 helmet on his head, slowly closed his eyes, but closed his eyes are filled with the familiar faces that were pierced by rifle bullets.                                                                                                                                                                                 //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    Pain, not just any pain.                                                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    A clear tear ran from the corner of his eye, then across his handsome, smoky face and finally onto his dirty uniform.                                                                                                                                                                                                                                      //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    Yes, they are the most elite mechs in the whole of China, and the best in fighting power in the Chinese army.                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    After all, they are people, not god, they are also flesh and blood, was hit by the bullet will be injured, will sacrifice, from the early morning to now, just six hours, more than 50 brothers died, there are more than 20 seriously injured brothers uncertain of life and death, which has always been heavy feelings of Zhang Tianhai how not sad?    //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    Zhang Tianhai in the past life is indeed the leader of the Marine Brigade, is a Marine brigade can be called the "god of war" man, but so what? A lone hand, can defeat the Japanese aircraft cannon? Can he bring back his fallen comrade? Will the soldiers who are ready to go to war return unscathed?                                                 //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    No, he can't do anything. He's just one man. He's not against the world.                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    If Zhang Tianhai had been left alone with this group of Japanese soldiers to play jungle warfare, he might have survived, but now he is a company commander! He wants to command this battle, he wants to break through the Japanese line with the whole company of soldiers!                                                                              //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    After all, he was facing the most powerful Japanese marines in the whole of East Asia at this time!                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    In the past life when reconnaissance brigade squadron leader, Zhang Tianhai countless daydream, if he came to the Anti-Japanese War period, that will be how? Will he lead his troops to victory?                                                                                                                                                          //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    However, such as "dream" come true, the reality is so cruel - he is facing the enemy, is absolutely the Trump card among the Japanese, they shoot strange, hiding in the building above the commanding ground shooting, Li Haocheng company commander is dead in the hands of the devil put the gun.                                                       //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    The Marine Corps, from the very beginning, was expected to be a first class unit, both individually and collectively, because its mission was to land on heavily fortified enemy coastlines.                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//    Because of its mission, the Marine Corps is a first-class elite force, both in modern times and in the past, just like the PLA Marine Brigade in the 21st century. Which is not a rapid reaction force?                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
//                                                                                                                                                                                                                                                                                                                                                               //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract HZTST is ERC721Creator {
    constructor() ERC721Creator("Hearing zhang Tianhai say this,", "HZTST") {}
}
