
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: See a sunny day
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//    Investigate its reason, one is that the low temperature all the year round is not suitable for human living for a long time, the second is, the wild beast, level is not low, mostly more GuYuan twelve of the Wolf said, the twelve Wolf is ancient blood circulates, although a lot of blood thinner, but still is powerful, especially that of the legendary king of the Wolf, double pupil ice ray Wolf, is likely to have set foot on dead lingjinghutong, Such a realm, I am afraid that even if a few master together, the odds of success will not be very great, not to mention its seat under the eleven Wolf king, each strength is probably five layers above the mysterious realm, there are countless wild animals.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SSD is ERC721Creator {
    constructor() ERC721Creator("See a sunny day", "SSD") {}
}
