// SPDX-License-Identifier: MIT

pragma solidity ^0.8.19;

import "./IGovernance.sol";
import "./IERC20.sol";

contract RelayerCompensationProposal {
    IERC20 public constant TORN = IERC20(0x77777FeDdddFfC19Ff86DB637967013e6C6A116C);

    struct RelayerLoss {
        address relayer;
        uint256 lostAmountInTorn;
    }

    function executeProposal() public {
        // Data from 'data/relayerLosses.txt', generated by 'scripts/calculateLosses.ts'
        RelayerLoss[4] memory relayerLosses = [
            RelayerLoss(0x864DF9CD806D58341f13602103Bf853066ff962a, 625_894_225_496_155_734_516),
            RelayerLoss(0x5555555731006f71f121144534Ca7C8799F66AA3, 43_970_301_082_908_267_318),
            RelayerLoss(0x2Ee39Ff05643bC7cc9ed31B71e142429044A425C, 189_640_345_451_160_934_437),
            RelayerLoss(0x03392600086874456E08D2bAc104380BCdEBCfC0, 129_757_783_603_193_410_350)
        ];

        for (uint256 i = 0; i < relayerLosses.length; i++) {
            TORN.transfer(relayerLosses[i].relayer, relayerLosses[i].lostAmountInTorn);
        }
    }
}
