
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Aha!
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNWMMMWXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWKOKWMMMXO0NMMMMMMMMMMMMMMMMMMMMMMMWNNXXXNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMWWWMMMMMMMMMMMMMMMMMMMMMMWWXxlcccooodddddxKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN00NMMMMMMMMMMMMWKkxo:;;,;;cdkkkkkkkx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWX0XWMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMW0ko:::cl:;;,:x000000OkkkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWX0XWMMMMMMMWNKKKKKKKKXWMMMMMMMMMMMMMMMMMNxc:;,;cllc:;;ldxO00000kldKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWXNWMMMMMMMMMMWNKkdoooooooxKXWMMMMMMMMMMMMMWXOo:;;,;;;clc;,,;cdxdxxdoclk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXO0NMMMMMMMMWNKkdlccccccccldx0NWMMMMWNWMMMMXxoc;;;;;;;;;;;;;;;;;;;;;;;;;:xXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWWWMMMMMMMWWKkxollllllllllllldx0NWMWXO0NMMMWX0dcclllllllccccccccllcc:;,,,:lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWKOdlllllloddddoollllldk0NMWNNWMMMKo:;,lxxkkkkko;,,,,,:dxdl:;,',o0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNOdocclooodddddddoolccldkXMMMMMWOdc'..';:cokOdc;'.....,:coxl;,''ckOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNKXWMMMMMNOdoccloddddddddddollcldkXMMMMMW0dddolc;,,:xOdcccc;,;ccclxOd:,,';cok0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXOKWMMMMMNOdocclooddddddddoollcldkXMWXNWMMMMMWKOo::ck00000kl:oO0OO0Od:,,,codxOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWWMMMMMMW0kdlllllooddddoollllloxOXWXO0NMWWWWNKOdlcok00O00kocdO0OOOko;,,;oOkxxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWN0xdlclllooooollllodONWMMWWWWWX000000OOkkOOOOOOOOkOOOOOxlc;:okO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWNKxolcccccccclodOXNMMMMMMMMWX0kddddooolccccloooolclooc;;,:x0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWXKkoooooooox0XNMMMWX0XWMMMWNO:;;:::;;,'''',,;;;,;;;;;,';kNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNKNWMMMMMMMWX000OdlookNMMMMMWX0XMMMMMMO;',;;;,,'',,,,,,,,,,,,,,:oxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWXOKWMMMMMMMMMMMMNOdolxNMMMMMMMMMMMMMMMKoccc:;;,,;;::::;,,,,,,'.cOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMWW0oxNMMMMMMMMMMMMMMMMWXd::;;;;,,;;,;,,,,,,,'',:l0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMN0OXMMMMMW0oxXWMMMMMMMMMMMMMMMMXl';:::;;,,,,,,,,,,'',;:clox0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMWOccoxKWMMMMMMMMMMMMMMXl.',,,::;,,,,,,,,,'';cllllodxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxolloooxKMMMMMMMMKdlc:,'.,:c:,,,,,,,',;:cllllllllxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl,...'lxxxONW0xl;,;;,'.',;;:;;,,'',;ldollollllldOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxl,......';cxk:.'::,....',;;;;,,;;:cloooooollllllldKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdc;.....':do:;,,,,''.',,;lo:,,,;oxdolc:lddooollllloONWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdc::;'.',:llooodoc:,':ool;;coodddo:',:cc:lddollllloodONMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKxldO000o;,,;collc,'cdxdl:;;cdo;''...',;cxxolllllllokNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOokNMMMXko,.';;;,''cdxdol::col:;;;,...':dxlcclllllodk0NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcok0NMMM0;.';;,'''cdxdolllc::clllc:;'.':cclccclllllodXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0doloKWX0x:':cc:;''cdxdolllc;:clllllc;....lxl::lllllldXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0ddKWx'':lc;;;;'.cdxdolllloooolllc:,....lxl;:lllllld0NWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKddKNd..:lc;;;,..:oddlllc:',ldolc,''....lxl;:llllllood0WMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lcod:..cl:;;;,...,,,,,,'...',cdl,......lxl;:lllllllloOWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kdc,..:lc;;;,...............';,.......,;colcclllllloOWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkl:,;clc;;;,..............'............:xdc;cllllloOWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklllllc:;;;;'............,;,...........,clcccclllloOWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xlllc:;;;;;;;;'..........,;;;,...........'col:clllokXWWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMWMMMMMMMMMO:,;::cc:;;;;;;::,..........,;:::;,...........'colc:llodkNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNKKKKNMNXKKKNMMMMMM0l::;clc:;;;;;ck0l'.........,:d0kc;'............,:ooc:::dXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWOloxk00kolxkKWMMMMM0lcxOxodkko;lk0NWKkkl,.....'oOXWN0kc,........'''',;:looodOKNMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWNXkloxkkxdlldxOKXWMMMXkOXW0oxXNx:dXMMMMMM0;.....:0MMMMMWKkl,'....,oxl;,'';:::::cx0XWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWX0OxxxxxxdddddxxxxOKNWMMMMMWOloOKkdONMMMMMMKl,..,lxXMMMMMMMMKxl:,'.:KWOdoooc:::::cok0WMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMKxoc:::::::::cldxxxxkkKNWMMMW0ollo0WWMMMMMMMNOd:'lXWMMMMMMMMMMWNOdc'cKMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWNKo;;,,,,,;cdxxxxxxxxkkKWWMMWNKdo0MMWMMMMMMNOxdoONMMMMWMMMMMMMWOxdokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWX0xc:cclodxxxxo:lxOkxkO0NMMMXxo0MN00NMMMMKc,,,oNMMMN0KWMMMMMXo,,,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWOooO0OOkxdlclodkkkxxxOXMMMXxdKMWX0xo0WW0;...cXMMMWXNWWOokNXc...;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMW0oxXWX000OocokkkxxxO0KNMMMXxo0MMMXc.:ddl'...cXMMMMMMMNo.,do,...;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMKkONWNKNWWK00000000XWMMMMMN0kXMMMNd::c::c::cxNMMMMMMMWkc:::::c:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMWWWWMMMMMMMMMMMMWWMMMMMWWWWWWWWWWWMMMMMMMMMWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AHA is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
