
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: I have three phases
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    Big Xia, Tianshu County.                                                                                                                                                                                                                                                                       //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    In The South Wind City in June, the hot sun baked the earth like fire.                                                                                                                                                                                                                         //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    South Wind Secondary school.                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    Spacious and bright training ground.                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    Many fresh-faced, youthful young girls dressed in training clothes sit around, looking at the center of the field, where there are two figures in the rapid competition, the hands of wooden swords in the fierce collision, there is a clear sound, echoed in the training field.             //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    Both of them are about 15 or 16 years old. The boy on the right has a long body, handsome face, bright eyes under the eyebrow and excellent physique. Among other things, this top-notch leather bag attracted some young girls to throw their bright eyes at them, with a hint of shyness.    //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    "Li Lo, come on!"                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//    And bolder maidens cheered.                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LHTP is ERC721Creator {
    constructor() ERC721Creator("I have three phases", "LHTP") {}
}
