
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cool breeze City, 6 houses.
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    "Splashy!                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    A small voice came from a dilapidated room in another courtyard.                                                                                                                                                                                                                            //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    In the room, a qingyi youth, some leng God looked at a transparent jade put in front. Exactly, the boy is not looking at the jade, but at the liquid inside the jade. At this point, a pungent white smoke, is slowly spreading from the liquid.                                            //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    The boy was named 6 Chen, a legitimate son of 6 families.                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    "Failed again!                                                                                                                                                                                                                                                                              //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    "Ha ha, still can't be promoted to middle pharmacist." A wry smile gradually appeared on Chen's face. He shook his head slightly and said softly.                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    6 Chen is a junior pharmacist. He became a junior pharmacist eight years ago after successfully refining the primary medicine. For eight years, Chen has been trying to improve his skills to become an intermediate pharmacist, but so far he has failed.                                  //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    It's not that Chen doesn't have a gift for refining medicine, but... He has no attributes!                                                                                                                                                                                                  //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    On tenglong big 6, people with no physical attributes are actually ordinary people. Ordinary people, unable to set foot on the road of cultivation, can not become a strong practitioner.                                                                                                   //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    In general, one of the basics of being a pharmacist is to be a practitioner. Chen's ability to become a primary apothecary with no attributes was already an accident. If Jun Chen is indeed promoted to the rank of middle pharmacist, his status in the 6th family will rise with him.    //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
//    Unfortunately, as an ordinary person without attributes, to become a middle level pharmacist, that is no different from crazy dream, in anyone's opinion, it is impossible.                                                                                                                 //
//                                                                                                                                                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CBCH is ERC721Creator {
    constructor() ERC721Creator("Cool breeze City, 6 houses.", "CBCH") {}
}
