
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Proof of Fren
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    ,lxKWMMMMMMMMMMMMW0xc,.                        .,:lxOXWMMMMMMMMMWX0koc,.. .,lxKNMMMMMMMMMMMMW0xc,.                        .,:lxOXWMMMMMMMMMWX0koc;.   .,lxKNMMMMMMMMMMMMW0xc,.                        .,:lxOXWMMMMMMMMMWX0koc,.  .,lxKWMMMMMMMMMMMMW0xc,.                        .,:lxOXWMMMMMMMMMWX0koc;..     //
//        .,lxKNMMMMMMMMMMMMNKxc,.              .':lxOKWMMMMMMMMMWX0koc;..           .,cxKNMMMMMMMMMMMMW0xc,.              .,:lxOKWMMMMMMMMMWN0koc;..            .,cxKNMMMMMMMMMMMMN0xc,.              .':lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMWKxc,.              .,:lxOXWMMMMMMMMMWN0koc;..          //
//            .,cx0NMMMMMMMMMMMMWKxl,.    .,:ldOKNWMMMMMMMMWN0kdc;..                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNWMMMMMMMMWN0kdc;'.                      .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNWMMMMMMMMWN0koc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0koc;..                //
//                .,cx0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,c:'.              .,cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.    //
//    :'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMWNOd:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdl;'.           ..,cox0XWMMNOdl:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMWNOd:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMWNO    //
//    MN0dc'.             .'cd0NWMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.             .':d0NWMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMN0dc'.             .'cd0NMMMMMMMMMWNKkdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.             .'cdONWMMMMMMMMWNKOdl;'.           ..,:ox0XWMMMMMMMMMM    //
//    MMMMWN0dc,.             .':dOXNKOdl;'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0dc'.             .':dOXNKOdl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMMMMMMWN0dc'.             .':dOXNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMMMMMMN0dc,.             .':dOXNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMN0xc,.             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMMN0xc,.             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.              .'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMM    //
//    NMMMMMMMMMMMMN0xc,.                   .,:lxOKWMMMMMMMMMWX0koc;..      .,lxKNMMMMMMMMMMMMN0xc,.                   .,:lxOXWMMMMMMMMMWX0koc;..      .,lxKXWMMMMMMMMMMMMN0xc,.                   .,:lxOXWMMMMMMMMMWX0koc;..      .,lxKWMMMMMMMMMMMMN0xc,.                   .,:lxOXWMMMMMMMMMWX0koc;..      .,lx    //
//    ,cx0NMMMMMMMMMMMMWKxl,.         .':lxOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMWKxl,.         .':ldOKNMMMMMMMMMWN0koc;..                ..,cx0NMMMMMMMMMMMMWKxl,.         .':ldOKWMMMMMMMMMWN0koc;'.                .,cx0NMMMMMMMMMMMMWKxl,.         .':lxOKNMMMMMMMMMWN0koc;..                    //
//       .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .               .,cx0NMMMMMMMMMMMMWKxl,.';ldOKNMMMMMMMMMWN0kdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .              //
//           .'cd0NMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cok0Od:'.             .'cd0NMMMMMMMMMMMMWXNWMMMMMMMMWNKkdc;'.           ..,cok0Od:'.              .'cd0NMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.         //
//               .'cd0NMMMMMMMMMMMMMMMNKkdl;'.           ..,:ox0XWMMMMMMMNOdc'.             .'cd0NMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMWN0d:'.              .'cd0NMMMMMMMMMMMMMMWNKkdl;'.           ..,cox0XWMMMMMMWNOdc'.             .'cd0NMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMWNOdc'.     //
//    '.             .':dONWMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMN0dc'.             .':dONWMMMWNKOdl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMN0dc;'.             .'cdONWMMMMNKOdl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMN0dc'.             .'cdONWMMMMNKOdl;'.           ..,:ox0XWMMMMMMMMMMMMMMMMMN0d    //
//    N0xc,.             .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl;'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMMN0xc,.             .':odl;'.            .,:oxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0dc,.             .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMM    //
//    MMMMN0xc,.                        .,:lxOXWMMMMMMMMMWX0koc,.. .,lxKNMMMMMMMMMMMMN0xc,.                        .,:lxOXWMMMMMMMMMWX0koc;.. .,lxKWMMMMMMMMMMMMMN0xc,.                        .,:lxOKWMMMMMMMMMWX0koc;.. .,lxKWMMMMMMMMMMMMN0xc,.                        .,:lxOXWMMMMMMMMMWX0koc,.. .,lxKWMMMMMMM    //
//    MMMMMMMMNKxc,.              .':ldOKWMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMNKxc,.              .':lxOKWMMMMMMMMMWX0koc;..           .,cx0NMMMMMMMMMMMMMNKxc,.              .,:lxOKWMMMMMMMMMWX0koc;..           .,lx0NMMMMMMMMMMMMNKxc,.              .':lxOKWMMMMMMMMMWN0koc;..           .,cxKNMMM    //
//    MMMMMMMMMMMMWKxl,.    .':ldOKNWMMMMMMMMWN0koc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':lxOKNMMMMMMMMMWN0kdc;..                     .,cx0NMMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0    //
//    cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNWMMMMMMMMWNKkdc;'.           ..,c:'.             .,;cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .'cx0NMMMMMMMMMMMMWKxodOKNWMMMMMMMMWN0kdc;'.           ..,c:'.             .    //
//      .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdl;'.           ..,cox0XWMMNOd:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMMN0d:'.              .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMMNOd:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMMNOdc'.              //
//          .':d0NWMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMMMMMMWN0dc'.             .':d0NMMMMMMMMMWNKOdl;'.           ..,:ox0XWMMMMMMMMMMMMN0dc'.              .':d0NWMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMWN0dc'.             .':d0NMMMMMMMMMMNKkdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.          //
//              .':dOXNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMMMMMMN0dc,.             .':dOXNKOdl;'.            .,:lx0XWMMMMMMMMMMMMMMMMMMMMMMN0dc,.              .':dOXNKOdl;'.            .,:lx0XWMMMMMMMMMMMMMMMMMMMMMMN0dc'.             .':dOXNKOdl:'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0dc'.      //
//    .             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.             .''.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,..             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.              .'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc    //
//    0xc,.                   .,:lxOKWMMMMMMMMMWX0koc;..      .,lxKNMMMMMMMMMMMMN0xc,.                   .':lxOKWMMMMMMMMMWX0koc;..      .,cxKNMMMMMMMMMMMMNX0xc,.                   .,:lxOKNWMMMMMMMMWX0koc;..      .,lxKNMMMMMMMMMMMMN0xc,.                   .':lxOKWMMMMMMMMMWX0koc;..      .,cxKNMMMMMMMMMMMM    //
//    MMMW0xl,.         .,:ldOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMWKxl,.         .':ldOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMMWKxl,.         .':ldOKNMMMMMMMMMWN0kdc;'.                .,cx0NMMMMMMMMMMMMNKxl,.         .':ldOKNMMMMMMMMMWN0kdc;..                .,cx0NMMMMMMMM    //
//    MMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNWMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNMMMMMMMMMWNKkdc;'.           .              .,cx0NMMMM    //
//    MMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWXNWMMMMMMMMWNKkdc;'.           ..,cok0Od:'.             .'cd0NMMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cok0Od:'.             .'cd0N    //
//    d0NMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMMN0dc'.             .'cd0NMMMMMMMMMMMMMMMNKOdc;'.           ..,:ox0XWMMMMMMWN0dc'.             .'cld0NMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMMN0dc'.             .'cd0NWMMMMMMMMMMMMMMNKkdl;'.           ..,:ox0XWMMMMMMMN0dc'.             .'    //
//     .':dONWMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMN0dc'.             .':dONWMMMMNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMN0dc'.              .':dONMMMMMNKOdl;'.           ..,:ox0XWMMMMMMMMMMMMMMMMMN0dc'.             .':dONMMMMWNKOdl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMN0dc'.               //
//         .':odl;'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0dc,.             .':odl;'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0dc,.              .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.           //
//                        .,:lxOKNMMMMMMMMMWX0koc;.. .,lxKWMMMMMMMMMMMMN0xc,.                        .,:lxOKWMMMMMMMMMWX0koc;.. .,cxKNMMMMMMMMMMMMN0xc,.                         .,:lxOKNMMMMMMMMMWX0koc,.. .,lxKNMMMMMMMMMMMMN0xc,.                        .,:lxOXWMMMMMMMMMWX0koc,.. .,lxKNMMMMMMMMMMMMN0xc,.       //
//                  .':lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMNKxl,.              .':lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMNKxl,.               .':lxOKWMMMMMMMMMWX0kdc;..           .,cx0NMMMMMMMMMMMMNKxl,.              .':lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMNKxc,    //
//    xl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMWKOxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMW    //
//    MMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,c:'.             .,cd0NMMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMWNKkdc;'.           ..,c:'.             .,cd0NMMMMMMMMM    //
//    MMMMMMMMMMMMMWNKkdl;'.           ..,cox0XWMWNOd:'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,:ox0XWMMN0d:'.             .'cd0NMMMMMMMMMMMMMMMMMMMMWNKkdc;'.           ..,cox0XWMMNOdc'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdl;'.           ..,cox0XWMMNOdc'.             .'cd0NMMMMM    //
//    MMMMMMMMNKOdl;'.           ..,:ox0XWMMMMMMMMMMMMN0dc'.             .':dONMMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.             .':dONMMMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.             .'cd0NMMMMMMMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMN0dc'.             .':d0NW    //
//    OXNKOdl:'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0dc,.             .':dOXNKOdl;'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0xc'.             .':dxOXNKOdl:'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0dc,.             .':dOXNKOdl;'.            .,:lxOXWMMMMMMMMMMMMMMMMMMMMMMN0dc,.             .':    //
//     .'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.             .''.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.               .'.            .,:lxOXWMMMMMMMMMWX0koc:lxKWMMMMMMMMMMMMN0xc,.             ..'.            .,:lxOXWMMMMMMMMMWX0koc:lxKNMMMMMMMMMMMMN0xc,.                //
//              .,:lxOKNMMMMMMMMMWX0koc;..      .,cxKNMMMMMMMMMMMMN0xc,.                   .,:lxOKWMMMMMMMMMWX0koc;..      .,lx0NMMMMMMMMMMMMN0xc,.                    .,:lxOKWMMMMMMMMMWX0koc;..      .,cxKNMMMMMMMMMMMMN0xc,.                   .,:lxOXWMMMMMMMMMWN0koc;..      .,cxKNMMMMMMMMMMMMN0xc,.            //
//        .':ldOKNMMMMMMMMMWN0kdc;..                .,cx0NMMMMMMMMMMMMWKxl,.         .':ldOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMWKxl,.          .':ldOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMWKxl,.         .':lxOKNMMMMMMMMMWN0koc;..                .,cx0NMMMMMMMMMMMMWKxl,.        //
//    :ldOKNMMMMMMMMMWNKkdc;'.           ..             .,cx0NMMMMMMMMMMMMWKxl,.':ldOKNWMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.';:ldOKNWMMMMMMMMWNKkdc;'.           .              .'cx0NMMMMMMMMMMMMWKxl,.';ldOKNMMMMMMMMMWNKkdc;'.           .              .,cx0NMMMMMMMMMMMMWKxl,.    //
//    MMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWXNWMMMMMMMMWNKkdc;'.           ..,cok0Od:'.             .'cd0NMMMMMMMMMMMMWXNWMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWXNMMMMMMMMMWNKkdc;'.           ..,cox0Od:'.             .'cd0NMMMMMMMMMMMMWX    //
//    MMMWNKOdl;'.           ..,:ox0XWMMMMMMMN0dc'.             .'cd0NWMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMWN0dc'.             .'cdONMMMMMMMMMMMMMMMWNKkdl;'.            .,:ox0XWMMMMMMMN0dc'.             .'cdONMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMMMMMMN0dc'.             .'cd0NWMMMMMMMMM    //
//    Odl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMN0dc'.             .':dONWMMMWNKOdl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMN0dc,.             .':dONWMMMMNK0Odl;'.            .,:ox0XWMMMMMMMMMMMMMMMMMN0dc'.             .':dONWMMMMNKOdl;'.            .,:oxOXWMMMMMMMMMMMMMMMMMN0dc,.             .':dONWMMMMN    //
//                .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl:'..            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl:'.            .,:lxOXWMMMMMMMMMWX0OKWMMMMMMMMMMMMN0xc,.             .':odl:'    //
//          .,:lxOKWMMMMMMMMMWX0koc;.. .,lxKNMMMMMMMMMMMMN0xc,.                        .,:lxOXWMMMMMMMMMWX0koc;.. .,lxKNMMMMMMMMMMMMN0xc,.                         .,:lxOKWMMMMMMMMMWX0koc;.. .,lxKNMMMMMMMMMMMMN0xc,.                        .':lxOKNMMMMMMMMMWX0koc,.. .,lxKWMMMMMMMMMMMMN0xc,.                     //
//    .':lxOKNMMMMMMMMMWX0koc;..           .,cx0NMMMMMMMMMMMMWKxl,.              .':lxOKNMMMMMMMMMWN0koc;..           .,cxKNMMMMMMMMMMMMNKxc,.              ..':lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMNKxc,.              .,:lxOKNMMMMMMMMMWN0koc;..           .,cx0NMMMMMMMMMMMMWKxl,.                 //
//    KNMMMMMMMMMWN0kdc;..                     .,cx0NMMMMMMMMMMMMWKxl,.    .';ldOKNMMMMMMMMMWN0koc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ldO0KNMMMMMMMMMWN0kdc;'.                     .,cd0NMMMMMMMMMMMMWKxl,.    .':ldOKNMMMMMMMMMWN0kdc;'.                     .,cx0NMMMMMMMMMMMMWKxl,.    .':ld    //
//    MMMMMWNKkdc;'.           ..,::'.             .'cd0NMMMMMMMMMMMMWKxodOKNWMMMMMMMMWNKkdc;'.           ..,::'.             .'cd0NMMMMMMMMMMMMWKxodOKNMMMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNWMMMMMMMMWNKkdc;'.           ..,::'.             .,cd0NMMMMMMMMMMMMWKxodOKNMMM    //
//    NKkdl;'.           ..,:ox0XWMMNOdc'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKkdl;'.           ..,:ox0XWMMNOdc'.             .'cd0NMMMMMMMMMMMMMMMMMMMWWNKOdc;'.           ..,:ox0XWMWN0dc'.             .'cd0NMMMMMMMMMMMMMMMMMMMWNKOdl;'.           ..,:ox0                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DDM is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
