
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: A plot between King and Chu
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//    Samsara squad everyone looked at this assembly line, is also a face meng.                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//    Chu Xuan took out a set of black clothes, expressionless to show the public.                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//    "The Adelman suit is no less defensible than The rough-hewn wang Suit. It's more flexible, more close-fitting, and has a cushion-shock design that releases a lot of kinetic energy from impact."                                                                                                                                                                //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
//    ChuXuan said and pulled out a set of exoskeleton, said: "individual exoskeleton, the main structure I also used the" adleman alloy, tie-in black battery technology, can let a person continues to run at a speed of 60 kilometers per hour six hours, if nuclear reactor core energy into the ark, then the data will be higher, but also can make it fly. "    //
//                                                                                                                                                                                                                                                                                                                                                                     //
//                                                                                                                                                                                                                                                                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract APBK is ERC721Creator {
    constructor() ERC721Creator("A plot between King and Chu", "APBK") {}
}
