// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: PhoenixPunk2317
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ5BBBYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJG@@@YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ#@@&BB#@@@GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ&@@@GGG@@@GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ&@@&GGB@@@GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ&@@&GGB@@@GJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJY555555&@@&GGB@@@B555555JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJ?G@@@@@@@@@&GGB@@@@@@@@@@YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJG###BBBBBB@@@@GGB@@@&BBBBBB###5JJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJYYJ&@@&!7777!#@@&GGG@@@5!7777?@@@GJYYJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJJJ777!!!?JJJ???JJJ?777777JJJ#@@#JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777!!!77777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777!!!77777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P77777777777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P77777777777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P77777777777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P77777?YYYYYYJ777777777?YYYYYY&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJYYY5@@@P77777?GGGPPP5777777777JGGGPPP&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJG@@@J?J?77777?@@@GJJ?777777777P@@@YJJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJG@@@?77777777?###5???777777777Y###J??&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJG@@@?77777777777777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJG@@@@&@577777777777777777777777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJP&&&@@@G7??777777777777?555555Y777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@BYYJ777777777777?@@@@@@&777777&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJYYJJJ777777777?PPPPPP5777JJJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJYYYYY??????????7777777???YYY&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJYYYYYYYYYYYYJJJJJJJJJJYYYYYJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJYYYYYYYYYYYP#########BYYYYYJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@GJYYYYYYYYYYJG@@@@@@@@@&JYYYYJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P7??YYYYYYYYYY5555555555YYYJJJ&@@&JJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P77?JJJYYYYYYYYYYYYYYYYYYYYGBG#&&BJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777YYYYYYYYYYYYYYYYYYY5@@@G?JJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777???B@&&@@@@@@@@@@@@&GPGYJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777777&@@@@@@@@@@@@@@@&YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJY@@@P777777777&@@&JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//                                                                                        //
//                                                                                        //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract PP2317 is ERC1155Creator {
    constructor() ERC1155Creator("PhoenixPunk2317", "PP2317") {}
}
