// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Eyes
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                     .                                              //
//                                                                                                                                                                                                                                                                 .,lkOx:.                                           //
//                                                                                                                                                                                                                                                                .dXNNXK0O;                                          //
//                                                                                                                                                                                                                                                                .kNNNXK00c                                          //
//                                                                                                                                                                                                                                                                .xNNXK000c                                          //
//                                                                                                                                                                                                                                                                 ,okK0ko:.                                          //
//                                                                                                                                                                                                                                                                   .',.                                             //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                          .'.                                                                                                                                                                                                                                       //
//                                                                       .;d0XKx:'.                                                                                                                                                                                                                                   //
//                                                                   .,lkKNNNNNNNXOo;.                                                                    .:lol;.                                                                         .;ll,.                                                                      //
//                                                                .:oOXNNNNXNNNNNNNXX0xc'                                                             .,cxKNNNXKkc.                                                                    ':d0XNNKkc.                                                                    //
//                                                            .,cxKNNNXXNNNNNNNXNNNNNNNX0ko;.                                                      .;oOXNXXNNNXKKk'                                                                .,lkXNNXNNXXXO,   ..                                                               //
//                                                         .;o0XNNXNNNNNNNXXNNNNNNNNNNNNNNNXOo;.                                                'cxKXNNNXXKKKKKKKk'                                                             .:d0XNNNNXXXXXXXO:,lk0Oo;.                                                            //
//                                                      'cxKNNNNNNNNNNNNNXXXXXXNNNNNNNNNNNNXKKk'                                            .;oOKNNNXKKXXKKKKKKKKk'                                                         .,lkKNNNNXXNNXXXXXXXXKXNNNXXKd.                                                           //
//                                                  .;okKNNNNXXNNNNNNXXXXXXXXKKXNNNNNNNXXXXXKKk'                                         'cx0XNNXXXXKkdxO0KKKKKKKk'                                                      .:dOXNNXXXNX0kk0XXXXNNNNNXXNNNXXx. .:c:.                                                     //
//                                                 ;OXNNNXNNWNNNNXXXXXXXXXXKK0KXNNNNNNXXXKKKK0k,                                     .;lkKNNXXNNX0x:'. .l00KKKKKKk'               .,,.                               .,cxKNNXXNNXKkl,..;kXNNNNXXNNXXXXXXX0dxKNNKOo'                                                   //
//                                                 cXNNNNNNNNXXNXXXKKKKKKK000KXXXNNNNNXKKK00OOOOd:'.                              .:xKXNXXNXXXXKd,.     :0KK0KKKKk'           .'cx0XKkl,                          .;d0XNXNNNXXXKx;..'cxKNNXNNXXXXXXXXXXXNNNXXNXK00l.                                                  //
//                                                 cXNXXNNNNXKKKKKKKK0000KKKKXNNNNNNNNXK000000KXXXKOo;.                           ;KNNNXKKXXXKk;.       :KXXKKKKKO,        .;oOXNNNNXKKk.                         ;KNNNXXXXXXXOl,;oOXNNNNXXXXXKKKKXXXNNNNNXKKK0000l.                                                  //
//                                                 cKNXXXNNXKKKKKKKK0000KXXXNNNNNNNXXXXXXXNXXXNNNNNNXKOc.                         :KNNXKKKXKKd.         :KNXXXKKKKl.    'cx0XNNNXKKKKKKk.                         ;KNNXXXXXXXXOk0XNNNXXNNXXNXKKKXNNNNNXKKKK0000000l.                                                  //
//                                                 cXXXXXXNXKKKKKKKK00KKKNNNNNXXNNXXXXKXNNNNNNNNXXXXKKKd.                         :KNXXKKKKKd.          :KNNXXXKKKO;.;lkKNNXXXXXKKKKKKKx.                         ;KNXXXXNXXXNNNNXXNNXXXXNNNNNNNNXXKXXK00000000000l.                                                  //
//                                                 cXNNXXXXXKKKKKKKK00KKKXNNNNXXXXXXXKKKXNNNNNNXKKKKKKKd.                         :KNXXKKKKk'           :KNNNXXKKXXKKXNXXXXKKOO000KKKKKx.                         ;KNXXXNNXXNNNNNXXNXXXNNNNNNXXXXXK000000O0K000000l.                                                  //
//                                                 cKXXXNNNXKKKKK000OO00KKXNNXXXXXKKKK0KXNNNNNNKKKKKK00d.                         :KNNXKXXKc            :KNNNNNNNNNXXNXKKOd:,.,d00KKKKKx.                         ;KNNXXXXXXXNNXXNNXXXXNNNXNXKK0000KKKKKKOOKKK0000l.                                                  //
//                                                 cXXXXXXNXKK0000OO00000KXXNXXKKK000KXXXXNNNNNKK00000Kd.                         :KNXXXXXO,            ;KNNNNNNNNXKKKKOl.     cKK00KKKx.                         ;KNXXXXXKKXNXXXNXXXNNNXKKKK00000KKKKKK0OOKKK0000l.                                                  //
//                                                 cXNNXXXXXK00KK000000KXXXXXXKKKKKKKXNNNNNNNNXK0000KKKd.                         :KXXXKKKO,            ;KNNNNXKKKKK000Ol'     lXXK000Kx.                         ;0XXXXXXK0XNXXXXXXXNNXK000000KKKXKKKKK0O0KKKK000l.                                                  //
//                                                 cXNXNXXXXXXXNNXXXXXXXNNXXXXXNNNNNNNNNNNNXXKK00KKKK0Kd.                         :KNXXKKKKc            :KNNNXKK00000KKK0Od:,';kXXXK0KKx.                         ;KNXXXXXKKXNXXXXXXXXNXK00000KXXXXKKXKK00KKKK0000l.                                                  //
//                                                 cXXXXXXXXXXNNNNNNNXXXXXXXXKXNNNNNNNXXXXXKKK000KK000Kd.                         :KNNXXKKXk'           :KNNXK00000Ok0KK00KKKKKXNXXXKKKx.                         ;KNXXXXXKKXNXXXXXKKXNXK0000KXNXKKXXXK0KKKKK00000l.                                                  //
//                                                 cXNNXXXXXXNXXXNNNXXXXXXXKK0KXNNNNNNXKKKKKK00000000KKd.                         :KNNXXKKKKd.          :KNNXK0000k;.':dk0XXNXXNNNNKKKKx.                         ;KNXXXXXKKXNXXXXXKKXNXK0000KXXKXK0kod0XKKK000000l.                                                  //
//                                                 ,xKXNNNNXXXXXXNXXXKXKKKK00KKXXNNNNNXKKK000000KKKKK0k:.                         :KNNXXXKKKKd.         :KNXXK0000c     .;lkKXNNNNNXKKKx.                         ;KNXXXXXKKXNXXXXXKKXNXK00000KKOdc''c0NXKK000000Oc                                                   //
//                                                   .:d0XNXXXXXXXXXXKK0000KKXNXNNNNNNK000000KKKKKOdc'.                           ;KNNXXXXXXXKk;        :KNXXK000k,        .,cx0XNNXKKKx.                         ;0NNXKXXKKXNXXXXXKKXNXK000Oxl;. .:kXNXXK0000kd:'.                                                   //
//                                                      .,lk0XNNNXXXXKKXXXXXXNNNNNNXXXK0000KKK0ko;.                               .;okKXXNNNNNXKx;.     :KNXXK000x.            .;oO0Odc'                          .;oOK0ko:dXNXXXXXKKXNXK000k:..;oOXXXKK00Oxl;.                                                       //
//                                                          .:d0XXNXXXNNNNNNNNNXNNXKKK000K0Odc,.                                     .'cx0XNNNNNNXOl,. .dXXXXK000x'               ...                                .''.  cXNNXXXXKKXNXK0000OkO0KKK000Odc'.                                                          //
//                                                             .;okKXXXXNNNNNXXKKKK00000ko;.                                             .;oOXNNNNWNNKOOKNNXXK000x'                                                        ;OXXXXX0k0XNXK0000000000Oxl;.                                                              //
//                                                                .':d0XNNNNXXK00000Odc,.                                                   .,cxKNNNNNNNNNNNXX000x'                                                         .,ldo:..dXNXK0000000Odc'.                                                                 //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JKB is ERC721Creator {
    constructor() ERC721Creator("Eyes", "JKB") {}
}
